### PR TITLE
added wiki tags

### PR DESCRIPTION
**Pull request by dieterwarson**

### CODE REVIEW

**Comment by matkoniecz** [comment]
Great! Can you add also change that would fix from

> "brand:wikipedia": "en:Hilton Hotels %26 Resorts",

to

> "brand:wikipedia": "en:Hilton Hotels & Resorts",

?

**Comment by matkoniecz** [comment]
Thank you again for help!

**Comment by matkoniecz** [comment]
I opened #1879 to discuss what should be done with "Ibis" and "Ibis Hotel" duplicate, there is no need to do it here.

**Comment by dieterwarson** [comment]
No problem, thanks for merging!

**Pull request merged**
