### PR TITLE
Add and fix supermarkets in dk

### PR DESCRIPTION
**Pull request by mikini**
* add Løvbjerg
* add ABC Lavpris

* change Coop 365discount to new branding without Coop
* remove fakta in dk; has been transformed into 365discount
* add fakta in de; border shops still fakta branded

### CODE REVIEW

**Comment by KasperFranz** [comment]
This brings up a question - what are the criteria for the number of shops required to be added to NSI - Fakta Germany only got three shops

**Comment by LaoshuBaby** [comment]
> This brings up a question - what are the criteria for the number of shops required to be added to NSI - Fakta Germany only got three shops

For a canonical brand, 50 stores are usually needed, and at least 30 are recommended.  For countries where OSM data is seriously lacking and the country is small or the local mapper considers it important, we think at least 10 are needed.

However, if this brand operates in Germany and Denmark, the number of stores can be totaled

**Comment by KasperFranz** [comment]
> > This brings up a question - what are the criteria for the number of shops required to be added to NSI - Fakta Germany only got three shops
> 
> For a canonical brand, 50 stores are usually needed, and at least 30 are recommended. For countries where OSM data is seriously lacking and the country is small or the local mapper considers it important, we think at least 10 are needed.
> 
> However, if this brand operates in Germany and Denmark, the number of stores can be totaled

I think it would be good to get that documented somewhere so we do not flood NSI with brands/operators etc that is less than that threshold.

In this instance Fakta denmark is closed

**Comment by mikini** [comment]
Those numbers are a surprise to me. I have found no eligibility requirements anywhere in the current documentation. Who have decided those and how are they supposed to be upheld?

For a small country as [Denmark](https://en.wikipedia.org/wiki/Denmark) (~6 mio. inhabitants) adhering to those would make NSI sparsely populated.

Both ABC Lavpris and Løvbjerg added in this PR would not meet the 30 store threshold with their [15](https://www.abc-lavpris.dk/butikker) & [17](https://www.lovbjerg.dk/butikker-aabningstider) stores respectively, but I consider them as well-known chains.

I would probably not have added fakta DE by itself with its 3 stores but it came about from reusing the DK entry from the recent transformation to 365discount in DK (~300 stores).

**Comment by LaoshuBaby** [comment]
> I think it would be good to get that documented somewhere

> Those numbers are a surprise to me. I have found no eligibility requirements anywhere in the current documentation.

https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case#notability

It was not documented at first and was only used as a magic number in nsi-collector, but it has been recorded in this project for some time.

> but I consider them as well-known chains.

Yes, so I've said above that if it is well-known in the local or there are many factors such as population restrictions, it is really difficult to meet the number of branches, but it is well-known enough, at least 10 is the final bottom line.

**Comment by KasperFranz** [comment]
> If the fakta shares same entry in Germany and Denmark (shares the same wikidata qid), it is acceptable, and the total number in the two countries can meet the notability requirements, it can be added.

They are two different qid [Q123942180](https://www.wikidata.org/wiki/Q123942180) and [Q3172238](https://www.wikidata.org/wiki/Q3172238).


The requirement for minimum shops are not very visible, so it might be worth getting it better documented

**Comment by mikini** [comment]
I've removed fakta completely and polished some matchNames for Danish supermarkets, hopefully the PR is ok for merging now?

Just as a thought exercise to put things in an international perspective for the threshold values; the largest Danish national supermarket Bilka, known by all Danes, has [18 locations](https://www.bilka.dk/kundeservice/info/find-din-bilka/c/find-din-bilka/).

**Comment by mikini** [comment]
Also added more elaborate instructions about this to the ["Judge Case" wiki](https://github.com/osmlab/name-suggestion-index/wiki/Judge-Case/_compare/209b66d963e4c85a631021bbc53a5cb673a90e6b...91928384011d47ba498854eec454e73c6443f241), and attempted a little more general cleaning.

**Comment by KasperFranz** [comment]
LGTM

**Pull request merged**
