### PR TITLE
Rozetka permanently closed its parcel lockers

### PR DESCRIPTION
**Pull request by serhii-muchychka**

### CODE REVIEW

**Comment by Cj-Malone** [comment]
Was this meant to include Cargus Ship & Go? The website is still active.

https://www.cargus.ro/en/point-location/

**Comment by Cj-Malone** [comment]
@DnaX Since you requested Ship&Go in #7502, do you know if it's still active?

**Comment by DnaX** [comment]
@Cj-Malone I don't know about Rozetka (Ukranian I suppose) because I'm living betweed italy and Romania. Cargus Ship&Go it's instead a Romanian brand.

**Comment by DnaX** [comment]
@Cj-Malone As I know yes, they installed the parcel lockers in Bucharest less then 1 year ago.

**Comment by Cj-Malone** [comment]
Thank you. I've re added it in https://github.com/osmlab/name-suggestion-index/commit/ae0944207ffbd3223da006236b7ba980e873cb48. If anyone thinks it's is actually closed, please let me know.

**Comment by serhii-muchychka** [comment]
I didn't immediately understand what happened. It seems that the problem came in the merge commit. My original patch looks good: https://github.com/osmlab/name-suggestion-index/pull/7927/commits/d52026b1eed00aaefb105328621eff351d3d69c6

**Pull request merged**
