### PR TITLE
Add Platte Valley Bank

### PR DESCRIPTION
**Pull request by xorgy**

### CODE REVIEW

**Comment by xorgy** [comment]
Not to be confused with Platte Valley Bank (Missouri).

**Comment by arch0345** [comment]
Thanks @xorgy and welcome! It looks like they might also have some locations in Colorado: https://pvbank.com/locations/

**Comment by xorgy** [comment]
> Thanks @xorgy and welcome! It looks like they might also have some locations in Colorado: https://pvbank.com/locations/

It's a bit complicated, those are "in network" but they don't belong to the same brand.

**Comment by jleedev** [comment]
Also not to be confused with this single-branch bank in the other half of Nebraska: https://www.pvbonline.com/home/about/hours

**Comment by jleedev** [comment]
Platte Valley Bank of Missouri might no longer exist: https://www.centralbank.net/central-bancompany/recent-news/central-bancompany-platte-valley-bank-merger/

**Comment by 1ec5** [comment]
> Also not to be confused with this single-branch bank in the other half of Nebraska: https://www.pvbonline.com/home/about/hours

[Changeset 124,703,646](https://www.openstreetmap.org/changeset/124703646) maps this bank and preemptively tags it with `not:brand:wikidata` to avoid confusion.

**Pull request merged**
