### PR TITLE
Add Hello Cycling and Docomo Bike Share rental services

### PR DESCRIPTION
**Pull request by sguinetti**
This pull request adds Hello Cycling and Docomo Bike Share services. Note: The main brand is under Docomo Bike Share, and each city uses a different name operated by municipal ward (plus I'm not sure which network put to the POI). For example, Tokyo and Yokohama.

### CODE REVIEW

**Comment by bhousel** [comment]
I looked at this but I'm having trouble understanding how they all relate to each other.
They all link to the same wikidata QID but it shows up as "OpenStreet" for me.  Some of these entries link to an "OpenStreet" wikipedia page, and others link to a different page.  The names don't really match up. 

I haven't looked at the logos, but I wouldn't want to show a user the wrong logo because we have an entry linked to a parent company with a different logo, or I wouldn't want to set a wrong name tag.

**Comment by sguinetti** [comment]
That is true, OpenStreet is a company with a different name that operates the Hello Cycling brand and others. So would it be best for me to create a new Wikidata entry?

**Comment by bhousel** [comment]
Ok, I see the Hello Cycling one is changed, but the other ones still link to OpenStreet?

**Comment by sguinetti** [comment]
> Ok, I see the Hello Cycling one is changed, but the other ones still link to OpenStreet?

Yes. I changed to new Wikidata about Hello Cycling only. Also, I deleted the Wikipedia link.

**Comment by bhousel** [comment]
```js
  "amenity/bicycle_rental|baybike": {
    "countryCodes": ["jp"],
    "tags": {
      "amenity": "bicycle_rental",
      "brand": "ドコモ・バイクシェア",
      "brand:en": "Docomo Bike Share",
      "brand:ja": "ドコモ・バイクシェア",
      "brand:wikidata": "Q43593262",
      "brand:wikipedia": "ja:ドコモ・バイクシェア",
...
```
What I mean is..

This "baybike" entry has
- `"brand:wikipedia": "ja:ドコモ・バイクシェア"` corresponds to [this Wikipedia page](https://ja.wikipedia.org/wiki/%E3%83%89%E3%82%B3%E3%83%A2%E3%83%BB%E3%83%90%E3%82%A4%E3%82%AF%E3%82%B7%E3%82%A7%E3%82%A2) for "DOCOMO bike share, Inc.", which has QID [Q55533296](https://www.wikidata.org/wiki/Q55533296)
- But the entry instead has `"brand:wikidata": "Q43593262"`, which links to [this Wikidata page](https://www.wikidata.org/wiki/Q43593262) for "OpenStreet, Inc"
- neither "Docomo Bike Share" nor "OpenStreet" is "baybike".  If we show users a brand logo for either of these things, it will look wrong to them.  If "baybike" is a unique brand, "baybike" is what should go in the brand tags (even if "baybike" is operated or owned by some other entity).

I'm saying the whole thing looks all mismatched.

**Comment by sguinetti** [comment]
Right. I misunderstood what you mean. I apologize. I correct it again.

**Comment by bhousel** [comment]
Thanks for cleaning it up @sguinetti - it all looks great now :+1: 
Would be awesome to see more bike share locations on the map!

**Pull request merged**
