### PR TITLE
add costco optician

### PR DESCRIPTION
**Pull request by modaserMoj**

### CODE REVIEW

**Review by Binnette — APPROVED** [review]
Seems good 👍

**Review by bhousel — CHANGES_REQUESTED** [review]
Looks like they are actually named like as "Costco Optical" - can you change the name and displayname?
https://www.costco.com/optical.html

**Comment by modaserMoj** [comment]
> 
> 
> Looks like they are actually named like as "Costco Optical" - can you change the name and displayname?
> https://www.costco.com/optical.html

I made the requested change

**Review by bhousel — APPROVED** [review]

**Comment by bhousel** [comment]
Thanks @modaserMoj 👍

**Pull request merged**
