### PR TITLE
Modify 3 bank

### PR DESCRIPTION
**Pull request by LaoshuBaby**
## Modify:
   + BOC
   + CCB
   + ICBC

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
This PR is because when I want to put a bank in China , I inputed ```ICBC``` and it give me a suggestion!

But when I inputed ```工商银行``` it give me 2 suggestion!

Then I use the wikidata to search in the json and find it have a oversea version and a Chinese only version

So to avoid double suggestion in mainland of China, I added ```exclude``` in those 3 bank's oversea version.

**Comment by LaoshuBaby** [comment]
Based on my observations on the PR records of osmlab/name-suggestion-index, especially those PRs that have not been agreed to merge into the master for a long time, I think my addition today may cause arguments like #4855 and #4959 

Therefore, I will let this commit that may cause controversy as this PR separately, so as not to affect the merge of other more basic and no-controversial commits.

Proposing multiple PRs in the same day does cause a lot of trouble for everyone, but this is based on the purpose of separating different issues as much as possible to maintenance name-suggestion-index more carefully. Based on this thought, I hope administrators can forgive and understand me and what I do.

望各位领导批评指正！

**Comment by bhousel** [comment]
> So to avoid double suggestion in mainland of China, I added `exclude` in those 3 bank's oversea version.

Thanks!  yes I'd like to see more of this kind of local scope in the index.  We probably have too many `001` entries..

> Proposing multiple PRs in the same day does cause a lot of trouble for everyone,

It's no problem for me as long as they are simple  👍

**Comment by bhousel** [comment]
BTW thanks @LaoshuBaby for all your contributions recently! To speed things up, I've invited you to be a maintainer on this project.  Feel free to triage issues, merge PRs, and commit directly to the main branch anything that you feel good about. 🙇

**Comment by LaoshuBaby** [comment]
> 
> 
> BTW thanks @LaoshuBaby for all your contributions recently! To speed things up, I've invited you to be a maintainer on this project. Feel free to triage issues, merge PRs, and commit directly to the main branch anything that you feel good about. 🙇

**Thank you for trusting me!**

新人上岗，望今后诸位前辈能多多关照！

**Pull request merged**
