### PR TITLE
Added internet cafes

### PR DESCRIPTION
**Pull request by AnjaliGGeetha**
Added Akshaya & CSC.

### CODE REVIEW

**Review by bhousel — CHANGES_REQUESTED** [review]
Looks like the Wikidata ID for Akshaya project is Q4701821, and maybe Q99562093 is a duplicate that should be merged with the existing entry?

I see you've edited both of these on Wikidata in the past few days - what's your intent with having 2 separate QIDs?

**Comment by AnjaliGGeetha** [comment]
Akshaya center is different from Akshaya project. Akshaya project started as e-literacy campaign by the government of Kerala. As part of that, private entrepreneurs were asked to establish internet kiosks where government e-services can be accessed by common people. What we are mapping is Akshaya centers which are not owned by the government but owned by private entrepreneurs. Hence added a separate wikidata entry for Akshaya Center.

**Comment by bhousel** [comment]
ok, thanks for the clarification @AnjaliGGeetha  - in that case, can you remove the `"brand:wikipedia": "en:Akshaya project",` tag, since that really doesn't go with the Q99562093 id for the Akshaya Centers?

**Comment by AnjaliGGeetha** [comment]
Ok, Removed wikipedia tag from Akshaya Center

**Comment by Identitaet** [comment]
closed cause fixed in #4211

**Pull request closed without merging**
