### PR TITLE
migrate 99 speedmart

### PR DESCRIPTION
**Pull request by MASangys**

### CODE REVIEW

**Comment by Adamant36** [comment]
It looks like 99 Speedmart is already in the index. So, I'm going to close this. Unless there is a reason not to.

**Comment by MASangys** [comment]
Please reopen it

**Comment by Adamant36** [comment]
I'm confused though. What's the difference between this entry and the one that's already in the index that warrents the PR?

**Comment by MASangys** [comment]
Originally it was in convenience store, but it should be variety store. Thats all

**Comment by Adamant36** [comment]
That makes sense. I was thrown off because you didn't delete the convience store entry. So I thought you were just creating a duplicate entry for some reason. I'm pretty sure you have to delete the convience store entry since your moving it. The match tag should make sure the objects all get updated.

**Comment by MASangys** [comment]
I already make PR at there also right?
https://github.com/osmlab/name-suggestion-index/pull/4002

**Comment by Adamant36** [comment]
Is 99 Speedmart a variety store, convenience store, or both?

**Comment by MASangys** [comment]
Not at all, they are all variety store, as they sells daily goods and they use 2 lots compare to other convenience store cuz they put more things inside a store, juts called it mini market locally.

**Comment by Adamant36** [comment]
Hhmm what's the difference on the ground between the 99 Speedmarts that are Pasar Minis and the ones that aren't then?

**Comment by MASangys** [comment]
Pasar Mini=Mini market in Bahasa Melayu (Malay)

the ones that aren't then?
-So far I didnt notice they opened a real convenience store, may be at the fuel station there will be, but they dont open at there and in the mall. 

https://www.google.com/search?q=inside+99+speedmart&client=ms-android-samsung-tpin&prmd=imnv&sxsrf=ALeKk02V4daPW0VW5xMLcUG6YjZ4eo9hvA:1593407830699&source=lnms&tbm=vid&sa=X&ved=2ahUKEwjPsuzdoqbqAhUx7XMBHW3mDZwQ_AUoBHoECA8QBA&cshid=1593407854393&biw=360&bih=560#ip=1

There are some video inside the mini market.

Plus this, they have 3 branch in Singapore now.
https://insideretail.asia/2020/02/27/malaysias-99-speedmart-launches-in-singapore/

**Comment by Adamant36** [comment]
Alright. I'm thinking the best option would be to the convenience store entry as is for now at least so people have the option to choose just in case. Then just add a no match tag to this for it. Which I'll probably do after I merge it.

**Comment by bhousel** [comment]
> Alright. I'm thinking the best option would be to the convenience store entry as is for now at least so people have the option to choose just in case.

If he says they are all variety stores, can't we just let them all be variety stores?

**Comment by bhousel** [comment]
Yeah looked at it some more, and I think this is ok.  The line between variety store and convenience store is pretty thin.
Some variety stores (like Don Quixote) can be like huge multi story businesses that sell everything you can imagine.

**Comment by MASangys** [comment]
Thanks for updating

**Comment by Adamant36** [comment]
"If he says they are all variety stores, can't we just let them all be variety stores?" 

Yeah of course. Its always 50/50 on how good research is anyway and I don't care that much about it. Like you said in the other PR its not like these things can't be changed again if it turns out not to be correct.

**Pull request merged**
