### PR TITLE
Add Brico Io

### LINKED ISSUE #7548: Add Italian DIY chain "Brico Io"
It's an Italian chain with more than 100 shops. See here: https://www.wikidata.org/wiki/Q15965705

Suggested tagging:

```
brand=Brico Io
brand:wikidata=Q15965705
name=Brico Io
shop=doityourself
```

### PR DESCRIPTION
**Pull request by arrival-spring**
Closes #7548

### CODE REVIEW

**Comment by Cj-Malone** [comment]
Should it be "Brico io" or "Brico Io"?

**Comment by arrival-spring** [comment]
> Should it be "Brico io" or "Brico Io"?

Wikipedia and Wikidata both have it as Brico Io, but the website does seem to style it as Brico io

Ping @DnaX

**Comment by DnaX** [comment]
@arrival-spring I checked the official logos and seems it's better the form "Brico io" with lowercase "io".

**Comment by arrival-spring** [comment]
Changed, thanks

**Comment by Cj-Malone** [comment]
Thanks everyone

**Pull request merged**
