### PR TITLE
Remove default Azerbaijanian for pharmacy

### PR DESCRIPTION
**Pull request by ferdinand0101**

### CODE REVIEW

**Comment by ferdinand0101** [comment]
removes Aptek from suggestion list since it's the name for pharmacy in Azerbaijanian

**Comment by Adamant36** [comment]
Hi there. Are places like this just state run generics or something instead of being a "brand"? It look like there's a bunch of them with the same kind of signage etc. 

Aptek

Aptek 2

**Comment by bhousel** [comment]
> Are places like this just state run generics or something instead of being a "brand"? It look like there's a bunch of them with the same kind of signage etc.

It's ok!  State-run stores with a common branding can be included.. We have a few already, check out the discussion on #2028

**Comment by Adamant36** [comment]
>It's ok! State-run stores with a common branding can be included.

I know. That's why I was asking. I figured if it was a state brand (not a generic) we could keep it in the index and just create a Wikidata entry for it. Instead of removing it from the pharmacy file altogether. Which is what this PR did 🤷‍♂

**Comment by bhousel** [comment]
> I know. That's why I was asking. I figured if it was a state brand (not a generic) we could keep it in the index and just create a Wikidata entry for it. Instead of removing it from the pharmacy file altogether. Which is what this PR did

oh gotcha.. Yeah I was pretty confused, as the original title didn't say what it was about.

@ferdinand0101 are you sure you want this removed?  It looks like something that we would normally include as a brand.  Ideally, someone local gets to decide.

**Pull request merged**
