### PR TITLE
Update fuel.json added Petrol AD

### PR DESCRIPTION
**Pull request by jhutton1**

### CODE REVIEW

**Comment by Dimitar5555** [comment]
Petrol is already in NSI. See https://nsi.guide/index.html?t=brands&k=amenity&v=fuel&tt=петрол#petrol-b450da

**Comment by Cj-Malone** [comment]
@Dimitar5555 I suspect "petrol" as a match name was what "fixed" it in Slovenia, so this may fix #6552 too.

**Comment by jhutton1** [comment]
Sorry, I missed that.  Closing PR as not needed.

**Review by Dimitar5555 — APPROVED** [review]
> @Dimitar5555 I suspect "petrol" as a match name was what "fixed" it in Slovenia, so this may fix #6552 too.

I'm not sure if it will work but it seems like it won't break anything. I will let you know what the result is.

**Pull request merged**
