### PR TITLE
added Reál

### PR DESCRIPTION
**Pull request by amous4822**
Added Real to department_store file. 
#4443

### CODE REVIEW

**Review by bhousel — CHANGES_REQUESTED** [review]
Few things:
- From [their website](https://real.hu/), it looks more like a supermarket or convenience store (or both?)
- This long name is definitely not how they refer to themselves, nor how people would expect the points to appear on a map.  Why not just "Reál"?

**Comment by amous4822** [comment]
should I put it only under supermarket ? one of the banners in [the website](real.hu) carousel mentions it's a super store.

**Comment by bhousel** [comment]
> should I put it only under supermarket ? one of the banners in [the website](real.hu) carousel mentions it's a super store.

I don't know this brand, so I'm not able to really decide that.
- supermarket is more for larger stores where you push a cart around.
- convenience is more for smaller stores where you carry a basket around.

If "Reál" operates both kinds of stores, it can be in both files.

**Comment by amous4822** [comment]
Should I mention Real only as a display name and use long names for brand and name in tags ?

**Comment by debyos** [comment]
Hi,
sorry for being so late. Reál works mostly with `convenience` stores, mostly in rural areas. Nevertheless, they do have also `supermarket` like shops so you can put them to both categories. Moreover, they work in a franchise system, so the name of the company varies for each store, i.e. the company name is of less interest.
Cheers

**Comment by amous4822** [comment]
created new PR #4588

**Pull request closed without merging**
