### PR TITLE
Add Gourmet City

### PR DESCRIPTION
**Pull request by sguinetti**
This pull request adds a subrand by Daiei.

### CODE REVIEW

**Comment by tas50** [comment]
@sguinetti Is there a twitter of facebook account you can link in the wikidata so we get that icons in iD?

**Comment by sguinetti** [comment]
Well, the SNS would be from Daiei.  There isn't other social network than that company. I just put the logo on Wikidata instead.

**Comment by Adamant36** [comment]
> I just put the logo on Wikidata instead.

How has your success with that been so far? It seems like all the logos I upload get deleted.

**Comment by sguinetti** [comment]
If a logo lacks artistic intent, such as plain text with basic shapes and straight lines are in the public domain. This is the requirement to upload content to Commons:
> In Japanese copyright law, a work is considered eligible for protection when it is "a production in which thoughts or sentiments are expressed in a creative way and which falls within the literary, scientific, artistic or musical domain." ([Wikipedia](https://en.wikipedia.org/wiki/Threshold_of_originality#Japan))

**Comment by ArenaL5** [comment]
Shouldn't the logo be for Gourmet City, even if the social network account is for all Daiei?

(On a separate note, could you double-check this PR? d962ce975ee7113f8a7f77bcf09954d41d3a5300 rewrites this with a different store, and the next commit rewrites it back to Gourmet City.)

**Comment by sguinetti** [comment]
Strange. I think that I will have wrongly merged the commits. I don't know if this is the only pull request with this problem. Should I update to the last commit to review if something weird happens?

**Comment by sguinetti** [comment]
I close this pull request. Now I rework in #3865.

**Comment by ArenaL5** [comment]
The other PRs looked fine to me. It was only a glitch this one.

#3865 is good, I'm merging it.

(I noticed the logo is the same, but I was asking why the text at https://www.wikidata.org/wiki/Q11300647#P154 reads "daiei" instead of "gourmet city"). Anyways, it's not that important, and I can merge it anyways.)

**Pull request closed without merging**
