### PR TITLE
Update Deutsche Post entries

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
Merge the two post_office entries, and add country codes and Wikipedia and Wikidata links to the remaining Deutsche Post entries.

---

Also, apparently I added the missing trailing newline to this file when I saved it in Emacs. Should I remove it?

### CODE REVIEW

**Comment by ENT8R** [comment]
You just need to add `"match": ["amenity/post_office|Deutsche Post Filiale"]` to the entry of the `Deutsche Post`

And I would also add
```
"brand:wikidata": "Q157645",
"brand:wikipedia": "en:Deutsche Post",
```
to the entry of the post box. But if you feel unsure about something, just tell me and I will do it for you 😄

> Also, apparently I added the missing trailing newline to this file when I saved it in Emacs. Should I remove it?

Don't mind about the newline...

**Comment by lucaswerkmeister** [comment]
Shouldn’t I alse remove the Filiale entry (and add its count to the main one)?

**Comment by ENT8R** [comment]
> and add its count to the main one

Please don't modify the count by hand, this won't work. But after you added `"match": ["amenity/post_office|Deutsche Post Filiale"]` to the entry of the `Deutsche Post` you should remove the entry, that is true.

**Comment by lucaswerkmeister** [comment]
Alright, new version pushed.

**Comment by ENT8R** [comment]
Thank you very much for your contribution 🎉 👍

**Comment by lucaswerkmeister** [comment]
Thanks for helping me out and merging it :heart:

**Pull request merged**
