### PR TITLE
Add Tags to Price chopper

### PR DESCRIPTION
**Pull request by mraguso2**
issue: https://github.com/osmlab/name-suggestion-index/issues/1734 
Add tags to Price Chopper

### CODE REVIEW

**Comment by maxerickson** [comment]
There's a second brand that should get the same OSM tags, https://en.wikipedia.org/wiki/Price_Chopper_(supermarket) .

**Comment by bhousel** [comment]
yeah this is a tricky one.. I'll check in more detail today.

**Comment by bhousel** [comment]
screenshot 2018-10-20 21 39 54

https://overpass-turbo.eu/s/CXF

The New York one:   https://en.wikipedia.org/wiki/Price_Chopper_Supermarkets
The Kansas City one:  https://en.wikipedia.org/wiki/Price_Chopper_(supermarket)

# 😑 

I don't really want to add polygons for different regions, but that might be the easiest way to support this.

**Comment by good-praxis** [comment]
This actually reminds me, we probably have a pretty similar issue with the `Netto` brands.
as of 6433488fd2cf91ce8ae45cbcc96b0466d7e96d35 this is how it is handled in the list:

```
  "shop/supermarket|Netto": {
    "count": 4209,
    "match": [
      "shop/supermarket|NETTO",
      "shop/supermarket|netto"
    ],
    "tags": {
      "brand": "Netto",
      "brand:wikidata": "Q552652",
      "brand:wikipedia": "en:Netto (store)",
      "name": "Netto",
      "shop": "supermarket"
    }
  },
  "shop/supermarket|Netto Marken-Discount": {
    "count": 794,
    "tags": {
      "brand": "Netto Marken-Discount",
      "brand:wikidata": "Q879858",
      "brand:wikipedia": "en:Netto Marken-Discount",
      "name": "Netto Marken-Discount",
      "shop": "supermarket"
    }
  }
```
A lot of the upper `Netto` ones (as in the count) will very very likely refer to `Netto Marken-Discount`, these brands are only really distinct by region, with regions only being filled with the first Netto (aka. "Netto Black", but more often just Netto) and other regions with the other Netto ("Netto South" or just Netto)

Just thought it may be topical.

**Comment by bhousel** [comment]
I added them both using the tilde character in the key like this:

```js
  "shop/supermarket|Price Chopper~(Kansas City)": {
    "countryCodes": ["us"],
    "nocount": true,
    "tags": {
      "brand": "Price Chopper",
      "brand:wikidata": "Q7242572",
      "brand:wikipedia": "en:Price Chopper (supermarket)",
      "name": "Price Chopper",
      "shop": "supermarket"
    }
  },
  "shop/supermarket|Price Chopper~(New York)": {
    "countryCodes": ["us"],
    "nocount": true,
    "tags": {
      "brand": "Price Chopper",
      "brand:wikidata": "Q7242574",
      "brand:wikipedia": "en:Price Chopper Supermarkets",
      "name": "Price Chopper",
      "shop": "supermarket"
    }
  },
```

**Pull request merged**
