### PR TITLE
add fuel stations in Ghana

### PR DESCRIPTION
**Pull request by sammyhawkrad**

### CODE REVIEW

**Comment by bhousel** [comment]
Hey @sammyhawkrad  - it's weird that this pull request is touching a lot of files aside from `data/brands/amenity/fuel.json` where the changes are.  Can you refresh your fork with the `main` branch so that this merges more cleanly?

(I know I've been changing a lot of stuff the past few days, trying to work through the issue and PR backlog)

**Comment by sammyhawkrad** [comment]
It's because I run `npm run build` after my changes. 

I had also synced my fork with the main and pulled the latest changes locally not realising there had been new commits to the main repo. 

I'm going to close this pull request and submit a new one.

**Comment by bhousel** [comment]
thanks @sammyhawkrad .. Its ok to skip the `npm run build` on your end ... I'm merging lots of stuff and I run it sometimes.

**Comment by sammyhawkrad** [comment]
Resubmitted as #9547

**Pull request closed without merging**
