### PR TITLE
Update sports.json

### PR DESCRIPTION
**Pull request by alessandrocarmeli**
sportler added

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Hi @alessandrocarmeli, and thanks for the PR - we tend not to include a web site within the Name Suggestion Index however, as this data is available via the Wikidata. I don't think "_strapline_" is something that is currently considered either, so I would suggest removing both of these values.

**Comment by bhousel** [comment]
I agree with @UKChris-osm , I merged and removed the `strapline` and `website` tags in 1cb5f6193 (we don't add these tags in the index).

**Comment by kjonosm** [comment]
@alessandrocarmeli, @bhousel  Could you double check the name value (Sportoler)? It looks very much like a typo...

**Comment by UKChris-osm** [comment]
Good spot @kjonosm

**Pull request merged**
