### PR TITLE
Edit Pony Cleaning, add Young Dry and Dia Cleaning

### PR DESCRIPTION
**Pull request by sguinetti**
This pull request update Pony Cleaning, a japense dry cleaning brand. With Wikidata and matchname. Also, added Young Dry (for Osaka area) and Dia Cleaning.

### CODE REVIEW

**Comment by Adamant36** [comment]
Hello. On this one brand:en seems to be Pony, but name:en is Pony Cleaning. Am I correct to assume that both are suppose to be Pony Cleaning?

**Comment by sguinetti** [comment]
Hello again. Pony is a trademark. In [some areas](https://www.e-tennoz.com/en/archives/cstm_shopguide/283), the english name is Pony and its logo is a horse with this text. "Cleaning" is for the shop name and clarifies that it is a place for cleaning.

**Comment by Adamant36** [comment]
How is it mostly tagged in OSM? Pony or Pony Cleaning?

**Comment by sguinetti** [comment]
OK. I changed this brand to Pony with official_name.

**Comment by Adamant36** [comment]
> OK. I changed this brand to Pony with official_name.

Thanks 👍

**Pull request merged**
