### PR TITLE
Moving Claire's from jewelry

### PR DESCRIPTION
**Pull request by SelfishSeahorse**
See also #2805

### CODE REVIEW

**Comment by SilentSpike** [comment]
Should this not be [`shop=accessories`](https://taginfo.openstreetmap.org/tags/?key=shop&value=accessories) (found [here](https://wiki.openstreetmap.org/wiki/Retail_chains_in_the_United_Kingdom#Accessories)). It has a higher usage, but the wiki page has been deleted 🤔

**Comment by SelfishSeahorse** [comment]
> Should this not be [`shop=accessories`](https://taginfo.openstreetmap.org/tags/?key=shop&value=accessories) (found [here](https://wiki.openstreetmap.org/wiki/Retail_chains_in_the_United_Kingdom#Accessories)). It has a higher usage, but the wiki page has been deleted 🤔

``shop=accessories`` has a higher usage, but it has been used for different accessories shops – not only fashion accessories –, e.g. home accessories or accessories for mobile phones, cars, motorcycles or computers. ``shop=fashion_accessories`` is unambiguous and has been approved.

**Comment by tas50** [comment]
This seems like the right place overall for Claires

**Comment by tas50** [comment]
That being said can you make a single PR that handles the move not a PR for each file?

**Comment by SilentSpike** [comment]
I think it's because the files were edited via github directly. We can just merge both PRs 👍

**Comment by tas50** [comment]
Yeah that’s obvious now that I look at the branch names.
Jet leg has me this week.

**Comment by SelfishSeahorse** [comment]
> That being said can you make a single PR that handles the move not a PR for each file?

I tried to make a single pull request, but i haven't found out how to do this on GitHub.

**Comment by tas50** [comment]
Thanks for bringing this up @SelfishSeahorse. I added the necessary match tag in b0cfd721b4477ee160613f9fe2ed5ddb575ceda7. That way when we run `npm run build` the script doesn't add back the jewelry store.

**Pull request merged**
