### PR TITLE
add Loco Burrito brand

### PR DESCRIPTION
**Pull request by Nydragon**
Loco Burrito is a mexican fast food brand in South Korea

### CODE REVIEW

**Comment by Nydragon** [comment]
Not sure how ids are generated so i entered a random alphanumeric string.

**Comment by phd0** [comment]
no, do not add ids : it is generated automatiquely by the script

**Comment by Cj-Malone** [comment]
Thank you. & yeah, ids are auto generated, however the next build will override yours so it's fine.

**Comment by Nydragon** [comment]
Alright, thank you!

**Pull request merged**
