### PR TITLE
Add Costa Drive Thru

### PR DESCRIPTION
**Pull request by peternewman**
See https://github.com/openstreetmap/iD/issues/8794

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @peternewman 👍 
It's missing a comma, but I'll just merge it and fix that..

**Comment by peternewman** [comment]
Was just in the process of fixing that... You should probably protect branches so they can only merge then they're passing CI!

I'm also going to add the unhyphenated "drive through" variant.

**Comment by bhousel** [comment]
> Was just in the process of fixing that... You should probably protect branches so they can only merge then they're passing CI!

Haha, I usually prefer to just merge small mistakes and fix them right away rather than holding up a PR until it passes CI. 

> I'm also going to add the unhyphenated "drive through" variant.

The matcher actually ignores variation in punctuation, so these extra match names are not needed 😄

**Comment by peternewman** [comment]
> Haha, I usually prefer to just merge small mistakes and fix them right away rather than holding up a PR until it passes CI.

Ah fair enough, I thought you'd always want to keep your main branch valid and clean, even if it meant you editing the PR yourself.

> The matcher actually ignores variation in punctuation, so these extra match names are not needed smile

Ah damn, I was wondering...

**Pull request merged**
