### PR TITLE
Add MedPlus (Pharmacy)

### PR DESCRIPTION
**Pull request by mds08011**
Adds MedPlus per Issue #2908

### CODE REVIEW

**Comment by matkoniecz** [comment]
> "dispensing": "yes",

Is it certainly applying to all locations?

**Comment by bhousel** [comment]
Thanks @mds08011  👍 
I made the name consistent and removed the `dispensing` tag in 1875a2cb5
We don't include this tag because most people don't use it.

**Comment by 1ec5** [comment]
Isn’t there a field for `dispensing` in iD?

**Comment by bhousel** [comment]
> Isn’t there a field for `dispensing` in iD?

Yes but I don't understand it.  We probably added it because someone asked us to.

I read these pages but I still don't understand what the field is for:
https://wiki.openstreetmap.org/wiki/Key:dispensing
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpharmacy

`dispensing=yes` seems like every pharmacist.  I'm not even sure `dispensing=no` is a real thing.
It even says "The default value is country specific."

Why even tag it then?  Who wants this data or can even make use of it?

**Comment by mds08011** [comment]
The talk page seems to indicate it's based on a very technical UK distinction: https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dpharmacy

**Comment by txtsd** [comment]
Fair enough. And thanks!

**Pull request merged**
