### PR TITLE
Remove discard filters

### PR DESCRIPTION
**Pull request by tohaklim**
I believe names from this index are flagged as generic - the ones removed are not, per se

### CODE REVIEW

**Comment by bhousel** [comment]
Could you explain more the intent behind this?
What are the names you are removing?

**Comment by tohaklim** [comment]
they are what I'd refer to as "semi generic", as in they are not brand names, yet should not be discouraged as are still valid names

**Comment by bhousel** [comment]
ok - can you instead move them up to the `discardKeys` section so that they don't creep back into the index?

**Comment by tohaklim** [comment]
oh, that's what I was missing. Moved them, hopefully the syntax is ok

**Comment by bhousel** [comment]
> oh, that's what I was missing. Moved them, hopefully the syntax is ok

Thanks!
If you `npm run build` and the unwanted entries don't return - the syntax is ok 😄

**Pull request merged**
