### PR TITLE
Add MMA Insurance

### PR DESCRIPTION
**Pull request by bmillemathias**

### CODE REVIEW

**Comment by Adamant36** [comment]
Seems to have conflicts you need to resolve?

**Comment by bmillemathias** [comment]
> 
> 
> Seems to have conflicts you need to resolve?

Yep, fixed

**Comment by Adamant36** [comment]
Thanks. What's with all the other odd changes? @matkoniecz can you look at this?

**Comment by matkoniecz** [comment]
Seems to be fixed now.

**Comment by Adamant36** [comment]
Hhhmm, weird. Must have been because I was going to "view changes." Guess I'll merge it. Thanks @bmillemathias.

**Pull request merged**
