### PR TITLE
Added missing wiki information in Vinmonopolet

### PR DESCRIPTION
**Pull request by stefannypanameno93**

### CODE REVIEW

**Comment by Identitaet** [comment]
sorry I already fixed both those things (probably cause I saw your pr and rembered to do it but forgot you)

**Comment by Identitaet** [comment]
Thanky you anyway

**Comment by bhousel** [comment]
Thanks @stefannypanameno93 - we can accept the PR so you get credit for hacktoberfest even though it didn't merge.

**Comment by Identitaet** [comment]
Oh yeah forgot that as well
Sorry

**Pull request closed without merging**
