### PR TITLE
Add Chicken Licken will address #4287

### PR DESCRIPTION
**Pull request by TheDynamicPunk**
I've added Chicken Licken which should address #4287

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Hi @TheDynamicPunk 

A minor edit is needed, as the Wikipedia for this entry is "_Chicken Licken (restaurant)_"

**Comment by TheDynamicPunk** [comment]
@UKChris-osm Thanks for reviewing I'll update it

**Comment by UKChris-osm** [comment]
Sorry @TheDynamicPunk, "_displayName_" was okay as it was, it was only the Wikipedia tag that needed changing :)

**Comment by TheDynamicPunk** [comment]
I'm sorry I misunderstood 😥
I'll update it

**Comment by UKChris-osm** [comment]
Thank you @TheDynamicPunk all done and all good 👍

**Pull request merged**
