### PR TITLE
Changed Landbank to LANDBANK

### LINKED ISSUE #4104: Revisiting the tagging schema for LANDBANK (Philippines)
Similar to #2706, Land Bank of the Philippines uses capitalized letters for LANDBANK. One example of this can be found in their [About Us](https://www.landbank.com/about-us/about-landbank) page. Based on what I've found, I'm suggesting that the naming schema for LANDBANK be changed to the following:

"amenity": "bank"
"brand": "LANDBANK"
"brand:wikidata": "Q6483872"
"brand:wikipedia": "en:Land Bank of the Philippines"
"name": "LANDBANK"

### PR DESCRIPTION
**Pull request by ShunshunL**
Closes #4104

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Hi @ShunshunL, you should only need to edit the one file "_brands/amenity/bank.json_"and the rest of the files will automatically be corrected when the various "_npm run *_" are actioned.

**Comment by ShunshunL** [comment]
Hi @UKChris-osm, thanks for letting me know about this. I did realize that after committing then reading through the guidelines. My most recent commit for this should only consist of one file change under folder brands/.

**Comment by UKChris-osm** [comment]
Thanks @ShunshunL, I won't commit this yet, as there is a question about the upper casing at the moment!

**Comment by bhousel** [comment]
Thanks @ShunshunL and welcome 👋 
I did some internet research (see #4104) and I think we should leave the name alone for now.  Sorry to close this!

**Pull request closed without merging**
