### PR TITLE
Add wiki tags for the German beverage store 'Edeka Getränkemarkt'

### LINKED ISSUE #1052: Research needed for: shop/beverages|Edeka Getränkemarkt
#### :thinking: We need help deciding what to do with "shop/beverages|Edeka Getränkemarkt"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/beverages|Edeka Getränkemarkt` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/beverages|Edeka Getränkemarkt`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/beverages|Edeka Getränkemarkt`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

### PR DESCRIPTION
**Pull request by ENT8R**
Fixes #1052
There are some unrelated changes, but this is just the removal of whitespaces by the build script or my editor 😄

### CODE REVIEW

**Comment by matkoniecz** [comment]
Is there chance that you can link their website/twitter account/FB account/official reports/some other confirmation? I need it for wikidata.org/wiki/Wikidata:Administrators%27_noticeboard#Please_undelete_this_entries_about_brands (entries are temporarily undeleted to give time for fixing them)

**Comment by bhousel** [comment]
@matkoniecz thank you for your work on getting these undeleted!  👏

**Comment by ENT8R** [comment]
Mmhh... This one is actually a little bit trickier:
- it is not an independent brand/store but it is a part of the German supermarket chain "Edeka"
- in some cities, the beverage stores of this chain are outsourced and located in another building next to the main store (probably due to lack of space in the main store)
- so it does not operate as a own company, it is only the beverage section of this store

So there is no website, twitter of facebook account for this store (I could not even find an official website) as it is a part of "Edeka"...

BTW: the exact same thing can be also found at the supermarket chain "Rewe" with their beverage store "Rewe Getränkemarkt":
https://github.com/osmlab/name-suggestion-index/blob/da32eb92df9c5f0d7d72bceffc1123f89a604420/brands/shop/beverages.json#L94-L106

**Comment by matkoniecz** [comment]
https://www.wikidata.org/wiki/Q57519344 seems to have a FB page that I added

**Comment by ENT8R** [comment]
No, this is only a facebook page of a local store located in the city of "Gedern". That's why the page name is "rewegedern"... I did a short research but I couldn't find any other official facebook, twitter or web page.

**Comment by matkoniecz** [comment]
In that case I removed it.

**Pull request merged**
