### PR TITLE
add Toby's Estate

### PR DESCRIPTION
**Pull request by AlertSubject**
closes https://github.com/osmlab/name-suggestion-index/issues/7838

### CODE REVIEW

**Comment by Cj-Malone** [comment]
LGTM, thanks.

**Comment by codeinabox** [comment]
Thank you for this. The location set however needs correcting as this brand only operates in Australia, Indonesia, Kuwait, Philippines and Singapore

**Comment by AlertSubject** [comment]
> Thank you for this. The location set however needs correcting as this brand only operates in Australia, Indonesia, Kuwait, Philippines and Singapore

Is it possible to edit this online or do o have to do it all in vs code again?
I have barely no experience and maybe there's an easier way I don't know yet

Also I thought I've seen Wales in the list of stores?

**Comment by Cj-Malone** [comment]
> Is it possible to edit this online or do o have to do it all in vs code again? I have barely no experience and maybe there's an easier way I don't know yet

Editing a single file via GitHub is really easy, go to the [file](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/cafe.json), hit the [pencil/edit button](https://github.com/osmlab/name-suggestion-index/edit/main/data/brands/amenity/cafe.json) on the right, edit what you want, commit it, open the pull request.

Let us know if you're having any issues.

> Also I thought I've seen Wales in the list of stores?

Maybe New South Wales?

**Comment by codeinabox** [comment]
For reference the store locations are here https://www.tobysestate.com.au/cafe-finder

**Pull request merged**
