### PR TITLE
Refine various 001 codes to regions or countries

### PR DESCRIPTION
**Pull request by chuqtas**

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
Have we got a reference book between ```locationSet``` code and country/regions? @bhousel 
~~(**Sorry**, but I don't know~~ ```150``` ~~means what, I guess it means EU? I only know~~ ```001```~~means global. )~~

**Comment by LaoshuBaby** [comment]
I think it is good because too large locationset may make people confuced when they are suggested with a not known brand when mapping.

And thank @chuqtas  for [your previous contributions to NSI](https://github.com/osmlab/name-suggestion-index/commits?author=chuqtas), especlliy in charging_station

I'm a newcomer at NSI community, This is my first review. If I have made some mistake, please criticize me!

**Comment by bhousel** [comment]
> Have we got a reference book between `locationSet` code and country/regions?

Yes!  check out https://ideditor.codes - anything listed there will work 👍

**Comment by LaoshuBaby** [comment]
♥




------------------&nbsp;Original&nbsp;------------------
From: "Bryan ***@***.***&gt;; 
Date: 2021年3月14日(星期天) 下午2:17
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: Re: [osmlab/name-suggestion-index] Refine various 001 codes to regions or countries (#4969)





  
Have we got a reference book between locationSet code and country/regions?
  
Yes!  check out https://ideditor.codes - anything listed there will work 👍

**Comment by UKChris-osm** [comment]
> I'm a newcomer at NSI community, This is my first review. If I have made some mistake, please criticize me!

Nobody intends on criticising you @LaoshuBaby, you're doing well!

**Pull request merged**
