### PR TITLE
Hanmibank

### PR DESCRIPTION
**Pull request by m-hue**
Bank with locations in CA, IL, NJ, NY, TX and VA.

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
I trying to find more exact states boundry in country coder but failed.

So I think this is exact enough.

**Comment by LaoshuBaby** [comment]
Thanks @m-hue for improving NSI continuosly!

**Comment by LaoshuBaby** [comment]
Can this locationSet suitable for using geojson to describe?

(Because just received the comment notice for #4784

**Comment by bhousel** [comment]
> Can this locationSet suitable for using geojson to describe?

We don't have state-level boundaries yet, but scoping it to [`us`](https://ideditor.codes/?code=us) (or even [`conus`](https://ideditor.codes/?code=conus)) is ok for now. 

Hanmibank might expand to more states, and it would be extra work for us to maintain a geojson of all the states where its branches are.

**Comment by LaoshuBaby** [comment]
> 
> 
> > Can this locationSet suitable for using geojson to describe?
> 
> We don't have state-level boundaries yet, but scoping it to [`us`](https://ideditor.codes/?code=us) (or even [`conus`](https://ideditor.codes/?code=conus)) is ok for now.
> 
> Hanmibank might expand to more states, and it would be extra work for us to maintain a geojson of all the states where its branches are.

So since there is currently no geojson file for continents, it seems that I have been worrying too much. Thank @bhousel  for your answer! 👍

**Comment by bhousel** [comment]
> So since there is currently no geojson file for continents, it seems that I have been worrying too much. Thank @bhousel for your answer! 👍

yes, for `locationSet` we can support:
- codes recognized by country-coder - https://ideditor.codes
- circle region defined as a point and radius
- custom .geojson file

(more info here: https://github.com/ideditor/location-conflation/blob/main/README.md )

It's somewhat expensive to download or bundle a lot of geojsons, and also extra work for us to maintain them, so I think of it as a fallback option.. They are very useful for sub-country regions like Crimea, or French-speaking Canada, or regions where transit companies operate, etc.  We also have a few situations in the US where there are separate regional brands using the same name ("Price Chopper", "Citizens Bank").

**Pull request merged**
