### PR TITLE
Add Selecta vending machines

### PR DESCRIPTION
**Pull request by coolultra1**
Selecta is a big vending machine company in all of Europe. I hope the Locationset is ok, they operate in those 16 countries and none more.

### CODE REVIEW

**Review by coolultra1 — COMMENTED** [review]
I hereby approve of this commit. The committer seems to be really handsome.

**Comment by UKChris-osm** [comment]
Hi @coolultra1 - I think the "_brand:wikipedia_" should be "_Selecta (company)_" in this instance.

**Comment by coolultra1** [comment]
@UKChris-osm Sorry, my bad, fixed now.

**Comment by bhousel** [comment]
thanks @coolultra1 👍

**Pull request merged**
