### PR TITLE
Added Chicken Cottage

### PR DESCRIPTION
**Pull request by PatrickMackridge**
Closes issue #4413

### CODE REVIEW

**Comment by Identitaet** [comment]
Are you sure you added Chicken cottage ?
GitHub says that this deletes everything

**Comment by Adamant36** [comment]
Two PRs ago it formated everything on different lines. I don't know why it would change things again.

**Comment by Identitaet** [comment]
Probably different versions of the script in the forked repos

**Comment by bhousel** [comment]
Yeah my guess is that sometimes people's code editor might apply formatting to the files that is different than the formatting that `npm run build` tries to put things into.  

The cleanest diffs will always be when someone edits their files and then runs `npm run build`, but I know most of the time people aren't doing that, and that's ok.

**Comment by bhousel** [comment]
The Chicken Cottage part of it seems fine, so I'm just gonna squash-merge it.
Thanks @PatrickMackridge & welcome 👋

**Comment by PatrickMackridge** [comment]
Hi all, yeah I think the formatting was something to do with when I ran `npm run build`. When I resolved the merge conflicts, I think I may have ran the new script as the formatting seems to be ok now? I'm not 100% sure, but merge conflicts should be fixed now. Thanks!

**Comment by bhousel** [comment]
> Hi all, yeah I think the formatting was something to do with when I ran `npm run build`. When I resolved the merge conflicts, I think I may have ran the new script as the formatting seems to be ok now? I'm not 100% sure, but merge conflicts should be fixed now. Thanks!

No problem, it can be hard to keep your fork updated when a repo moves as fast as this one does 😆 

It looks like you tried merging in the upstream commits with other stuff onto your `addChickenCottage` branch, and then manually resolved all the merge conflicts.  This is extra work!

A better way to accomplish the same thing is to sync the upstream main branch and then **rebase** your `addChickenCottage` branch.  This is a fancy way of telling git to "take the commits from my `addChickenCottage` branch and rewrite them so that they come at the end of the `main` commits".  

Either way, the squash-merge was able to figure out that all the commits on the `addChickenCottage` branch were just doing the same work that had already played out on `main`.  You can see that  ee5a283 ended up really clean.

Git is weird but cool.

**Comment by PatrickMackridge** [comment]
> A better way to accomplish the same thing is to sync the upstream main branch and then **rebase** your `addChickenCottage` branch. This is a fancy way of telling git to "take the commits from my `addChickenCottage` branch and rewrite them so that they come at the end of the `main` commits".

Good advice thanks, I'll try and remember this for next time I have this sort of issue 😆

**Pull request merged**
