### PR TITLE
Remove Fairwood (CN)

### PR DESCRIPTION
**Pull request by tommylung**
Remove
- Fairwood

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
Thank you very much! However, I rarely heard of this brand in the mainland (this is indeed the first time I heard about it, and I didn't notice it in the database before), I checked it and there are basically few stores in the mainland, which may not meet the inclusion standards. (At least 10 or potentially more than 10), so I suggest that it is better to simply remove the mainland version and only write the Hong Kong and Macau version!
非常感谢！不过内地很少听说有这个品牌(这确实是我第一次听说，之前也没注意到数据库里有它)，查了一下它内地基本没有几家店，可能是达不到收录标准的(至少10个或潜在可能超过10个)，因此我是建议不如干脆把内地版本的移除，只写港澳版本就可以了！

**Comment by tommylung** [comment]
> Thank you very much! However, I rarely heard of this brand in the mainland (this is indeed the first time I heard about it, and I didn't notice it in the database before), I checked it and there are basically few stores in the mainland, which may not meet the inclusion standards. (At least 10 or potentially more than 10), so I suggest that it is better to simply remove the mainland version and only write the Hong Kong and Macau version! 非常感谢！不过内地很少听说有这个品牌(这确实是我第一次听说，之前也没注意到数据库里有它)，查了一下它内地基本没有几家店，可能是达不到收录标准的(至少10个或潜在可能超过10个)，因此我是建议不如干脆把内地版本的移除，只写港澳版本就可以了！

Thanks for your suggestion. We can remove it.
謝謝你的建議，我們可以把它刪除。

**Comment by LaoshuBaby** [comment]
> Thanks for your suggestion. We can remove it.
> 謝謝你的建議，我們可以把它刪除。

Besides, I guess this brand Fairwood is a restautant not a fast_food

The definition of them can bee seen in https://github.com/osmlab/name-suggestion-index/pull/4987 (Sorry for those part of Chinese, it is written by me when I'm not a maintainer)

I think this case maybe similar to "Hehegu" restaurant, although it said itself is a "fast food".

https://github.com/osmlab/name-suggestion-index/blob/a45aa6d3fb6155851027db27acae1c7d4c6f1e1c/data/brands/amenity/restaurant.json#L5524-L5538

**Comment by tommylung** [comment]
@LaoshuBaby  Thanks for your reply.

Fairwood and Café de Carol are the Chain fast food restaurants. They all belong to ["Hong Kong style fast food restaurants"](https://zh.wikipedia.org/wiki/港式快餐).

**Pull request merged**
