### PR TITLE
Add shop/deli to food in matchGroups.json

### PR DESCRIPTION
**Pull request by andrewpmk**
Should resolve issue with Subway being mistagged as deli in #9087. Please close that pull request.

### CODE REVIEW

**Comment by andrewpmk** [comment]
Tests failing, why?
```
 # Subtest: match alternate tagpairs in matchTags
        not ok 7 - match alternate tagpairs in matchTags
          ---
          duration_ms: 1.779887
          location: 'file:///home/runner/work/name-suggestion-index/name-suggestion-index/tests/matcher.test.js:212:13'
          failureType: 'testCodeFailure'
          error: |-
            Expected values to be strictly equal:
            + actual - expected
            
            + 'amenity/fast_food'
            - 'shop/deli'
          code: 'ERR_ASSERTION'
          name: 'AssertionError'
          expected: 'shop/deli'
          actual: 'amenity/fast_food'
          operator: 'strictEqual'
          stack: |-
            TestContext.<anonymous> (file:///home/runner/work/name-suggestion-index/name-suggestion-index/tests/matcher.test.js:218:14)
            Test.runInAsyncScope (node:async_hooks:206:9)
            Test.run (node:internal/test_runner/test:631:25)
            Test.start (node:internal/test_runner/test:542:17)
            TestContext.test (node:internal/test_runner/test:167:20)
            TestContext.<anonymous> (file:///home/runner/work/name-suggestion-index/name-suggestion-index/tests/matcher.test.js:212:13)
            async Test.run (node:internal/test_runner/test:632:9)
            async TestContext.<anonymous> (file:///home/runner/work/name-suggestion-index/name-suggestion-index/tests/matcher.test.js:154:3)
            async Test.run (node:internal/test_runner/test:632:9)
            async Test.processPendingSubtests (node:internal/test_runner/test:374:7)
          ...
```

**Comment by andrewpmk** [comment]
Removed the offending test

**Comment by andrewpmk** [comment]
shop/deli can be removed from Honey Baked Ham now

**Review by LaoshuBaby — APPROVED** [review]
Personally, I very much agree with adding shop/deli to matchGroups, but I think this test case should not be removed directly. Instead, we should consider providing a new one that is applicable in this scenarios.

**Comment by bhousel** [comment]
Yeah I'd also perfer to see:
* shop/deli added to matchGroups and also
* that test rewritten to test matchTags with a different weird tag

**Comment by andrewpmk** [comment]
OK I changed the Honey Baked Ham test to use shop/butcher now it works.

Also removed the shop/deli matchNames from Honey Baked Ham because we don't need it anymore.

**Review by AntiCompositeNumber — APPROVED** [review]

**Pull request merged**
