### PR TITLE
attempt to handle convenience shops named abc [ready, waiting for review]

### PR DESCRIPTION
**Pull request by matkoniecz**
closes #2087

--

this one is a bit tricky so I am submitting it as a PR

### CODE REVIEW

**Comment by good-praxis** [comment]
There is also a lot of them in hungary, apparently? https://overpass-turbo.eu/s/Drg
Is this the same brand as the one in poland or is this yet another one?

**Comment by good-praxis** [comment]
How does this reflect the generic hungarian ABC? It will basically ignore it because of country codes, right?

**Comment by ImreSamu** [comment]
> How does this reflect the generic hungarian ABC? 

 it looks fine to me.  :)

**Comment by good-praxis** [comment]
I will go ahead and merge it then, because it seems factually accurate -- however, please keep in mind that a lot of the polish `abc` are incorrectly named `ABC`, as you can see on [overpass](https://overpass-turbo.eu/s/Dri)

**Comment by ImreSamu** [comment]
just a comment:

in extreme cases 
-  some native Hungarian osm contributor in Poland,  adding this - instead of a normal `shop=convenience`  -  **so a brand logo would be helpful.**   

but this is a really extremes cases.

now the hungarian "terms"  - including the "ABC" 
*  "terms": "ABC, sarki élelmiszer, kisbolt, közért"

see https://github.com/openstreetmap/iD/blob/master/dist/locales/hu.json#L5400
```json
                "shop/convenience": {
                    "name": "Kis élelmiszerbolt",
                    "terms": "ABC, sarki élelmiszer, kisbolt, közért"
                },
```

Probaly somebody need to write a simple script - to check the "brand" names in the Terms,

**Pull request merged**
