### PR TITLE
Added Coeur de Blé to fast_food.json

### PR DESCRIPTION
**Pull request by staceycng**
Referencing open issue #3741.

### CODE REVIEW

**Comment by staceycng** [comment]
Hi @bhousel!

Thanks for the feedback! I was unable to locate either an English or French wiki reference to Coeur de Blé, so created one myself. Let me know what else I can change. Thanks!

**Comment by UKChris-osm** [comment]
Hi @staceycng,

Does the Wikipedia article you referenced, "_en:Coeur de Blé_", actually exist, as I couldn't get anything to load up when searching for it?

Also, does "_Coeur de Blé_" have any form of social media presence?

**Comment by bhousel** [comment]
Thanks @staceycng and welcome! 👋 

In 80ada06c I removed the nonexistent Cœur de Blé wikipedia link and reran the build script.

If you do find some social media links or any other details about this brand, please add them to the [Cœur de Blé wikidata page](https://www.wikidata.org/wiki/Q95745666). At only 12 locations it's really a bit thin on notability, but more detail there will help prevent your page from being removed by admins.

**Comment by staceycng** [comment]
Hi @bhousel,

Noted and will do--thanks!

**Pull request merged**
