### PR TITLE
Add nomatch tags to get rid of the warnings for Fresh and Casino

### PR DESCRIPTION
**Pull request by quazihasan**
Got rid of two duplicates warning for Fresh and Casino. This is my first commit. If it goes well, I'm going to resolve more. This change set takes care of two out of 26. 24 more warnings to go!

### CODE REVIEW

**Comment by bhousel** [comment]
Do you know what the brands are?  If we're not sure about them, we don't want to just eliminate the warnings.

**Comment by bmillemathias** [comment]
Casino is a brand that owns different types of shops from supermarket to convenience stores, supermarket have often a fuel station aside.

**Comment by Adamant36** [comment]
https://en.wikipedia.org/wiki/Groupe_Casino

**Comment by quazihasan** [comment]
Should I also need to add the brand tag in there for them with wikidata and wikipedia info? For Fresh, it is already there for one of the file.

**Comment by doublah** [comment]
I wouldn't use the Groupe Casino wiki page for brand tags, as it refers to the general company that owns the Casino supermarkets brand (and multiple other brands). Maybe create a new wikidata page for the brand.

**Comment by bhousel** [comment]
closing as stale, sorry we couldn't get this merged!

**Pull request closed without merging**
