### PR TITLE
Add 1 fast_food

### PR DESCRIPTION
**Pull request by LaoshuBaby**
## Add:
   + 正新鸡排

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
## WARN：

When ```npm run build```  it show me this warning

```
⚠️   Warning - Unusual OpenStreetMap tag:
----------------------------------------------------------------------
  To resolve these, make sure the OpenStreetMap tag is correct.
----------------------------------------------------------------------
  "正新鸡排 (zhengxinchickensteak-65b4e8)" -> unusual tag? -> "cuisine = chicken steak"
total 1
```

**Comment by LaoshuBaby** [comment]
> 
> ## WARN：
> 
> When `npm run build` it show me this warning
> 
> ```
> ⚠️   Warning - Unusual OpenStreetMap tag:
> ----------------------------------------------------------------------
>   To resolve these, make sure the OpenStreetMap tag is correct.
> ----------------------------------------------------------------------
>   "正新鸡排 (zhengxinchickensteak-65b4e8)" -> unusual tag? -> "cuisine = chicken steak"
> total 1
> ```

But! **The only cuisine of this chain brand is chicken steak!**

So this time, **I will ingore this warning!**

If it is mistake, please just fix it and tell me! Thanks!

**Comment by bhousel** [comment]
> But! **The only cuisine of this chain brand is chicken steak!**
> 
> So this time, **I will ingore this warning!**

Should it be maybe `chicken;steak` (two cuisines with semicolon delimiter?)

**Comment by LaoshuBaby** [comment]
> 
> 
> > But! **The only cuisine of this chain brand is chicken steak!**
> > So this time, **I will ingore this warning!**
> 
> Should it be maybe `chicken;steak` (two cuisines with semicolon delimiter?)

No, that means 2 different cuisine, one is ```炸鸡```, and another is ```牛排```……

but it is truly only one cuisine, named ```鸡排```

[Here is the wikipedia about this taiwan snacks.](https://zh.wikipedia.org/wiki/%E9%A6%99%E9%9B%9E%E6%8E%92)

----------

**But I truly made a mistake! I should use this to describe！**   ```chicken_steak``` **! I'm so careless!**

**Comment by kjonosm** [comment]
Checking your wiki link, `cuisine=chicken` should be the correct tag for defining this item as a chicken restaurant.

**Comment by bhousel** [comment]
> No, that means 2 different cuisine, one is `炸鸡`, and another is `牛排`……
> but it is truly only one cuisine, named `鸡排`
> 
> [Here is the wikipedia about this taiwan snacks.](https://zh.wikipedia.org/wiki/%E9%A6%99%E9%9B%9E%E6%8E%92)

Wow this is fascinating to me. I think it's ok to use whatever `cuisine` value you want for this.  The OSM wiki is not a good source here.

You can search taginfo for one that's used already, but we definitely have a bunch of entries in the name-suggestion-index for Asian cuisines that aren't well documented on OSM's wiki (`beef_bowl`, `udon`, `curry`, `ramen`, `friture`, `soba`, and my favorite, `takoyaki`).

https://taginfo.openstreetmap.org/keys/cuisine#values

**Pull request merged**
