### PR TITLE
More brands

### PR DESCRIPTION
**Pull request by kreed**
Few more brands I ran into. I got a little proactive in renaming Schlotzsky's, but per the discussion in #2236 I think that's the direction we're going with?

### CODE REVIEW

**Comment by matthijsmelissen** [comment]
Thanks! Could you specify in the PR description which issues this fixes, like here: https://github.com/osmlab/name-suggestion-index/pull/2255 ?

**Comment by SilentSpike** [comment]
All look good to me (the rename of Schlotzsky's included) 👍

`countryCodes` data is always nice too (as these appear to be mostly US brands), but not as important

**Comment by kreed** [comment]
That's a good point. I'll add those in.

**Comment by kreed** [comment]
@Adamant36 I made those changes for Safelite and Extra Space Storage. I'm not sure about La-Z-Boy. It looks like they operate outside North America (e.g. their [UK division](https://www.la-z-boy.co.uk/)), but I'm not sure they have stores elsewhere. Even if they don't now, it seems likely that they could in the future. I'm going omit the country code to be safe.

**Comment by Adamant36** [comment]
That's fine. I wasn't to sure about it anyway. Thanks for adding the other stuff.

**Comment by matthijsmelissen** [comment]
These seem to be smaller brands. For example Havertys only has 19 instances in OSM.

@bhousel Would we like to add these?

**Comment by SilentSpike** [comment]
@matthijsmelissen We encourage adding brands which don't have enough entries (50) to be automatically picked up yet.

However, you raise a related interesting question, should we include brands which have less than 50 locations in reality?

**Pull request merged**
