### PR TITLE
Add Kagi110-Key Ambulancy Association

### PR DESCRIPTION
**Pull request by sguinetti**
This company operates two locksmith shop brands. Two brands share the same logo, SNS and  website. Store names differ only by name.

### CODE REVIEW

**Comment by Adamant36** [comment]
> This company operates two locksmith shop brands. Two brands share the same logo, SNS and website. Store names differ only by name.

uummmm, I sorta feel like they could have two different Wikidata entries then, but then I think Wikidata might have an issue with putting the same SNS and website on two separate pages. Although, people in OSM should be able to find what brand name they want by searching for a unique Wikidata code. So, I don't know 🤷

**Comment by matkoniecz** [comment]
Seems OK to me.

**Comment by ArenaL5** [comment]
This is very weird. The Wikidata entry is titled “Kagi110-Key Ambulancy Association”, and it seems like one name always goes after another in the website.

Am I right in thinking these used to be different brands, they're now managed as a single brand but didn't bother to unify the name? If that's the case, creating separate entries wouldn't help tag this business. I'd merge it as it is.

**Comment by sguinetti** [comment]
> Am I right in thinking these used to be different brands, they're now managed as a single brand but didn't bother to unify the name? 

Yes. The company merged into one but the brands did not.

**Pull request merged**
