### PR TITLE
add Extrafarma and more information to Drogasil

### PR DESCRIPTION
**Pull request by willemarcel**
All Drogasil shops are wheelchair=yes

### CODE REVIEW

**Comment by matkoniecz** [comment]
> All Drogasil shops are wheelchair=yes

Are we 100% sure that all opened in future also will be?

I am really dubious whatever this assumption is a good idea.

**Comment by willemarcel** [comment]
@matkoniecz The company has this as a principle and only allow to open shops in buildings with wheelchair accessibility.

**Comment by matkoniecz** [comment]
It is still a bit dubious for me to add it as default for all new objects. What if in some place they made a mistake? Or management changes?

@bhousel What you think about adding `wheelchair=yes` via name suggestions?

**Comment by bhousel** [comment]
> @bhousel What you think about adding `wheelchair=yes` via name suggestions?

That is a pretty awesome policy for the company's management to follow... 
I'm ok with it, if it really is their thing.

**Comment by bhousel** [comment]
Also I added `"nocount": true` for Extrafarma, because they don't appear that way in the most recent planet that we checked.  (The record would be in `allNames.json` if so)

**Pull request merged**
