### PR TITLE
deletion of elements that aren't brands 

### PR DESCRIPTION
**Pull request by Olyon**

### CODE REVIEW

**Comment by tas50** [comment]
@Olyon these will just come back when the file is generated again unless you add to the filters to mark them as not being brands

**Comment by Olyon** [comment]
I made the additions in filter_brands.json so it doesn't come back if I understood correctly.
but I am not added "Accor" which only appears 3 times as a name in the world. But appears a lot in brand=* but it is not a brand, it's the owner of the brand...

**Comment by tas50** [comment]
Thanks @Olyon

**Comment by tas50** [comment]
@Olyon I can "npm run build" which regenerated the names we keep and Accor has come back, but the others are good.

**Pull request merged**
