### PR TITLE
Tesco Lotus to Lotus's

### PR DESCRIPTION
**Pull request by MASangys**
Lotus's rebranding in Malaysia and Thailand by end of the year.
https://asia.nikkei.com/Business/Retail/Tesco-disappears-from-Southeast-Asia-as-CP-renames-outlets

### CODE REVIEW

**Comment by bhousel** [comment]
If this is a brand in transition, I think we should preserve the current/old with a tag `alt_name=Tesco Lotus`.  This will let NSI continue to match on current name, and also will let users find the features in geocoders like Nomanitum that index `alt_name`.

**Comment by MASangys** [comment]
Can, therefore you may add Tesco Lotus for alt name
but this alt name only applicable to Thailand branch, Malaysia's branches are priginally named Tesco before rebranding tho.

**Review by LaoshuBaby — CHANGES_REQUESTED** [review]
If one name only apply to a special conutry/region, you'd better seperate it into 2 different item.

**Comment by MASangys** [comment]
> If one name only apply to a special conutry/region, you'd better seperate it into 2 different item.

But after rebranding, only 1 item left for both countries.

**Comment by MASangys** [comment]
Hello, any respond?

**Comment by bhousel** [comment]
Thanks @MASangys, this is ok 👍

**Pull request merged**
