### PR TITLE
Remove name from Toby Carvery

### PR DESCRIPTION
**Pull request by Cj-Malone**
They can have unique names

### CODE REVIEW

**Review by LaoshuBaby — COMMENTED** [review]
What about add a `"preserveTags": ["^name"],` after locationSet?

**Comment by Cj-Malone** [comment]
Urm, I didn't know about `preserveTags` until right now, so some questions.

Is that necessary when NSI doesn't have a `name` tag? Presumably the name tag isn't changing so it wouldn't need to be preserved.

Does this actually make it more confusing when a POI changes? Say something `name=x` is replaced by Toby Carvery with a name `y`. Once you've selected Toby Carvery in iD would that keep the `name=x`?

**Comment by bhousel** [comment]
Sorry @Cj-Malone , our docs on this are not great and I'd like to improve them.
The most comprehensive guidance for how this project treats the `name` tag is here: 
https://github.com/osmlab/name-suggestion-index/pull/6071#issuecomment-1015756763

It does sound like this brand falls into the middle category, where it's reasonable to set the `name` to "Toby Carvery" if it doesn't already have a value but we should leave the `name` tag alone if it does already have a value... 
This is what the `"preserveTags": ["^name"]` property does.

**Comment by Cj-Malone** [comment]
OK, yeah. Sounds like the second. The vast majority are "Toby Carvery", with the website referring to them as "Toby Carvery {location}". There are a few like "Halfway House", "The Artichoke" and "White Hart" where they have unique names, but they'll still be covered in "Toby Carvery" signs. Potentially they should just be `loc_name` anyway, in which case this PR can be closed, but I've updated it in case.

**Pull request merged**
