### PR TITLE
Update Malaysia

### PR DESCRIPTION
**Pull request by MASangys**

### CODE REVIEW

**Comment by Adamant36** [comment]
Hello. What exactly were you trying to do here? Whats being updated?

**Comment by MASangys** [comment]
I had added some bank in Malaysia and enhancement of tagging name

**Comment by Adamant36** [comment]
Hhmmm, it seems it changed the whole bank file for some reason. I can't even get the file to load so I can see what bank you added or if anything might have accidentally been changed somewhere.

**Comment by Adamant36** [comment]
You want to just give me the details of the bank? Then I'll do a PR for it without all the other changes.

**Comment by matkoniecz** [comment]
It should be fixable by running `npm run build`

@MASangys - please, run `npm run build` (what should be always done before making a PR anyway).

**Comment by MASangys** [comment]
Noworries, I had reopen a new PR for this

**Pull request closed without merging**
