### PR TITLE
McDonald's in France have unique names

### PR DESCRIPTION
**Pull request by gileri**
In France (at least), McDonald's restaurants have unique/quasi-unique, public-facing names. They can be visible [here](https://www.restaurants.mcdonalds.fr/).

This PR creates a France-specific item that uses the french wikipedia article, does not suggest an incomplete name, while keeping  the other NSI goodies.

### CODE REVIEW

**Comment by arch0345** [comment]
Thanks @gileri and welcome! Would you be able to screenshot an example? I'm not able to access mcdonalds.fr for some reason.

**Comment by LaoshuBaby** [comment]
Welcome to NSI, but I have some questions about this.

1. I was also blocked by the website, is this website only can be browsed by a french IP? If so, a screenshot is needed.
图片

2. You can use `preserveTags` to aviod the changing of `name`, and If you want to create a new entry only apply to France, you'd better let the global one (Which include 001) exclude `fr`

**Comment by gileri** [comment]
Thank you both for the warm welcome !

> Would you be able to screenshot an example? I'm not able to access mcdonalds.fr for some reason.

You can have two even :
Restaurant name on website 1
Restaurant name on website 2

>You can use preserveTags to aviod the changing of name
I was going to do that, but to my understanding that would still suggest incomplete names on restaurants that do not currently have a name in OSM.

>If you want to create a new entry only apply to France, you'd better let the global one (Which include 001) exclude fr

You're totally right, thanks ! I assumed for some reason that this entry would override the original in France, but of course it won't... Pushed in d94da900e.

**Comment by arch0345** [comment]
Looks good 👍

**Pull request merged**
