### PR TITLE
Add V-Markt supermarket brand

### PR DESCRIPTION
**Pull request by kirandash**
Added V-Market supermarket brand to Germany to address issue #3576

### CODE REVIEW

**Comment by UKChris-osm** [comment]
The Wikidata in this PR seem to link to a generic page for "v-markt" (Wikipedia disambiguation page) and the Wikipedia links to a non-existent article, as opposed to the actual brand pages, was that intentional?

**Comment by kirandash** [comment]
@UKChris-osm I have now fixed the wikipedia brand detail as "de:Georg_Jos._Kaes". And I have used the wikidata mentioned in #3576. I hope that's ok.

**Comment by UKChris-osm** [comment]
Hi @kirandash 

Is "V-MARKT" a supermarket brand, that appears on the supermarkets, and is "Georg_Jos._Kaes" the parent company that owns / runs the "V-MARKT" chain?

The Wikidata linked in this PR seems to have been automatically generated but doesn't have any meaningful data attach to it, whereas [Q1504903](https://www.wikidata.org/wiki/Q1504903), seems to be a bit of a mix between the V-MARKT brand and Georg_Jos._Kaes.

Also, does the brand name have an "e" in it? In the PR is lists the brand & name as "V-MARK**E**T" with an "**E**", but the brand itself seems to not use the letter "**E**" in it, and is "V-MARKT"

**Comment by kirandash** [comment]
Hi @UKChris-osm 
As per issue #3576 and the wikipedia page, V-MARKT is a supermarket brand. As per [wikipedia page](https://de.wikipedia.org/wiki/Georg_Jos._Kaes) "Georg_Jos._Kaes" seems to be another name for it.

I had added the wikidata: Q2505135 as mentioned in #3576. Now I have changed it to [Q1504903](https://www.wikidata.org/wiki/Q1504903). That seems to have more information.

Regarding the extra "E" in "V-MARKET", that was a mistake as I copied the name from english translated page. Which I have now corrected to "V-MARKT".

Hope that fixes all the issue.

**Comment by bhousel** [comment]
Thanks @kirandash - I did some cleanups in bbdcd9b4
* we need to replace underscores with spaces in the `brand:wikipedia` tag
* I removed the redundant match names and match tags
* I removed the extra `official_name`, it's the same as `name` so probably unnecessary

**Comment by carstenhag** [comment]
Thanks a lot for fixing the data issues and doing this PR :).

**Pull request merged**
