### PR TITLE
Update and rename hifi.json to herbalist.json

### PR DESCRIPTION
**Pull request by MASangys**
I would luke to create a new page for herbalist, cuz no page currently. https://en.wikipedia.org/wiki/Eu_Yan_Sang

### CODE REVIEW

**Comment by bhousel** [comment]
Hey @MASangys can you redo this one?   It looks like the `hifi.json` file got deleted, and there are some JSON syntax issues.

If you haven't already done it, I definitely recommend cloning the project locally to your computer if you are going to be editing a bunch of files.  It's really much easier!   

Some guidance here:  https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by MASangys** [comment]
Yes, but can you create a new file for herbalists?

**Comment by bhousel** [comment]
> Because I need to learn, and it takes time. And then I cannot create a file on NSI Index also, so how can I adding a new entry here?

When the project is cloned locally, you can edit the files on your computer to get them however you want them to look, then `git add` and `git commit` once they are ready.  New files will be added if there are any.

**Comment by MASangys** [comment]
Sorry but I only managed to create a clone file here
https://github.com/MASangys/name-suggestion-index/commit/eb0317adab626ebd2e038df5e220ea1f6709cdb0

**Comment by MASangys** [comment]
Can you help me to merge it, I am still learning and as of now I cannot find the git add and git commit button

**Comment by bhousel** [comment]
> Can you help me to merge it, I am still learning and as of now I cannot find the git add and git commit button

Sure I will close and take care of it.. Best thing I can suggest is for you to follow the steps in the link that I sent above:
https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

**Pull request closed without merging**
