### PR TITLE
Editing Central Banks Brand name and adding wikidata

### PR DESCRIPTION
**Pull request by KarenDouglas**
I updated the Central Bank info (data/brands/amenity/bank.json) file.

Since it didn't have a Wikipedia page, I created a new item in Wikidata. I used its official website, Youtube channel, and Linkedin as identifiers.
Note that its display name is Central Bank but its brand is Central Bancompany according to its website: 

- https://www.centralbank.net/
- https://www.youtube.com/user/CentralBankMO
- https://www.linkedin.com/company/central-bancompany/

### CODE REVIEW

**Comment by arch0345** [comment]
Thanks @KarenDouglas and welcome! Please note in the future that the name/brand is used for what the company brands themselves as/how they're signed on the ground. It looks like they brand themselves as 'Central Bank' so I'll change the brand/name for this entry:
image

**Comment by KarenDouglas** [comment]
Thanks for the feedback and thorough explanation. I misunderstood brands. I will also look into location sets as you suggested! 
Thanks for having me!

**Comment by arch0345** [comment]
One more thing: make sure to leave out the full URL for identifiers when creating a Wikidata item (for example `central-bancompany` instead of `https://www.linkedin.com/company/central-bancompany/` for the LinkedIn Company ID) and use the `reference url` property instead of `official website` for references.

**Comment by KarenDouglas** [comment]
Will do! Thanks.

**Pull request merged**
