### PR TITLE
Add Folder brand

### PR DESCRIPTION
**Pull request by Crashillo**
Spanish stationery company https://folder.es/

### CODE REVIEW

**Comment by arch0345** [comment]
Looks good @Crashillo! Just note that without a `brand:wikidata` tag this won't get generated as an iD preset. You can easily create a wikidata page for this: just make sure to include statements (instance of, country, official website, etc.). I also recommend including their Facebook/Twitter on the page as NSI collects logos through their profile photos.

**Comment by LaoshuBaby** [comment]
> create a wikidata page for this

https://github.com/osmlab/name-suggestion-index/commit/f00db18e55d22a7cfacf4c2c79c8b1489feca9f5#diff-30bd66984d505b0abccc666090d8c90d1c2964aec4a79011bd28b246b4559f63

added

**Comment by Crashillo** [comment]
> > create a wikidata page for this
> 
> [f00db18#diff-30bd66984d505b0abccc666090d8c90d1c2964aec4a79011bd28b246b4559f63](https://github.com/osmlab/name-suggestion-index/commit/f00db18e55d22a7cfacf4c2c79c8b1489feca9f5#diff-30bd66984d505b0abccc666090d8c90d1c2964aec4a79011bd28b246b4559f63)
> 
> added

Heeey, I was doing it as well, but I didn't yet publish it. I'll update the fields using that ID

**Comment by LaoshuBaby** [comment]
> > > create a wikidata page for this
> > 
> > 
> > [f00db18#diff-30bd66984d505b0abccc666090d8c90d1c2964aec4a79011bd28b246b4559f63](https://github.com/osmlab/name-suggestion-index/commit/f00db18e55d22a7cfacf4c2c79c8b1489feca9f5#diff-30bd66984d505b0abccc666090d8c90d1c2964aec4a79011bd28b246b4559f63)
> > added
> 
> Heeey, I was doing it as well, but I didn't yet publish it. I'll update the fields using your ID

just publish，dont worry，wikidata can be merged

**Pull request merged**
