### PR TITLE
Added Westfalenbahn to Transit

### PR DESCRIPTION
**Pull request by shubh710**
Related to Issue https://github.com/osmlab/name-suggestion-index/issues/4403

### CODE REVIEW

**Comment by Identitaet** [comment]
Almost perfect but the operator tag should only be Abelio cause what's in the brackets is disambiguation for Wikipedia

**Comment by Adamant36** [comment]
> Almost perfect but the operator tag should only be Abelio cause what's in the brackets is disambiguation for Wikipedia

Plus there shouldn't be an underscore for the operator name or the Wikipedia title.

**Comment by shubh710** [comment]
Hi @Identitaet @Adamant36 
my bad, since I can see you have merged previous request do you want me to resolve mentioned issues and submit another PR?

**Comment by shubh710** [comment]
I can see you have rectified issues yourself. :)
Thanks.

**Pull request merged**
