### PR TITLE
Update CategoryRow.jsx

### PR DESCRIPTION
**Pull request by kjonosm**
Update search option from wikidata to wikipedia as NSI doesn't support wikipedia tags anymore.

### CODE REVIEW

**Comment by UKChris-osm** [comment]
@kjonosm I've switched over the [nsi.guide](https://nsi.guide) web site to your branch temporarily, can you have a look and see if you're satisfied with this update?

**Comment by kjonosm** [comment]
works for me 👍

**Comment by bhousel** [comment]
> @bhousel would you be happy to have the Wikipedia Search link replaced with a Wikidata Search?

I'm not sure.. The reason I added these is mostly for people to research brands which aren't already matched to anything.

This is very unscientific, but I just tried searching for a really generic sounding brand name, and I feel like the wikipedia search returned better results:

Screen Shot 2022-10-30 at 2 31 01 PM

Screen Shot 2022-10-30 at 2 31 10 PM

**Comment by UKChris-osm** [comment]
I've switched back to the main branch for the web site now.

**Comment by UKChris-osm** [comment]
Sorry @kjonosm, but making a change for #7299 has caused a conflict with this PR, so I've created a new PR with #7301 that adds a Wikidata search, but retains the Wikipedia search link also.

**Pull request closed without merging**
