### PR TITLE
Multiple additions on shoes.json

### PR DESCRIPTION
**Pull request by coderbeetle**
- ABCマート: Added two more country codes, Wikidata code, and Wikipedia link.
- Besson Chaussures: Added country code. A Wikipedia shop for this page does not exist, but I managed to find their operator information - so I added these too.
- FLO: Added country codes. Wikipedia page doesn't exist.
- Gabor: Added country codes, Wikidata code, and Wikipedia link.

### CODE REVIEW

**Comment by Adamant36** [comment]
I created a Wikidata entry for FLO to deal with #2383, but it ended up getting hung up. So if you want to add it this PR that would be great. Then I can close the other one. Its Q61994802

**Comment by coderbeetle** [comment]
Done!

**Comment by Adamant36** [comment]
Thanks. Two more minor things. In general we only add `name:en`  in cases where the `name:` tag is in another language, but we don't add other values like `name:jp` or anything. Since its essentially a duplicate of the `name:` key and we don't want to add to many name values to database (hopefully that's clear. If not I can provide some issue numbers that discuss it better for you to read). 

also, if you run npm run build before doing the commit it will check for any errors and get rid of the trailing space at the end of the file. Its not necessary, but helpful if you add more then a few lines of code.

**Comment by coderbeetle** [comment]
Thanks for letting me know! I think the duplicate names were already in the code, as far as I can recall I didn't add any names in other languages in addition to the English ones. Should I remove values like `name:ja` in the future?
As for the `npm run build`, I've been actually pretty confused as on how to run it. I'm assuming I'm supposed to run it on Git, but I haven't really been able to find any useful references on that.

**Comment by Adamant36** [comment]
No, its cool. They can stay in there if they were already added. I totally thought you had added them. Sorry. At least you know about it for the future now though. 

As far as `npm run build`, you run it in the terminal before you start editing the .json files and after you save your edits to commit them. The contributing file could probably be more clear about it. If you don't understand something, feel free to open a issue about it or just ask.

**Comment by bhousel** [comment]
> Thanks. Two more minor things. In general we only add `name:en` in cases where the `name:` tag is in another language, but we don't add other values like `name:jp` or anything.

No - we _do_ add tags like `name:jp` now to placate the various OSM validator tools.  See #2245

The build script will even add them automatically for languages like Japanese, where we can tell with a regex what language the name is in.

**Comment by Adamant36** [comment]
Oh yeah, my bad. I forgot the policy changed.

**Pull request merged**
