### PR TITLE
Add PostalAnnex

### PR DESCRIPTION
**Pull request by tas50**
Shipping / post office box company in the US.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by matkoniecz** [comment]
This is mapped just 3 times at this moment :)

**Comment by bhousel** [comment]
> This is mapped just 3 times at this moment :)

Awesome!  I love getting things into this index early, so things can be mapped consistently when people add them..

**Comment by tas50** [comment]
I'm really confused why this one isn't mapped more because they're fairly common on the west coast at least.

**Comment by tas50** [comment]
Oh it's because they're all mapped wrong. There's 37 of them, but most have a space between the two words.

**Pull request merged**
