### PR TITLE
Added BEA 東亞銀行 bank

### PR DESCRIPTION
**Pull request by zbc**

### CODE REVIEW

**Comment by Adamant36** [comment]
Hi there. It would be good to add brand:zh and name:zh.

**Comment by bhousel** [comment]
or if it is in classical, `brand:lzh` and `name:lzh`  (I don't know, I can't read it)
[details on Chinese multilingual names](https://wiki.openstreetmap.org/wiki/Multilingual_names#China)

**Comment by zbc** [comment]
Because of 東亞銀行 is Hong Kong-based bank, so it is written by traditional Chinese. 东亚银行 is the simplified Chinese for it.  `brand:lzh` is for the old ancient Chinese I think. How about I add simplified Chinese it to `brand:zh` and `name:zh`, since `zh` usually stands for simplified Chinese?

**Comment by zbc** [comment]
Or I can add `name:zh-Hant` and `name:zh-Hans` to differentiate traditional or/and simplified Chinese if you prefer?

**Comment by bhousel** [comment]
> Or I can add `name:zh-Hant` and `name:zh-Hans` to differentiate traditional or/and simplified Chinese if you prefer?

I don't know.. Just try to do whatever it says to do on the thing I linked 👍

**Comment by zbc** [comment]
My prettier messed up the format before, so I just fixed that issue too. Check it out. Thanks.

**Comment by bhousel** [comment]
Thanks @zbc looks good 👍

**Pull request merged**
