### PR TITLE
Use French wikipedia page for 8 à Huit convenience

### PR DESCRIPTION
**Pull request by bmillemathias**
As they are french based shops

### CODE REVIEW

**Comment by Adamant36** [comment]
I'm not sure if it matters. I've seem people do the exact opposite before and change the page reference to English. Its not like they aren't all linked to on Wikidata anyway.

**Comment by matkoniecz** [comment]
If all are in France then linking to a local Wikipedia is preferable.

BTW, country restriction is missing - I can add it. But to confirm:

@bmillemathias Are you sure that all, including ones existing but not mapped `name=8 à Huit shop=convenience` are in the France?

**Comment by Adamant36** [comment]
"If all are in France then linking to a local Wikipedia is preferable." 

Does it say that anywhere? I'm saying that its not, but I've seen it go both ways multiple times.

**Comment by matkoniecz** [comment]
It is certainly consensus among mappers in Poland, up to universally supported bot edits enforcing it.

There is also https://wiki.openstreetmap.org/wiki/Key:wikipedia 

> link to the Wikipedia article in the appropriate language

> which should be to the article in the primary language for the subject

> it is preferable to link article in a local language. It is appropriate to provide links to articles in secondary languages where there is no existing article about given object in local language. For example for museums in France French Wikipedia is preferred. But linking to the English article about the particular museum in France is OK if there is no matching article in French Wikipedia.

(disclaimer: I may be author of some quoted parts - see article history, but it is not a fresh change and so far I noticed no complaints)

**Comment by bhousel** [comment]
Thanks @bmillemathias 👍

**Comment by bhousel** [comment]
> "If all are in France then linking to a local Wikipedia is preferable."
> 
> Does it say that anywhere? I'm saying that its not, but I've seen it go both ways multiple times.

Yes, it mentions this briefly in the Contributing guide that for a non-English brand we should try to link to their local Wikipedia page.  (You're also right that it doesn't really matter much).

**Comment by Adamant36** [comment]
Ok cool. I must have missed it.

**Pull request merged**
