### PR TITLE
Update some nodes

### PR DESCRIPTION
**Pull request by waso99**

### CODE REVIEW

**Comment by bhousel** [comment]
Hey @waso99 can you describe the intent here?  It's not clear to me what you changed?

**Comment by waso99** [comment]
> 
> 
> Hey @waso99 can you describe the intent here? It's not clear to me what you changed?

Hey @bhousel, just adding and correcting some Saudi's brands in:
books.json 
supermarket.json
fuel.json
fast_food.json

**Comment by waso99** [comment]
> 
> 
> > Hey @waso99 can you describe the intent here? It's not clear to me what you changed?
> 
> Hi @bhousel, just adding and correcting some Saudi's brands in:
> books.json
> supermarket.json
> fuel.json
> fast_food.json

**Comment by bhousel** [comment]
> Hi @bhousel, just adding and correcting some Saudi's brands in:
> books.json
> supermarket.json
> fuel.json
> fast_food.json
> 
> could you tell me where is the mistake.

I see a few things:
- JSON syntax - the "Files Changed" tab on GitHub shows a diff view of the pull request, and highlights a few places missing a comma or bracket.
- You can't have multiple OSM tags with different values, for example this won't work:
Screen Shot 2021-02-15 at 1 50 16 PM

- Some things are duplicated, like there are 2 "Herfy" brands now, but maybe there were before?  
- Try to write commit messages that describe what you did, not just "update fast_food.json".  GitHub already shows us what files got changed - I'd rather see something like "Added 3 missing brands" or "Corrected misspelling of xxx" or something like that..

**Comment by waso99** [comment]
> 
> 
> > Hi @bhousel, just adding and correcting some Saudi's brands in:
> > books.json
> > supermarket.json
> > fuel.json
> > fast_food.json
> > could you tell me where is the mistake.
> 
> I see a few things:
> 
>     * JSON syntax - the "Files Changed" tab on GitHub shows a diff view of the pull request, and highlights a few places missing a comma or bracket.
> 
>     * You can't have multiple OSM tags with different values, for example this won't work:
> 
> 
> Screen Shot 2021-02-15 at 1 50 16 PM
> 
>     * Some things are duplicated, like there are 2 "Herfy" brands now, but maybe there were before?
> 
>     * Try to write commit messages that describe what you did, not just "update fast_food.json".  GitHub already shows us what files got changed - I'd rather see something like "Added 3 missing brands" or "Corrected misspelling of xxx" or something like that..

Sorry for my mistakes, because I am new with Github, next time I will do my best.
Thanks..

**Pull request closed without merging**
