### PR TITLE
Update outdoor.json : add Ekosport & Espace Montagne

### PR DESCRIPTION
**Pull request by raphodn**
Add 2 French sports retailers : Ekosport & Espace Montagne
- https://www.wikidata.org/wiki/Q130221125
- https://www.wikidata.org/wiki/Q130221137

### CODE REVIEW

**Comment by kjonosm** [comment]
@raphodn  Could you please limit the `locationSet` to `fx`?
For reference, see https://fr.wikipedia.org/wiki/France_métropolitaine

**Comment by kjonosm** [comment]
Hey @raphodn, could you also check whether [`sport=outdoor`](https://wiki.openstreetmap.org/wiki/Tag:shop=outdoor) fits better for these brands?

**Comment by raphodn** [comment]
@kjonosm ok done !

**Comment by kjonosm** [comment]
Thanks!

**Pull request merged**
