### PR TITLE
More Japanese Brands (part 3)

### PR DESCRIPTION
**Pull request by sguinetti**
This is a third pull request, the previous pulls were #2365 and #2367. Add business brands about cinema, banks, restaurants, convenience stores and clothes. Thanks.

- Also, Added Hush Puppies brand
- About 7-Eleven: Added alternative typos with "-"
- About Nishimatsuya Chain, Hotto Motto and Pronto: Add NoMatch.
- About Ito-Yokado. Add Match (writed in Wikipedia Article)
- There are different numbers in "count" from this pull request, build from npm.

### CODE REVIEW

**Comment by Adamant36** [comment]
Whoever sees this might want to wait until #2243 is finished to merge it. As its currently being worked on. 

@sguinetti, With the McDonald's it should only have the name in the language the entry is for and English. So you need to get rid of either ko or zh. Along with two of the name entries for Bank of Japan and any other ones that aren't just the entry language and English, like LAWSON, and on the last entry id get rid of operator:en because the Wikipedia page is in English and that's good enough IMHO. 

Also, it would it be good to split your contributions into smaller PRs. 292 lines in 11 commits is a lot to go over and make sure is correct (as is evidenced by the merge conflict).

**Comment by sguinetti** [comment]
@Adamant36 Yes, I notice it again. I'm sorry again. I was able to divide into 3 parts, but I had to reduce more. In each brand, I added a lot of information.

Otherwise, I saw in Openstreetmap that they added the name: ko key to the Lawson brand (via Overpass Turbo). So, add the translated name could help to other visitors in the translated name without problems.

When you say "last entry", are you mean Lawson-Three 3?

**Comment by Adamant36** [comment]
YorkMart for the last entry. 

As far as the name goes, people can add whatever names they want in OSM. See https://github.com/osmlab/name-suggestion-index/pull/2365#issuecomment-468703966 though and also the last paragraph in https://github.com/osmlab/name-suggestion-index/pull/2222#issuecomment-450438029

To quote it "So far we've just been doing name - and we add name:en only if name is not readable in English. I don't think it would be really helpful to add more than those, and it could get messy if we start automatically adding 100 more tags for international names, so let's not."

**Comment by sguinetti** [comment]
@Adamant36 Right. I will follow that point: Keep the names of these brands in English and Japanese only.

**Comment by sguinetti** [comment]
I was wrong. The commit 27b9de3  says "Change wikipedia article to japanese, and keed title in english".

**Comment by bhousel** [comment]
> Whoever sees this might want to wait until #2243 is finished to merge it. As its currently being worked on.

It's ok - I did #2243 it in a way that we can keep `canonical.json` around until everything is merged. I'll finally remove it today and update the docs.

**Comment by bhousel** [comment]
@sguinetti  I noticed these entries:

```js
  "shop/baby_goods|西松屋": {
    "count": 67,
    "countryCodes": ["jp"],
    "nomatch": ["shop/clothes|西松屋"],
    "tags": {
      "brand": "西松屋",
      "brand:en": "Nishimatsuya Chain",
      "brand:wikidata": "Q11628761",
      "brand:wikipedia": "ja:西松屋",
      "name": "西松屋",
      "name:en": "Nishimatsuya Chain",
      "shop": "baby_goods"
    }
  },
...
  "shop/clothes|西松屋": {
    "count": 159,
    "nomatch": ["shop/baby_goods|西松屋"],
    "tags": {
      "brand": "西松屋",
      "brand:en": "Nishimatsuya Chain",
      "brand:wikidata": "Q11628761",
      "brand:wikipedia": "ja:西松屋",
      "clothes": "children",
      "name": "西松屋",
      "shop": "clothes"
    }
  },
```

As specified here, it looks like there is a single brand that operates both generic clothing stores and also separate baby good stores. 

If they are really different, it's ok to keep them as 2 entries like this and "nomatch" each other.

But if they are really the same thing, we should pick a single entry (probably the baby goods one) and "match" the less desired entry.   

Think about it and let me know whether you want me to change it.. thanks!

**Comment by bhousel** [comment]
@sinclarius  - can you check these entries for "西松屋"  ?
We're not sure whether it should be merged into a single entry, or remain as two.

**Comment by sinclarius** [comment]
@bhousel Sure thing, I'll try to get to it today. Sorry—totally missed this message last week!

**Comment by sinclarius** [comment]
I'm not personally familiar with any Nishimatsuya storefronts, but I think it's safe to merge it into a single entry. From the company profile page (https://www.24028.jp/company/outline) and the executive's message page (https://www.24028.jp/company), it looks like it's **both** a baby and children's clothing store ("ベビー・子どものくらし用品専門店チェーン"). I looked at a couple of their listed stores, and I found a few cases where they noted some specific baby items that they don't carry. However, the circular ads for those stores still showed a lot of items for both babies and children (https://www.nishimatsuya.com/flier/chirashir_0228_0319/html5.html#page=1). Hope that helps!

**Comment by bhousel** [comment]
Thanks for checking @sinclarius - It sounds like they sell mostly baby things, so I merged them into the `shop=baby_goods` entry in e60767e.

**Pull request merged**
