### PR TITLE
Add Randstad

### PR DESCRIPTION
**Pull request by DivyaB1**
Hi,

I'm adding Randstad - https://www.randstad.com/

Thanks,

### CODE REVIEW

**Comment by arrival-spring** [comment]
Thanks for adding this, mostly looks good to me.

I think name and brand should both be capitalised, despite their logo having lower case r, in text on their website they use upper case 

Also, I think the location set for this needs to be limited, see https://www.randstad.com/find-randstad-in-your-country/

**Comment by DivyaB1** [comment]
Updated brand name with a capital 'R' and added countries separately

**Comment by bhousel** [comment]
thanks @DivyaB1 👍

**Comment by kjonosm** [comment]
@DivyaB1 and @bhousel Randstad is now listed in NSI as both `office=consulting` and `office=employment_agency`.
Which would be the right office type to keep?

**Comment by DivyaB1** [comment]
I believe it should be `office=employment_agency`.

**Pull request merged**
