### PR TITLE
Filter out generic tailors

### PR DESCRIPTION
**Pull request by tas50**
Mens
Womens
Mixed

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by Adamant36** [comment]
You might have waited on the PR until #2243 is done since its currently being worked on.

**Comment by tas50** [comment]
Oh nice. I'll wait on that. I look forward to GitHub being able to display a diff, as well as Atom/Sourcetree not crashing due to the diff size.

**Comment by matkoniecz** [comment]
@tas50 Thanks for noticing this generic entries!

**Comment by Adamant36** [comment]
There's Juicy Couture clothing stores out there and some other ones with random "couture" names. So it might be worth keeping the generic one and adding it as a match for a new "Juicy Couture" entry if there isn't one already (it looks like the name Juicy Couture has 16 uses).

**Comment by tas50** [comment]
@Adamant36 There's plenty of valid Couture names so instead of a name filter I did this one on the tailor key. It should only catch the bogus mens/womens/mixed tailors.

**Comment by Adamant36** [comment]
How do you know they aren't Couture licensed or branded tailers in other branded clothing stores?

**Comment by bhousel** [comment]
> How do you know they aren't Couture licensed or branded tailors in other branded clothing stores?

This is something I think about sometimes - whether there is an actual brand that has a generic word for a name.  I think it's ok to keep them excluded until we find examples of it.

**Comment by tas50** [comment]
In this case they're almost entirely in 1 city in the Ivory Coast. I'd imagine they're probably all from 1 mapper or a group of mappers. Couture is part of several brand names, but that's just because it's a term for handmade fitted clothes. It's pretty safe to say these are all just tailors.

**Comment by Adamant36** [comment]
Hhhmmm, I'll have to leave a note there asking what the actual names of the places are.

**Comment by tas50** [comment]
We should definitely get a note on those locations for further surveying.

**Pull request merged**
