### PR TITLE
Update engineer.json Add Alstom

### PR DESCRIPTION
**Pull request by Guerme**
Adding Alstom - https://www.alstom.com/

### CODE REVIEW

**Comment by kjonosm** [comment]
@Guerme Sorry for nitpicking but according to OSM wiki `office=engineer` is used for an office that is offering (individual) engineering as a service. However, Alstom is a manufacturer in the infrastructure (mainly rail) industry.

**Comment by Guerme** [comment]
@kjonosm - No worries.  I see that there is an OSM key for manufacturer.  Should I add a manufacturer.json file?  If so, should it go in the man-made folder?

**Comment by kjonosm** [comment]
From my understanding there is no established tagging yet. Depending on the place it could be [`office=company`](https://wiki.openstreetmap.org/wiki/Tag:office=company), [`man_made=works`](https://wiki.openstreetmap.org/wiki/Tag:man_made=works) or [`industrial=*`](https://wiki.openstreetmap.org/wiki/Key:industrial). Any ideas @1ec5?

**Comment by 1ec5** [comment]
If Alstom’s facilities are that diverse, there would be multiple entries for the same operator, one per tag. It’s also possible that, say, a given company’s offices may be more relevant for inclusion in NSI than its factories or vice versa.

**Comment by bhousel** [comment]
I'm just going to accept this as-is.  If there's a better category for it, we can move it, but calling them an engineering office isn't completely wrong.

**Pull request merged**
