### PR TITLE
Update Robidog entry

### PR DESCRIPTION
**Pull request by habi**

### CODE REVIEW

**Comment by habi** [comment]
Should have been added to https://github.com/osmlab/name-suggestion-index/pull/8516, but I couldn't figure out how to do it...

**Comment by habi** [comment]
Yes, because of https://github.com/osmlab/name-suggestion-index/issues/957#issuecomment-770282691

**Comment by habi** [comment]
Thanks for the clarification, I didn't know that.
Changed accordingly.

**Comment by habi** [comment]
Yes, that's true.
But a while ago I've updated the Robidog preset to include `bin=yes`, which I actually think is semantically more correct.
The are all waste baskets, too, but often their opening is small enough to only accept 🐶 💩  bags.

**Comment by habi** [comment]
The 'issue' arose that EveryDoor is using nsi.guide, and searching for 'Robidog' there doesn't bring up the excrement bag dispenser anymore.

**Comment by bhousel** [comment]
supersceded by #9247

**Pull request closed without merging**
