### PR TITLE
Add some matchTags

### PR DESCRIPTION
**Pull request by peternewman**
For shop=clothes and clothes=outdoor type cases.

### CODE REVIEW

**Comment by arch0345** [comment]
Looks good @peternewman

**Comment by peternewman** [comment]
Thanks @arch0345 . I did vaguely wonder if these should be for the whole category instead rather than just individual brands...

**Comment by arch0345** [comment]
Yeah I also think this could be applied to the whole category, to do this `shop/outdoor` could be added here:
https://github.com/osmlab/name-suggestion-index/blob/main/dist/matchGroups.json#L86-L96

**Comment by peternewman** [comment]
> Yeah I also think this could be applied to the whole category, to do this `shop/outdoor` could be added here: https://github.com/osmlab/name-suggestion-index/blob/main/dist/matchGroups.json#L86-L96

Cool, given that agreement, I've done it, although I think you meant config rather than dist!

I've also done it here instead:
https://github.com/osmlab/name-suggestion-index/blob/fe358961bf175d06732c0a048dcd730602b363e0/config/matchGroups.json#L189-L192

As it was a smaller and more appropriate group.

PTAL at #6385

**Pull request merged**
