### PR TITLE
add pantai timor mart

### PR DESCRIPTION
**Pull request by MASangys**

### CODE REVIEW

**Comment by bhousel** [comment]
Why do all the brands "Billion", "Pantai Timor Mart", "Pantai Timor"  in #5093 and #5094 link to the same `brand:wikidata` "Billion Shopping Center" [Q106989381](https://www.wikidata.org/wiki/Q106989381) QID which relates to "Pasar Raya Billion" [wikipedia page](https://ms.wikipedia.org/wiki/Pasar_Raya_Billion)? 

There's definitely a lot inconsistent about these PRs.. Is this a parent organization with several sub brand?

**Comment by MASangys** [comment]
All 3 

> Why do all the brands "Billion", "Pantai Timor Mart", "Pantai Timor" in #5093 and #5094 link to the same `brand:wikidata` "Billion Shopping Center" [Q106989381](https://www.wikidata.org/wiki/Q106989381) QID which relates to "Pasar Raya Billion" [wikipedia page](https://ms.wikipedia.org/wiki/Pasar_Raya_Billion)?
> 
> There's definitely a lot inconsistent about these PRs.. Is this a parent organization with several sub brand?

Is this a parent organization with several sub brand?
-Yes. Billion is the general brand, but in some area, they use “Pantai Timor” as their brand name, but still the same mother company. Pantai Timor Mart is mini market version of this store.

**Comment by MASangys** [comment]
Any update regarding this?

**Comment by bhousel** [comment]
I found the list of stores:  https://billiongroup.com.my/store-locator/

I guess these are the three store formats:
Screen Shot 2021-05-28 at 9 07 19 AM

It would fit better in NSI if we have a separate wikidata for each one but I guess it's ok for now to use the parent wikidata qid.

**Pull request merged**
