### PR TITLE
Add Christine Laure

### LINKED ISSUE #3700: Add french clothes Christine Laure
`name=Christine Laure`
`shop=clothes`

Currently 44 / 153 shops in France https://overpass-turbo.eu/s/SNt
website: https://www.christine-laure.fr
wikidata: [Q90472537](https://www.wikidata.org/wiki/Q90472537)

Shops are stored in https://www.christine-laure.fr/storelocator/
```html
<div class="items" style="display: none;">
```

### PR DESCRIPTION
**Pull request by pyrog**
fix #3700

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Does the brand have any social media accounts (Twitter, Facebook) that can be added to the Wikidata?

**Comment by pyrog** [comment]
Founded some facebook pages for local shops. Nothing on Twitter or Instagram.

Logo is there: 
Logo

**Comment by tas50** [comment]
I linked the Facebook account to the wikidata so we'll get a logo.

**Comment by tas50** [comment]
Thanks @pyrog

**Pull request merged**
