### PR TITLE
Move Ross, TJ Maxx, TK Maxx to department_store

### LINKED ISSUE #3006: Move TJ Maxx to shop=department_store?
The NSI currently lists TJ Maxx as `shop=clothes`.  However, [Wikipedia](https://en.wikipedia.org/wiki/TJ_Maxx) and the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Tag:shop%3Ddepartment_store) specifically refer to TJ Maxx as a "department store".

What are people's thoughts on `shop=department_store` vs `shop=clothes`?

https://github.com/osmlab/name-suggestion-index/blob/a052e67a011f9820f1a15e370b6e172b3f16a9ae/brands/shop/clothes.json#L2763-L2772

### PR DESCRIPTION
**Pull request by mds08011**
Moves Ross, TJ Maxx, and TK Maxx from `shop=clothes` to `shop=department_store`

Resolves #3006

### CODE REVIEW

**Comment by tas50** [comment]
I think it's a stretch to call Ross a department store, but it's referred to as a department store in places like Wikipedia so 👍

**Comment by mds08011** [comment]
I agree but it also sells much more than just clothes 🤷‍♂

**Comment by 1ec5** [comment]
`department_store=discount` 🤷‍♂

**Comment by tas50** [comment]
Sometimes you just have to find the thing that fits best. We tag walmart as supermarkets 🤷‍♂

**Comment by 1ec5** [comment]
That’s a bit of a counterexample actually. Walmarts and other hypermarkets are tagged as supermarkets because of what they primarily sell, but these discount department stores are being tagged as department stores because of what they happen to also sell. By the same reasoning as Walmart, we’d be tagging them as clothing stores.

**Pull request merged**
