### PR TITLE
Ticket #805 

### PR DESCRIPTION
**Pull request by lrm25**
Removed "Casablanca" and "Casa Blanca" from restaurant ……name suggestions (see reason in ticket comments)

### CODE REVIEW

**Comment by bhousel** [comment]
This looks mostly good - can you redo the commit without checking in your `.swp` files?

**Comment by lrm25** [comment]
Oops.  Just removed them.

**Comment by lrm25** [comment]
NM, it's been a while since I've used git.  Forgot that everyone will pull those.  I have to undo the commit.  One second.

**Comment by lrm25** [comment]
OK, it should be good now.  Let me know if there are any issues.

**Comment by bhousel** [comment]
LGTM, thanks @lrm25 👍

**Pull request merged**
