### PR TITLE
Added grocery.json to shop

### PR DESCRIPTION
**Pull request by AnjaliGGeetha**
added ration shop to grocery.json

### CODE REVIEW

**Comment by bhousel** [comment]
@AnjaliGGeetha please don't open a new pull requests for every change.  You can just push a revision to your working branch and GitHub will pick up the change. 

The bigger issue is that I am not comfortable adding a `shop=grocery` tag to this index, when better supported alternatives `shop=convenience` and `shop=supermarket` are available.. Can you please pick one of those?

I'm also confused about the mismatch between "Public Distribution System", the operator, and "Ration Shop" the store.  Is it really a brand?  Put another way, it shouldn't say `"brand": "Ration Shop"` but then link to the Public Distribution System wiki resources. Also the Public Distribution System wikidata page for Q60901 is basically empty, so I'm having trouble finding out anything about it.

**Comment by AnjaliGGeetha** [comment]
In Kerala there are 14000 ration shops that sell dry food items like grains and sugar. One exception being kerosene. Its role is in food security; grocery is closest to it. There is nothing better in OSM at the moment.

**Comment by naveenpf** [comment]
@AnjaliGGeetha please do discuss in community before raising the PR request

**Comment by naveenpf** [comment]
https://wiki.openstreetmap.org/wiki/India/Tags/Shop

Tagging scheme based on 2017 discussion

**Comment by bhousel** [comment]
> https://wiki.openstreetmap.org/wiki/India/Tags/Shop
> Tagging scheme based on 2017 discussion

Ok thanks @naveenpf for the link to the previous discussion.  @AnjaliGGeetha please switch this item to `shop=convenience` to match that recommendation.

**Comment by colonelm** [comment]
@bhousel going by the tag definition on OpenStreetMap wiki, grocery is what is most appropriate. However if all of it gets mapped with name Ration Shop, practically level problem can be addressed. Most important is making it easy to map ration shop.

**Comment by AnjaliGGeetha** [comment]
@bhousel Added the item to shop=convenience

**Comment by bhousel** [comment]
Thanks, this was merged in 2d03808f and preceding commits.

**Pull request closed without merging**
