### PR TITLE
Add wikipedia data and resolve build warnings

### PR DESCRIPTION
**Pull request by tas50**
Fixup some warnings and add some wikipedia entries.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by Adamant36** [comment]
Hi there. Just a heads up, if you do npm run build when your done before you submit the PR it will check for errors in your code and get rid of the red arrow (trailing space or whatever) at the end of your code. Its not 100% necessary, but still good to do just in case.

**Comment by tas50** [comment]
I'm pretty sure that's npm run build actually nuking a new line that someone else added in.

**Comment by Adamant36** [comment]
> I'm pretty sure that's npm run build actually nuking a new line that someone else added in.

Hhhmmm, I'm not sure that's how it works. A new line is created every time you save the canonical.json and its not from something before you or it wouldn't throw up the error I don't think. https://stackoverflow.com/questions/34271528/what-is-little-red-arrow-and-no-sign-in-github-desktop

**Comment by bhousel** [comment]
This seems ok now.. Thanks @tas50 !   
I'm not too worried about the trailing newline 😄

**Pull request merged**
