### PR TITLE
Added Margin Free Market

### PR DESCRIPTION
**Pull request by AnjaliGGeetha**

### CODE REVIEW

**Comment by Adamant36** [comment]
Hello. Do you think it goes by "Margin Free Market" or some variation of "MarginFree" more in OSM?

**Comment by AnjaliGGeetha** [comment]
The name is used inconsistently, but the registered one as per their website is MarginFree (https://www.mfreem.com/). So I am changing the brand name to MarginFree.

**Review by bhousel — CHANGES_REQUESTED** [review]
Can you fix the name?  It definitely shouldn't be "MarginFree Market Pvt Ltd"..

**Comment by AnjaliGGeetha** [comment]
Changed file.

**Pull request merged**
