### PR TITLE
Add Maryland Fried Chicken

### PR DESCRIPTION
**Pull request by resistiv**
Added Maryland Fried Chicken, an American fried chicken and seafood chain, to restaurants.json

### CODE REVIEW

**Comment by tommylung** [comment]
Thanks

**Comment by Cj-Malone** [comment]
This wikidata entry was deleted..

**Comment by resistiv** [comment]
> This wikidata entry was deleted..

Yes, unfortunately so...
I'm trying to have it restored, as it was deleted for not being notable per Wikidata's standards.
I'll roll back my commits if I can't get it restored soon.

**Comment by Cj-Malone** [comment]
I've managed to get a few restored recently, good luck.

Some bullet points that I've brought up with Wikidata admins:

- Lack of detail. Apologise and add more.
- Notability:
- - If you know the number of POIs, say it. It's hard to argue that a chain with a bunch of physical locations isn't worth having data on.
- - "structural need". This one is harder to argue, there definition of "structural need" is just for Wiki projects. NSI isn't one. But we are open data and share goals. NSI has a complete need for this entry to be restored, without wikidata a brand can't be in NSI.
- Age, this entry was probably brand new by you. It can't reasonably have had multiple editors yet. Also after the next NSI release (weekly) it would have gotten P8253 which has "Wikidata property for an identifier that suggests notability".

**Comment by resistiv** [comment]
Howdy! Just to keep this updated, I've gotten the Wikidata item restored.
Will the P8253 property be added automatically by NSI, or should I go ahead and grab the ID from the JSON listing?
Thank you for the advice @Cj-Malone, it was very helpful in getting the item restored!

**Comment by Cj-Malone** [comment]
That's good, thank you.

It's added automatically, and the build scripts will look after it if it changes in the future. I don't see any issue in adding it manually though.

**Pull request merged**
