### PR TITLE
Update optician.json "Les Opticiens Mutualistes" => "Écouter Voir"

### PR DESCRIPTION
**Pull request by cayenne17**
Remove OLD "Les Opticiens Mutualistes"
Add old_name on new

I don't know if that's how it works?

### CODE REVIEW

**Comment by Cj-Malone** [comment]
We've agreed in principle for `old_name`. https://github.com/osmlab/name-suggestion-index/pull/9738 However it sounds like this rename happened 5 years ago. I think `matchNames` would be a better place for it.

**Comment by cayenne17** [comment]
> We've agreed in principle for `old_name`. #9738 However it sounds like this rename happened 5 years ago. I think `matchNames` would be a better place for it.

`matchNames` has nothing to do with OSM?

`old_name` I use it on OSM so that when people search with the old name, they find it.

**Comment by Cj-Malone** [comment]
`matchNames` is a NSI/iD thing so people can search for the old name and get recommend the entry. The value doesn't end up in OSM.

https://github.com/osmlab/name-suggestion-index/blob/bdaefe3ce78b949eff7d862593ce8321fd636eb3/data/brands/shop/optician.json#L137-140

**Comment by cayenne17** [comment]
@Cj-Malone I've just added matchNames with the old name.

**Comment by Cj-Malone** [comment]
Thanks

**Pull request merged**
