### PR TITLE
Added Yakiniku King (焼肉きんぐ) wikidata & wikipedia

### PR DESCRIPTION
**Pull request by yelaD**
Wasn't sure if I should have added `"brand:wikipedia": "物語コーポレーション"` instead, since 焼肉きんぐ (Yakiniku King) is a subsidiary of 物語コーポレーション (The Monogatari Corporation), according to the wiki https://ja.wikipedia.org/wiki/物語コーポレーション

### CODE REVIEW

**Review by Binnette — CHANGES_REQUESTED** [review]
Hi @yelaD, can you please update your pull request and remove all this formating changes?
Thank you.

Also can you please to improve the wikidata article ? https://www.wikidata.org/wiki/Q99735922 (take an other restaurant for example)

**Comment by yelaD** [comment]
Hi, this might be a noob question, but how do you update a pull request?

Also I've updated the wikidata article.

**Comment by yelaD** [comment]
I think the formating is fixed now, this took way to long hehe

**Review by Binnette — APPROVED** [review]
Looks good. TY :+1:

**Comment by bhousel** [comment]
Thanks for fixing @yelaD & welcome 👋

**Pull request merged**
