### PR TITLE
Update fast_food.json

### PR DESCRIPTION
**Pull request by Djiril**
Add Cojean french fast_food restaurant. I let you set the id, thanks ;)

### CODE REVIEW

**Comment by arch0345** [comment]
Thanks @Djiril and welcome!

**Comment by Djiril** [comment]
Thank YOU for the great job you do for the OSM community!

**Comment by Djiril** [comment]
How long does it take to be visible in OSM iD ? Thanks.

**Comment by LaoshuBaby** [comment]
> How long does it take to be visible in OSM iD ? Thanks.

I noticed that arch0345 just publish a new version to npm registry. (https://github.com/osmlab/name-suggestion-index/commit/4e5b73d2433141c7cd31092b88a33d8ce1d2cbf4)

We will publish new version of package weekly or half month.(usually) And after it publish to npm, it may need several days let all CDN use latest json. This time can't be control by ourselves, you can try clean you cache in local browser and reload iD tomorrow. FYI: https://github.com/osmlab/name-suggestion-index/discussions/6592

**Comment by Djiril** [comment]
Ok Thanks a lot for the information !

**Comment by UKChris-osm** [comment]
> How long does it take to be visible in OSM iD ? Thanks.

I can see this entry available in iD now @Djiril 👍

**Pull request merged**
