### PR TITLE
Create BricoCenter

### PR DESCRIPTION
**Pull request by carmeliale**

### CODE REVIEW

**Comment by arch0345** [comment]
Hi,
Thanks for your first PR! It looks like you added a new file containing this missing brand instead of adding it to the existing file for shop/doityourself. Make sure to cut and paste this into data/brands/shop/doityourself.json before marking this as ready for review. If you need any help, just let me know; I'll be happy to help you!

**Comment by carmeliale** [comment]
@arch0345
I'm at the basics with github. I understood how to create the code file but I have not yet understood how to move the file in the various folders that collect the various categories of NSI: If you want to show me how to do the gesture, it is more than accepted!
Thanks again

**Comment by arch0345** [comment]
Yeah, it's kind of confusing at first. 

Here are step-by-step directions to move the code you added to the designated file:
1. Select the code you added and copy (ctrl+c). You can delete this file now (trash can icon).
2. Open the 'data' folder
2. Open the 'brands' folder
3. Open the 'shop' folder
4. Scroll down to 'doityourself.json' and open it, the files are sorted alphabetically
5. Edit the file (pencil icon)
6. Insert a line under the line that includes `"items":  [` and paste your code (ctrl+v). For this file this is line 12.


There's more information about how to contribute on the [wiki](https://github.com/osmlab/name-suggestion-index/wiki) under the "For contributors" section of the side-panel.

**Comment by carmeliale** [comment]
Ok, i've got added Bricocenter and Wycon Cosmetics. if it is as I did and you described it then it is very easy. I got lost in a glass of water.

**Comment by arch0345** [comment]
Looks good! However, looks like you edited your fork instead of this one accidentally. I'll create another PR for this. Thanks for your first contribution!

**Pull request closed without merging**
