### PR TITLE
Add more petstores and countrycodes for several existing stores

### PR DESCRIPTION
**Pull request by tas50**
Add some major US pet stores and add in country codes for several of the US based stores already there.

### CODE REVIEW

**Comment by Adamant36** [comment]
I'm not sure how much it matters, but in 99% of the cases the country is below the tag count. It seems to look better that way if nothing else. In this case you have it both above and below it. Maybe it would be good to pick one way of doing it for the sake of consistency (hopefully below it).

**Comment by bhousel** [comment]
> I'm not sure how much it matters, but in 99% of the cases the country is below the tag count. It seems to look better that way if nothing else. In this case you have it both above and below it. Maybe it would be good to pick one way of doing it for the sake of consistency (hopefully below it).

It doesn't really matter.. The properties all should get sorted alphabetically when the build script runs.

**Comment by bhousel** [comment]
Thanks @tas50 looks good 👍

**Comment by Adamant36** [comment]
> It doesn't really matter.. The properties all should get sorted alphabetically when the build script runs.

Javascript and NPM sure are fancy. I'm frequently surprised by how much they can automate.

**Pull request merged**
