### PR TITLE
Removed EB Games; added it as GameStop matchname

### PR DESCRIPTION
**Pull request by ShinyDog2636**
EB Games branding was replaced with GameStop

### CODE REVIEW

**Comment by TagaSanPedroAko** [comment]
@ShinyDog2636 Actually, that only applies to Canada locations. Australia and NZ locations are not affected.

**Comment by TagaSanPedroAko** [comment]
@ShinyDog2636 Are you in the Talk-ca mailing list and saw those related to those chains?

**Comment by ShinyDog2636** [comment]
@TagaSanPedroAko Thanks for catching that, I made a bad assumption.

It looks like both EB Games and GameStop exist in Australia and NZ so this may be a little more difficult to fix. I'll try to delete this for now.

**Comment by TagaSanPedroAko** [comment]
@ShinyDog2636 Will do a better pull request removing EB games from Canada only (and adding it as matchName for GameStop"). Not sure if we should provide two separate presets for GameStop US and GameStop Canada; I don't know if it also has a separate brand for Quebec.

**Pull request closed without merging**
