### PR TITLE
Create tram_stop.json

### PR DESCRIPTION
**Pull request by Dimitar5555**
The purpose of this PR is to add transit tagging to tram stops. Let me know if everything is ok.

### CODE REVIEW

**Comment by bhousel** [comment]
So I took a look at https://wiki.openstreetmap.org/wiki/Tag:railway%3Dtram_stop

This seems ok if, like with bus stops, the tram stop tag can sit alongside the public transport tags without interfering with that tagging.

**Comment by Dimitar5555** [comment]
There are also fields for network and operator in both `=platform` and `=stop_position` (third and fourth fields respectively).
image
image

**Comment by Dimitar5555** [comment]
Is there any reason to hold this PR or it can be merged?

**Comment by bhousel** [comment]
> Is there any reason to hold this PR or it can be merged?

It seems fine 🤷 
If it isn't, someone will let us know..

**Pull request merged**
