### PR TITLE
added matchName tag and modified network tag on bus.json

### PR DESCRIPTION
**Pull request by EOEboh**

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
Looks like you meet with some problem about commit file 😱

**Comment by EOEboh** [comment]
Yeah, could you specify what I should have done better?

**Comment by EOEboh** [comment]
> Looks like you meet with some problem about commit file 😱

Yeah, could you specify what I should have done better?

**Comment by LaoshuBaby** [comment]
> specify what I should have done better?

You created a symbol link called name-suggestion-index in repository's folder, and haven't change the bus.json

**Comment by EOEboh** [comment]
> > specify what I should have done better?
> 
> You created a symbol link called name-suggestion-index in repository's folder, and haven't change the bus.json

Oh, how do i rectify this? the codebase is large

**Comment by EOEboh** [comment]
> If this is for @LaoshuBaby's suggestions in #6259, you can commit those suggestions directly from that PR. There should be a 'Commit Suggestion' button under each suggestion.

Ok, thank you very much

**Pull request closed without merging**
