### PR TITLE
Shop Updates: Alcohol, Bakery, Beverages, Bicycle, Bookmaker

### PR DESCRIPTION
**Pull request by coderbeetle**
A sum up of things I came across:

- **Alcohol:** I couldn't find any proof that the brands _Cave, Горилка, Градус, Градусы, Кристалл_ exist. The brands _Cellarbrations, Liquor Depot, Mitra, Super Liquor, Алкомаркет, Ароматный мир_ have no Wikidata codes.

- **Bakery:** I couldn't find any proof that the brands _AILI, Büsch, Hert, Ronde des Pains, Schneider_ exist. _Granier_ seems to point to one site but I'm not sure about it, same for _Le Fournil_.  I'm not sure about _파리바게뜨, 파리바게트_. The brands _Bäckerei Schmidt, Bäckerei Schneider, Dat Backhus, Der Mann, Fischer, Goeken backen, Hinnerbäcker, Julie's Bakeshop, Lipóti Pékség, Marie Blachère, Mlinar, Nothing Bundt Cakes, Nur Hier, Oebel, Pan de Manila, Schäfer's, Sternenbäck, Булочная Ф. Вольчека, Кулиничи, Кулиничі_ have no Wikidata codes.

- **Beverages:** The brands _50嵐, Getränkeland, 茶湯會_ have no Wikidata codes. The brand _Бристоль_ is the same as one that exists in **alcohol**, and I didn't know what to do with it so I left it there - any suggestions?

Also - midway into tagging country codes, I noticed that there's not a fine distinction on what we should tag the United Kingdom - should it be `"gb"` or `"uk"`?

### CODE REVIEW

**Comment by coderbeetle** [comment]
I can't seem to find what's wrong :/ you can close this if you want and I'll try again later.

**Comment by matkoniecz** [comment]
>  I couldn't find any proof that the brands Cave, Горилка, Градус, Градусы, Кристалл exist.  

Are you interested in marking them as generics? https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#hocho--remove-generic-names is explaining how it can be done (let us know if anything is unclear in the documentation).

```
Error - Schema validation:
  ./brands/shop/bakery.json: 
  instance["shop/bakery|Marie Blachère"] additionalProperty "countryCode" exists in instance when not allowed
```

It should be `countryCodes` not `countryCode` (s is missing).

**Comment by coderbeetle** [comment]
I'll look into that! Thank you :)

**Comment by Adamant36** [comment]
The country code for the United Kingdom should be gb.

**Comment by coderbeetle** [comment]
Changed the country codes for the United Kingdom from `uk` to `gb` :)

**Comment by bhousel** [comment]
Thank you @coderbeetle! 👍   Looks great..

**Pull request merged**
