### PR TITLE
Add Hyatt hotels

### PR DESCRIPTION
**Pull request by tas50**
Adds the various Hyatt brand hotels with the operator of Hyatt. The Wikipedia page covers each of these brands.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by Adamant36** [comment]
Looks good I think. I doubt every hotel off shot will get its own Wikipedia page in this case. Those things are way to regional and probably not note worthy by themselves.

**Comment by Adamant36** [comment]
Mind if I ask why you didn't just go with a "match" for all of them under the Hyatt entry instead though?

**Comment by tas50** [comment]
They are very different locations that should get named with the correct name vs. slapping Hyatt on everything which would be incorrect. Some of those grands are very upscale hotels where as some are kinda dumpy. If you searched for Grand Hyatt you would want only those.

**Comment by Adamant36** [comment]
Like you say, the hotel industry is pretty convoluted. So its better to have them then not, I think.

**Pull request merged**
