### PR TITLE
updated national express

### PR DESCRIPTION
**Pull request by amous4822**
added missing tags and location #4404

### CODE REVIEW

**Comment by amous4822** [comment]
please review and revert.
Thanks.

**Review by bhousel — CHANGES_REQUESTED** [review]
I see from their wikipedia page https://en.wikipedia.org/wiki/National_Express that they might be the "operator" of a bunch of transit stuff around the world, but I think that the "national express" coaches are only a GB thing.

Also it looks like the wikidata that you added for them is wrong - Q1233212 links to A-welle.

So, this PR needs some work, and I'd like to get someone from GB to confirm how `network=National Express` should work.  (We can check overpass too)

**Comment by peternewman** [comment]
They certainly do coaches in the UK. It looks like they deserve their own network tag as I don't think they are just the operator for government routes:
https://en.wikipedia.org/wiki/National_Express_Coaches

**Comment by amous4822** [comment]
I tried to book tickets for their coaches around the world and it offered for places outside UK too. Should Location set contain all locations with available service or just the headquarters ? they have headquarters only in UK.

**Comment by bhousel** [comment]
Doing research like this is the main reason that we built the nsi.guide site 😄 

Here's what we know about National Express: https://nsi.guide/index.html?t=transit&k=route&v=bus#nationalexpress-8e0970
Clicking the Overpass query shows the places where "National Express" is used on a bus route:  https://overpass-turbo.eu/s/Zrc

Since we only see it used in Great Britain, I'd make the locationSet like this:
`{ "include": ["gb-eng", "gb-sct", "gb-wls"] }`

**Comment by amous4822** [comment]
This is a great tool !!
but I'm a bit confused, the website mentions stops at paris, amsterdam and other locations not shown in overpass-turbo. We should ignore this ?

**Comment by bhousel** [comment]
> but I'm a bit confused, the website mentions stops at paris, amsterdam and other locations not shown in overpass-turbo. We should ignore these locations ?

Yes sorry, this one is confusing - my guess is that this is an unusual bus operator.  

They operate "National Express" busses on the "National Express" network in Great Britain.  They also operate other busses on other networks in other places.  

For this `bus.json` file, we're trying to pin down the extent of the "National Express" bus network.  

Put another way, if you were to make a map of where "National Express" busses run, what would it look like?  The best map we can make with data gathered from OpenStreetMap looks like this (from Overpass):  
Screen Shot 2020-10-27 at 11 54 50 AM

It's probably incomplete, and our goal is to make the data in OpenStreetMap more complete and correct.

**Comment by amous4822** [comment]
updated the location set.

**Review by bhousel — APPROVED** [review]

**Comment by bhousel** [comment]
Thanks @amous4822 for the quick fixes 👍

**Comment by peternewman** [comment]
> Since we only see it used in Great Britain, I'd make the locationSet like this:
> `{ "include": ["gb-eng", "gb-sct", "gb-wls"] }`

Technically none of the currently mapped places are in Scotland.

Although they do mention Scotland on their website:
https://www.nationalexpress.com/en/destinations/edinburgh

Pre-covid they also ran routes to Northern Ireland:
https://www.nationalexpress.com/en/destinations/belfast/london-to-belfast

And even Ireland itself:
https://www.nationalexpress.com/en/destinations/dublin/london-to-dublin

**Comment by bhousel** [comment]
Hm yeah the situation is definitely complicated.
Looking at their own route map (https://routemap.nationalexpress.com/), I'd be comfortable expanding it to include Scotland, Paris, and Rome: 
 
Screen Shot 2020-10-27 at 1 37 24 PM
https://routemap.nationalexpress.com/

**Comment by peternewman** [comment]
Given they say temporarily suspended:
https://www.nationalexpress.com/en/destinations/dublin/london-to-dublin

Shouldn't we add the other places?

Or to ask the broader question, is NSI mapping for during Covid or before (and assuming things will come back), same thing with say restaurants which have become or added takeaway currently.

We could tag `covid:opening_hours=closed` for Ireland at least, but presumably other places in Europe it may still be travelling through even if it's not stopping.

**Comment by bhousel** [comment]
> Or to ask the broader question, is NSI mapping for during Covid or before (and assuming things will come back), same thing with say restaurants which have become or added takeaway currently.
>
> We could tag `covid:opening_hours=closed` for Ireland at least, but presumably other places in Europe it may still be travelling through even if it's not stopping.

A good way to think about the NSI is that we don't want to add anything to it that isn't true everywhere.  The tags in NSI will be suggested to users in other software like iD, or might be the basis of Maproulette tasks or automated cleanup scripts.

So I think because the covid situation is constantly changing, we should avoid storing tags like this in NSI (though mappers can definitely add these tags to the individual routes or businesses in OSM).

**Pull request merged**
