### PR TITLE
Added wikipedia tag to Milma & Added Jewellers

### PR DESCRIPTION
**Pull request by AnjaliGGeetha**
Added tag "brand:wikipedia": "en:Kerala Co-operative Milk Marketing Federation"

### CODE REVIEW

**Comment by AnjaliGGeetha** [comment]
1. Added tag "brand:wikipedia": "en:Kerala Co-operative Milk Marketing Federation"
2. Added Jewellers
 a). There are no wikipedia pages for Josco Jewellers (http://www.joscojewellers.in/)  and Chemmanur International Jewellers (http://www.chemmanurinternational.com/).
b). Jos Alukkas is the brand name as per their website https://www.josalukkasonline.com/. Name in their wikipedia page (https://en.wikipedia.org/wiki/Jos_Alukka_%26_Sons) seems incorrect .

**Comment by naveenpf** [comment]
Wikidata may be required to list this

**Comment by bhousel** [comment]
> Wikidata may be required to list this

We can accept these entries as-is and add the wikidata tags later if you want? 
They won't be exported to iD/JOSM presets until the wikidata tag is added.

**Comment by AnjaliGGeetha** [comment]
Please accept the current pull request. I will try wikidata and submit another request along with another set of brands.

**Comment by naveenpf** [comment]
https://www.wikidata.org/wiki/Q99520996 - Chemmanur International Jewellers
https://www.wikidata.org/wiki/Q99521002 - Josco Jewellers

**Comment by AnjaliGGeetha** [comment]
Added wikidata tag to jewellers

**Comment by bhousel** [comment]
Looks great, thanks @AnjaliGGeetha and welcome 👋

**Pull request merged**
