### PR TITLE
delete Philippine bus network values already merged to single network

### LINKED ISSUE #8338: Deleted PH bus networks restored
Any idea why some Philippine bus networks that have been removed at #8194 was restored?

### PR DESCRIPTION
**Pull request by TagaSanPedroAko**
networks in question has been deleted under #8194, but has been restored yet again for some reason.

Close #8338

### CODE REVIEW

**Comment by TagaSanPedroAko** [comment]
@tommylung You restored this?

**Comment by LaoshuBaby** [comment]
> Is this due to npm run build restoring already-deleted entries for some reason?

It's not his fault, no matter who it is, just doing `npm run build` now will cause them to be re-added, and that command is in publish checklist.

That's because of those data record:

https://github.com/osmlab/name-suggestion-index/blob/ff3bb985765eceafccb4d908c47ec4c398046e2b/dist/filtered/transit_keep.json#L912-L917

They all appear more than 10 times in the OSM data and thus belong to the category of "should be included in NSI". This is why I suggested in #8194 that you match them with the changed operator and cleanup OSM data if possible - it doesn't have to be, of course.

If you are sure that such colon-separated network names no longer exist in OSM data, this PR will be kept until the next update of filtered data.

**Comment by LaoshuBaby** [comment]
图片
I'm downloading latest pbf file and I'll generate a latest count file imitate [this PR](https://github.com/ideditor/nsi-collector/pull/13), so take it easy.

**Comment by TagaSanPedroAko** [comment]
Maybe that's worth a MapRoulette challenge.

**Comment by TagaSanPedroAko** [comment]
Just completed a sweep of routes using PH:PUJ:Cebu. Will follow up networks with PH:PUJ:Cavite and PH:P2P.

**Comment by TagaSanPedroAko** [comment]
Maybe we can mark this change as pending for now. Public transport network tag value format for the Philippines is currently being discussed through Telegram.

**Comment by TagaSanPedroAko** [comment]
Closed this. Discussion ended up with giving no preference for plain or prefixed network value, but encouraged using service branding for bus routes save Manila's city bus network. By the way, PH:PUJ: Sub values have been reinstated for use and will be kept so to localize tagging of jeepney routes rather than lumping them together in one nationwide network value.

**Pull request closed without merging**
