### PR TITLE
Multiple brands

### PR DESCRIPTION
**Pull request by xhika**
#4474

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Hi @xhika and thanks for taking care of #4474 👍 

Just one thing before accepting, if you're able to, could you go through your entries and changed any reference in the locationSet from "_uk_" to "_gb_" :)

**Comment by xhika** [comment]
> Hi @xhika and thanks for taking care of #4474 👍
> 
> Just one thing before accepting, if you're able to, could you go through your entries and changed any reference in the locationSet from "_uk_" to "_gb_" :)

Done, would you be so kind and label hacktoberfest-accepted also? 🙏

**Comment by UKChris-osm** [comment]
The hacktoberfest label won't be needed as we have tagged this project with the required topic label, so all PR's are acceptable by default now :)

**Comment by UKChris-osm** [comment]
Just out of interest @xhika was the edited text formatting for locationSet done by you or automatically by running npm run build?

**Comment by xhika** [comment]
> Just out of interest @xhika was the edited text formatting for locationSet done by you or automatically by running npm run build?

I've setup to auto format on save in Visual Studio Code :)

**Comment by bhousel** [comment]
> I've setup to auto format on save in Visual Studio Code :)

Going forward, could you disable that?  It does introduce a bunch of unwanted changes.

We could also maybe check in a project file that disables that option, maybe something to consider. 🤔 
https://stackoverflow.com/questions/38057725/turn-off-auto-formatting-for-json-files-in-visual-studio-code

**Comment by xhika** [comment]
> > I've setup to auto format on save in Visual Studio Code :)
> 
> Going forward, could you disable that?  It does introduce a bunch of unwanted changes.
> 
> We could also maybe check in a project file that disables that option, maybe something to consider. 🤔 
> https://stackoverflow.com/questions/38057725/turn-off-auto-formatting-for-json-files-in-visual-studio-code
> 

Will look into that, sorry for the trouble.

**Comment by tas50** [comment]
I think this should do it: https://github.com/osmlab/name-suggestion-index/commit/debe561673ef5f5761c5c0e7f1e3df62ebe78b8

There are probably more things we could enable/disable here, but this should stop the formatting on save.

**Pull request merged**
