### PR TITLE
Add local zone

### PR DESCRIPTION
**Pull request by Mannivu**
I've added local .geojson to better locate potential BBC Roma banks.

### CODE REVIEW

**Comment by arch0345** [comment]
Thanks for adding these geojsons, however, I recommend drawing these by hand instead with geojson.io using the polygon tool as suggested in this [wiki article](https://github.com/osmlab/name-suggestion-index/wiki/Feature-Files) since we try to use as few points as possible, see https://github.com/osmlab/name-suggestion-index/issues/4784#issuecomment-742003434. There's no strict limit, but I would try to use at less than 100 points per geojson.

**Comment by arch0345** [comment]
Thanks for adding these geojsons, however, I recommend drawing these by hand instead with geojson.io using the polygon tool as suggested in this [wiki article](https://github.com/osmlab/name-suggestion-index/wiki/Feature-Files) since we try to use as few points as possible, see https://github.com/osmlab/name-suggestion-index/issues/4784#issuecomment-742003434. There's no strict limit, but I would try to use at less than 100 points per geojson.

**Comment by Mannivu** [comment]
@arch0345 I've updated simplified version of the geojsons. I hope they are fine.

**Comment by arch0345** [comment]
Thanks @Mannivu!

**Pull request merged**
