### PR TITLE
Add RaceWay to brands

### PR DESCRIPTION
**Pull request by madesch**
Solves #3249

### CODE REVIEW

**Comment by madesch** [comment]
I see - I've created a [wikidata page](https://www.wikidata.org/wiki/Q73039084) which I can add to the json, will that suffice?

**Comment by bhousel** [comment]
> I see - I've created a [wikidata page](https://www.wikidata.org/wiki/Q73039084) which I can add to the json, will that suffice?

Yes that's excellent!   I'll try to add some more information to that page to ensure that the Wikidata admins keep it around 👍 

Could you also delete the `brand:wikipedia` tags - they still point to that disambiguation page and that's not completely correct.  Someday if somebody creates a wikipedia page like `"en:Raceway (brand)"`  we can point them to the correct page.  The most important thing is that the `brand:wikidata` field has a good value, so we can identify them all later...

**Comment by madesch** [comment]
Sure thing, thanks for the input! :)

**Comment by bhousel** [comment]
Thanks @madesch for the quick fixes and for adding the Wikidata page.. Welcome! 👋

**Pull request merged**
