### PR TITLE
Added multiple brand entries

### PR DESCRIPTION
**Pull request by UKChris-osm**
Added "_IMO_" (an international car wash company) to **/amenity/car_wash.json**

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Added "_London Camera Exchange_" to **/shop/camera.json**

**Comment by UKChris-osm** [comment]
Added "_Snappy Snaps_" to **/shop/photo.json**

**Comment by UKChris-osm** [comment]
Added "_Yours Clothing_" & "_BadRhino_" to **/shop/clothes.json** #3442

**Comment by UKChris-osm** [comment]
Added "_Dream Doors_" to **/shop/kitchen.json**

**Comment by UKChris-osm** [comment]
Added "_Beaverbrooks_" to **/shop/jewelry.json**

**Comment by UKChris-osm** [comment]
Added "_Jollyes_" to **/shop/pet.json**

**Comment by bhousel** [comment]
Thanks @UKChris-osm , these all look great 👍 

BTW thanks for all your contributions recently! To speed things up, I've invited you to be an admin on this project.  Feel free to triage issues, merge PRs, and commit directly to the master branch anything that you feel good about. 🙇

**Comment by UKChris-osm** [comment]
Thanks for the invite @bhousel, I wasn't expecting that, I'll have to up my game now :)

**Pull request merged**
