### PR TITLE
T-Mobile and Empik normalization

### PR DESCRIPTION
**Pull request by matkoniecz**
based on https://forum.openstreetmap.org/viewtopic.php?pid=661824#p661824 https://forum.openstreetmap.org/viewtopic.php?pid=661832#p661832 https://wiki.openstreetmap.org/w/index.php?title=WikiProject_Poland/Shops&oldid=1503653

### CODE REVIEW

**Comment by math1985** [comment]
Thanks!

The files still need to be regenerated.

**Comment by matkoniecz** [comment]
> The files still need to be regenerated.

By running `make`? I did it before making PR (and it failed to modify any files tracked in repository...).

**Comment by math1985** [comment]
Did you get any errors when running `make`? It should update name-suggestions.json and name-suggestions.min.json.

**Comment by matkoniecz** [comment]
No, and it updated name-suggestions.json and name-suggestions.min.json.

Neither is hidden by .gitignore.

`git check-ignore -v name-suggestions.min.json` and `git check-ignore -v name-suggestions.json` have an empty output unlike for example `git check-ignore -v test.pbf`.

I created folder `before` and put files generated before this PR and folder `after` and put files generated after changes introduced by this PR.

`diff before after` is empty - it probably means that as of today this PR introduced no changes in produced rules (maybe because some people changed empik to Empik in OSM - see https://wiki.openstreetmap.org/w/index.php?title=WikiProject_Poland%2FShops&type=revision&diff=1509171&oldid=1503653 ).

**Pull request merged**
