### PR TITLE
Add wiki tags for the German supermarket 'Nahkauf'

### LINKED ISSUE #1723: Research needed for: shop/supermarket|Nahkauf
#### :thinking: We need help deciding what to do with "shop/supermarket|Nahkauf"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|Nahkauf` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|Nahkauf`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|Nahkauf`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

### PR DESCRIPTION
**Pull request by ENT8R**
Fixes #1723

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @ENT8R !
I'm reading up on https://en.wikipedia.org/wiki/REWE_Group - it looks like they operate several sub-brands that don't have their own wikidata entries (and maybe should!)

The en: page suggests that Nahkauf is more of a convenience store than a supermarket.  Is this the case?  I'll merge the wiki tag, but we might want to revisit this entry later..

**Comment by ENT8R** [comment]
> The en: page suggests that Nahkauf is more of a convenience store than a supermarket. Is this the case?

I would say yes, but I'm not really sure about it because I live in a region where Nahkauf does not exist that much and I don't think that I ever visited one 😄
But from reading the German wiki page, I think that Nahkauf is not a real supermarket but rather a convenience store, so you are right 👍
So those shops should be rather tagged as `shop=convenience` and not as `shop=supermarket`, right?

**Comment by bhousel** [comment]
> So those shops should be rather tagged as `shop=convenience` and not as `shop=supermarket`, right?

Probably - are there some German mappers that you can reach out to?
I think they mostly talk on the osm forum:  https://forum.openstreetmap.org/viewforum.php?id=14

**Comment by ENT8R** [comment]
I will open a new topic and post the link here...

**Comment by ENT8R** [comment]
Opened a new topic: https://forum.openstreetmap.org/viewtopic.php?id=64138 I will post results here 😄

**Comment by ENT8R** [comment]
> > So those shops should be rather tagged as shop=convenience and not as shop=supermarket, right?

> Probably - are there some German mappers that you can reach out to?

The conclusion is that if a store (in Germany) has shopping carts, it should be tagged as `shop=supermarket` and if that is not the case it should rather be `shop=convenience`...
But "Nahkauf" is rather some medium-sized store which offers shopping carts, so in this case `shop=supermarket` should be the right tag to use.
Actually there is no real convenience store chain in Germany right now because people might prefer bigger store 😄

**Comment by bhousel** [comment]
> But "Nahkauf" is rather some medium-sized store which offers shopping carts, so in this case `shop=supermarket` should be the right tag to use.

Thanks for checking!  🙇

**Comment by ENT8R** [comment]
BTW: I will open a new PR to add the correct wikidata item after I created it 😄

**Pull request merged**
