### PR TITLE
Add German States

### PR DESCRIPTION
**Pull request by arch0345**
Simplified geojsons from #5900 
These can be tweaked as needed using this guide: https://github.com/osmlab/name-suggestion-index/wiki/Regional-Features

### CODE REVIEW

**Comment by SafetyIng** [comment]
Hey, 
I've created all 16 states;
[germany-states.zip](https://github.com/osmlab/name-suggestion-index/files/7774823/germany-states.zip)

**Comment by SafetyIng** [comment]
A little christmas gift ;)

**Comment by arch0345** [comment]
Thanks @SafetyIng! I'll add the rest of the states to this PR

**Comment by arch0345** [comment]
Hey there, `de-bb.geojson` in your zip file seems to be an invalid geojson. Could you take a look at this?

**Comment by SafetyIng** [comment]
Yeay, somewhere was a [ missed. Because (geo)json is a not supported file type  here as txt.
[de-bb.txt](https://github.com/osmlab/name-suggestion-index/files/7775236/de-bb.txt)

**Comment by arch0345** [comment]
Everything looks good now - thanks again @SafetyIng for taking the time to create these geojsons!

**Pull request merged**
