### PR TITLE
Create separate entries for SMART bus routes

### PR DESCRIPTION
**Pull request by arch0345**
Add 'smart-add5eb' for Suburban Mobility Authority for Regional Transportation and added wikidata/wikipedia and operator tags to each

### CODE REVIEW

**Comment by tas50** [comment]
If you run `npm run build` you should get a unique id here

**Comment by arch0345** [comment]
Sorry I'm a bit new to contributing on GitHub. I'm assuming the `npm run build` you're talking about is under 'checks'. When I looked at the error it said there were duplicate ids for the SMART network in Detroit, listing the id for the SMART network in Wilsonville (smart-a21cc9). Is it talking about the literal `id` tag in this entry? I added a different id for the SMART network in Detroit (smart-add5eb).

**Comment by tas50** [comment]
You run that locally in the git repo you checked out. There's some information in the readme on the commands you can use I believe. It generates unique IDs.

**Comment by arch0345** [comment]
Thanks for the clarification. I found the article you were talking about on the [Info for Maintainers](https://github.com/osmlab/name-suggestion-index/wiki/Info-for-Maintainers) wiki page.

After running `npm run build` a couple of times, it seemed to only work if I expanded the names to make them unique, which was fine by me. I'm still a little confused on why that error kept popping up even though there are multiple 'Metro' entries on the same file.

**Comment by LaoshuBaby** [comment]
> ).

I guess it is because the conflict of ```displayName``` tag, next time you can try to screenshot or copy the wrong hint.

if 2 item have same displayName, nodejs script will throw out error.

(2 item share same id will also)

**Comment by kjonosm** [comment]
@bhousel: Is it ok to use the same `network:short=SMART` for two separate items within the same location set? How does the validator work in such instances?

**Comment by bhousel** [comment]
> @bhousel: Is it ok to use the same `network:short=SMART` for two separate items within the same location set? How does the validator work in such instances?

I wouldn't do it - the matcher code will try to match on "smart" and might pick the wrong one.  

It would be better to have more narrowly scoped locationSets (like we're discussing in #5138)
And we should warn or fail if there are ambiguities like "smart" within a locationSet (which is #4921)

**Comment by bhousel** [comment]
I ended up redoing this in 72d137d0 after seeing how much trouble it can be to rename a `network` value that's already in use (see https://github.com/openstreetmap/iD/issues/8606) .

So I decided it's better to leave `network=SMART` for the different networks that use it (and I found another light rail that uses this value too), but gave them all unique locationSets scoped to where they are.

**Pull request merged**
