### PR TITLE
Add 1 fuel and Modify 3 fuel

### PR DESCRIPTION
**Pull request by LaoshuBaby**
## Add：
+ 中国海洋石油

## Modify:
+ 中国石油
+ 中国石化
+ Auchan

### CODE REVIEW

**Comment by hanchao** [comment]
Thanks @LaoshuBaby 
欢迎提交 Pull requests

**Comment by LaoshuBaby** [comment]
> 
> 
> Thanks @LaoshuBaby
> 欢迎提交 Pull requests

好家伙，NSI居然有自己人，幸会幸会，一起维护这个索引😊

**Comment by hanchao** [comment]
有个小问题，为啥我npm run build的顺序和你不一样。我这中文排在最后

**Comment by LaoshuBaby** [comment]
这个我也很好奇，每次我跑完以后都会自动全都跑到最前面去，我还以为是刻意有这个设定。
如果大家的npm都是中文最后的话，我手动挪过去便是
（但是我确实不懂nodejs，只会没有感情的敲```npm run build```）





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Han Chao"<notifications@github.com&gt;; 
发送时间: 2021年1月8日(星期五) 下午5:43
收件人: "osmlab/name-suggestion-index"<name-suggestion-index@noreply.github.com&gt;; 
抄送: "LAOSHU_CN"<keaitianxinmail@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [osmlab/name-suggestion-index] Add 1 fuel and Modify 3 fuel (#4850)





 
有个小问题，为啥我npm run build的顺序和你不一样。我这中文排在最后
 
&mdash;

**Comment by LaoshuBaby** [comment]
> 
> 
> 有个小问题，为啥我npm run build的顺序和你不一样。我这中文排在最后

这个我也很好奇，每次我跑完以后都会自动全都跑到最前面去，我还以为是刻意有这个设定。
如果大家的npm都是中文最后的话，我手动挪过去便是
（但是我确实不懂nodejs，只会没有感情的敲```npm run build```）

**Comment by Identitaet** [comment]
@bhousel is it possible to add something to the build script which ensures that the sort order is consistent ?
I looked online but didn't find good answers (at least for now)(probably something to do with language settings)

**Comment by hanchao** [comment]
`.sort((a, b) => a.displayName.localeCompare(b.displayName, 'en-US'))   // sort normalItems by displayName`

This function works differently in different environments

https://tc39.es/ecma262/#sec-string.prototype.localecompare

**Comment by bhousel** [comment]
Yes I just realized this issue with `localeCompare` a few days ago..
In 023401ce I tried added that `en-US` locale hoping that it would force it to work the same way in all environments? 
I'll dig into the docs a bit more and see if I'm missing something. (let me know if you have ideas!)

**Pull request merged**
