### PR TITLE
Add Baristi and Café Punta del Cielo

### PR DESCRIPTION
**Pull request by puentejose**

### CODE REVIEW

**Comment by Adamant36** [comment]
Hello. Thanks for the PR. It looks fine. One question though, is https://cafebaristi.com/ the website for the Baristi entry? Thanks.

**Comment by puentejose** [comment]
@Adamant36 It's the website for the Baristi entry

**Comment by Adamant36** [comment]
Alright. I created a Wikidata entry for it, Q99959844, if you want to add it.

**Comment by Adamant36** [comment]
Never mind. I added it in dfa39d4. Thanks for the PR 👍

**Pull request merged**
