### PR TITLE
Remove inappropriate `network=` in Hong Kong worsening bus route tags

### PR DESCRIPTION
**Pull request by Kovoschiz**
They are either official service classifications by the government (routes totally unrelated to each other), or route brandings. The HK community hasn't agreed on a standard tagging on them yet (due to slightly more complex company structures), so I would not complete the info at this moment. Priority is on stopping wrong  re-taggings urgently, as seen from https://osmcha.org/changesets/118155528 et al by the same new user editing basically correct KMB values to meaningless categories (those titles are wrong too --- They aren't the official names used).

I have difficulty understanding  #6265: What is being asked there? @tommylung @LaoshuBaby

### CODE REVIEW

**Comment by tommylung** [comment]
Thanks for your research.

May I know where is the document about the standard tagging of Hong Kong's transports? I cannot find the document on OSM wiki. I think the new user just take the reference on other verified routes.

**Comment by Kovoschiz** [comment]
> May I know where is the document about the standard tagging of Hong Kong's transports? I cannot find the document on OSM wiki. I think the new user just take the reference on other verified routes.

The Hong Kong page on HK is not very updated or reviewed. We had some small debates in changesets and Discord in the past, especially concerning how to tag KMB & LWB and Ctb & NWFB (one reason I left it untouched for now).

**Comment by tommylung** [comment]
For example: 
[KMB 48X](https://www.openstreetmap.org/relation/13895715)
- [KMB Bus 48X (Bayview Garden → Wo Che)](https://www.openstreetmap.org/relation/13895700)
- [KMB Bus 48X (Wo Che → Bayview Garden)](https://www.openstreetmap.org/relation/5838583)

May I know this new user followed the standard tagging for Hong Kong?

**Comment by Kovoschiz** [comment]
Can you read your Discord? I message you some info.

**Comment by arch0345** [comment]
As @LaoshuBaby mentioned, these entries will get readded every time someone runs the `npm run build` script. This is because we collect common networks (used 10 or more times) from the planet each week. These should either get added to as one of the `matchNames` for another entry or get added to the `named` `exclude` list at the top of the file. With the exception of Long Win Bus, these entries won't be seen in iD as only entries with a linked Wikidata item get an iD preset.

**Comment by Kovoschiz** [comment]
Thanks for explaining here. I will see what I can do.

**Comment by Kovoschiz** [comment]
Await more general consensus on tagging

**Pull request closed without merging**
