### PR TITLE
add DB brands

### PR DESCRIPTION
**Pull request by Identitaet**

### CODE REVIEW

**Comment by Identitaet** [comment]
The error is I guess problematic since they are all operated by the same company

**Comment by bhousel** [comment]
Travis is failing because of this - It probably is because of the duplicate `operator`, so I'll need to fix that.  My fault, not yours! 😁 
Screen Shot 2020-10-01 at 5 36 01 PM

**Comment by Identitaet** [comment]
I mean just a small oversight from the normal procces

**Comment by bhousel** [comment]
just pushed a fix, I'll rerun Travis and see if that worked 🤞

**Comment by Identitaet** [comment]
works

**Pull request merged**
