### PR TITLE
Added Balfours

### PR DESCRIPTION
**Pull request by BenR31415**
Added Balfours, fixing issue #3275

### CODE REVIEW

**Comment by Adamant36** [comment]
Thanks for the PR. One issue though, `"amenity/cafe|GloriaJean":` and also the brand tag should both be Gloria Jean's like the name tag is.

**Comment by Adamant36** [comment]
Also on second thought Balfours might be better off in the bakery file. Although I can change it after merging if you don't feel like doing it.

**Comment by BenR31415** [comment]
>Thanks for the PR. One issue though, "amenity/cafe|GloriaJean": and also the brand tag should both be Gloria Jean's like the name tag is.

My apologies, I'll fix that up.

>Balfours might be better off in the bakery file

I couldn't see a Bakery file in the list? Could have missed it sorry

**Comment by Adamant36** [comment]
Thanks. No worries on not seeing the file. It's in there, but don't worry about it. Btw, I noticed you added Big 4 Holiday Parks to the caravan site. It's not a problem this time around, but it's generally helpful if the changes being made are kept to the original PR and a single issue. Otherwise, it gets harder to track what's going on and how it relates to what issue.

**Comment by bhousel** [comment]
thanks @BenR31415  - I moved Balfours to the bakery file in fa82d74c6

**Pull request merged**
