### PR TITLE
Added ALH Hotels Brand to Hotel.json

### PR DESCRIPTION
**Pull request by ckpiper**

### CODE REVIEW

**Comment by arch0345** [comment]
It looks like ALH Hotels is an operator of hotels, each of which has a unique name https://www.alhgroup.com.au/venues

**Comment by ckpiper** [comment]
Good catch. Not just hotels either. They have a lot of restaurants as well.

**Comment by UKChris-osm** [comment]
In this case you can add `"preserveTags": ["^name"]` under the `locationSet` tag and this will allow mappers to add the unique name of each hotel without the NSI trying to overwrite it later.

**Comment by bhousel** [comment]
> In this case you can add `"preserveTags": ["^name"]`

oh, that's not necessary here - it's already set that way for the whole `hotel.json` category at the top of the file..

**Comment by UKChris-osm** [comment]
> oh, that's not necessary here - it's already set that way for the whole `hotel.json` category at the top of the file..

Ops, I didn't notice that, thanks 👍

**Comment by ckpiper** [comment]
> this will allow mappers to add the unique name of each hotel without the NSI trying to overwrite it later.

@UKChris-osm I just got back from vacation, so that is why I am responding 2 weeks later. But I am a little confused on what you mean? Do you mean mappers will add the hotel name and this nsi_id and NSI will not overwrite the name with ALH Hotels?

**Pull request merged**
