### PR TITLE
Added info for Светофор, Командор and Десяточка supermarkets

### PR DESCRIPTION
**Pull request by mukulkhanna**
Resolving #1785 

- Made a wikidata entry for Светофор supermarket
- Added wikidata, countrycodes and brand:en in config/canonical.json
- Build successful ✅

### CODE REVIEW

**Comment by mukulkhanna** [comment]
Also resolving #1776 and #1774

**Comment by maxerickson** [comment]
I'm not terribly worried about Wikidata, but I guess the entry should have a Russian name and then also maybe an English name. Putting the Russian name in the English name isn't the way to do it. I've also tried to add some statements to any entries I've created (because that makes the entries useful for Wikidata).

**Comment by mukulkhanna** [comment]
@maxerickson Sorry for the misunderstanding. I can make the corresponding changes.

As of now, I have entered the english spelling for the Russian brand as the "brand:en" value.
Just wanted to clear out that for the english name ("brand:en"), you would like the meaning of the Russian name in english, right?

**Comment by Adamant36** [comment]
Just a heads up, but I think usually its name:en that's entered as it resolves errors, along with being more accessible. Brand:en isn't as important. Although it can still be added. Also, you should put "closes" before  the issue #. Which auto closes it the PR is merged. "Resolving" doesn't do anything. As can be seen by the fact that the issues "resolved" here are still open. 

It would be good if you or @maxerickson closed them. Probably in this case @maxerickson should do it since its apart of the basic maintainance tasks of a maintainer to close old issue. In the future though, it would be good to just put "closes" in your PR messages to save the extra steps. 

Thanks

**Comment by mukulkhanna** [comment]
@Adamant36 Okay, will take care next time. Thank you.

**Pull request merged**
