### PR TITLE
Gas stations Glusco are rebranded as U.GO (this is not a new brand)

### PR DESCRIPTION
**Pull request by serhii-muchychka**
…here is no wikidata)

### CODE REVIEW

**Comment by neviksasha** [comment]
> 

Not U.GO? I have seen this spelling of the name

**Comment by serhii-muchychka** [comment]
> > 
> 
> Not U.GO? I have seen this spelling of the name

Could you provide your version of the name please?

**Comment by UKChris-osm** [comment]
Hi @serhii-muchychka 

If there isn't a wikidata attached to an entry, it won't appear in the NSI dataset.

Are you able to create a wikidata, or edit the current one to reflect the new branding?

**Comment by serhii-muchychka** [comment]
@UKChris-osm done!

**Comment by UKChris-osm** [comment]
Is there an official website and social media links that can be added to the new Wikidata @serhii-muchychka??

**Comment by serhii-muchychka** [comment]
@UKChris-osm currently nothing. There is a page on the owner's website with addresses
https://www.naftogaz.com/power-drive

**Comment by neviksasha** [comment]
@UKChris-osm I can confirm, that this change is correct

**Pull request merged**
