### PR TITLE
Update public_bookcase.json - Added Bibliocabine

### PR DESCRIPTION
**Pull request by danieldegroot2**
Adds Bibliocabine.

Mapped:
- Bibliocabine (10+/20+) 

cc: @habi

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Hi @danieldegroot2 - is there a Wikidata that can go with this entry? Is this a genuine brand or does "_Bibliocabine_" just translate to bookcase? The web site for Bibliocabine generates an error when I tried to look.

**Comment by habi** [comment]
http://bibliocabine.ch/ works for me, albeit with a certificate error.

**Comment by danieldegroot2** [comment]
> Hi danieldegroot2 - is there a Wikidata that can go with this entry?

No, there is not yet. It is okay like with [previous PRs](https://github.com/osmlab/name-suggestion-index/pulls?q=is%3Apr+bookcase+is%3Aclosed+author%3Adanieldegroot2) to merge it as-is.

> Is this a genuine brand or does "_Bibliocabine_" just translate to bookcase? The web site for Bibliocabine generates an error when I tried to look.

This is their Facebook / Instagram page. The logo is usually signed on ones shown here.
- https://www.facebook.com/bibliocabine
- https://www.instagram.com/bibliocabine/

It does not seem to overlap with little free library / bookcrossing.

Here is an archived version of their website. It does list more booths also without the logo signed.
https://web.archive.org/web/20240616091727/https://bibliocabine.ch/

> Bibliocabine [the project] is promoted and financed by Ingrado Foundation
> The Ticino Bibliocabins are run by various associations. Some of these are part of a project supported by the Fondazione Ingrado Servizi per le dipendenze, a social institution that has been active in Ticino since 1979.
> For this project in particular, guests of the Ingrado Residential Centre in Cagiallo are involved in a social project of creative transformation of disused telephone booths.
> [There are] videos aired on Radiotelevisione Svizzera Italiana (RSI) in the programmes Il Quotidiano and Falò.

Ingrado has another project 'Bibliocasette' but it is not a network.
> The Bibliocasette continue the solidarity book exchange project started by the Bibliocabine. Each Bibliocasette is built in the carpentry workshop of the Cagiallo Residential Centre. [...] It is available in two sizes.

Ingrado does not have a wikidata page yet.

'bibliocabine'(fr/it) / 'bibliocabina'(it) is also a term for bookcase.

**Comment by danieldegroot2** [comment]
Added DECS wikidata as workaround, though feel free to discard the commit and merge as-is.
(reminder, I am on Github browser so personally can only revert by manually adding another commit to remove it.)

**Comment by Snowysauce** [comment]
I'm not sure I understand why this brand should be added to the NSI without a relevant Wikidata page. Without Wikidata, this brand won't be exported outside of the NSI - in other words, it won't be offered as a preset in OSM editors. (See [here for the technical details](https://github.com/osmlab/name-suggestion-index/wiki/Technical-Details#availability-of-entries-in-downstream-projects).)

**Comment by danieldegroot2** [comment]
It seems to be okay([reply](https://github.com/osmlab/name-suggestion-index/pull/6550#issuecomment-1120024165)) to have the brands already in the file, anyone who wants to contribute can then easily add the wikidata.
I would personally like to focus on contributing data to OpenStreetMap itself, it is already quite time-consuming.

**Comment by Snowysauce** [comment]
> It seems to be okay([reply](https://github.com/osmlab/name-suggestion-index/pull/6550#issuecomment-1120024165)) to have the brands already in the file, anyone who wants to contribute can then easily add the wikidata.

You are correct that anyone could add a Wikidata page, but in the 2+ years since that pull request was merged, no one has. I wasn't aware of this project in 2022, so I don't know what the index looked like back then, but as of this moment, there are 44,500 entities across the four trees, 10,900 of which don't have Wikidata identifiers - 25% of the index. This problem gets worse every time an entry is added to the index without Wikidata.

What that pull request from May 2022 tells me is that once an entry successfully makes it into the NSI, no one keeps tabs on it to ensure that whatever was missing at the time of submission is eventually added. I'm sure the other maintainers have also realized this as time has gone on, and that's why incomplete pull requests that may have been acceptable in 2022 don't appear to be in 2024. Time has proven that the only sure way to ensure that an entity has a complete entry in the NSI is to not add the entry at all until its data is complete.

**Comment by danieldegroot2** [comment]
> 25% of the index. This problem gets worse every time an entry is added to the index without Wikidata.

It is understandable this is frustrating, eventhough noteably many are/were added by an automatic generation script.
Closing in favour of converting to an issue. See #9991.

**Comment by danieldegroot2** [comment]
> 25% of the index. This problem gets worse every time an entry is added to the index without Wikidata.

It is understandable this is frustrating, eventhough noteably many are/were added by an automatic generation script.
Closing in favour of converting to an issue. See #9991.

**Pull request closed without merging**
