### PR TITLE
Add several brands (supermarket, nutrition supplement shop, vehicle inspection)

### PR DESCRIPTION
**Pull request by HLucasTargomo**

### CODE REVIEW

**Comment by Cj-Malone** [comment]
Looks like [Q119994958](https://www.wikidata.org/wiki/Q119994958) has been deleted. We need to request it to be undeleted.

**Comment by MisterSynergy** [comment]
This item was nominated for deletion at https://www.wikidata.org/wiki/Wikidata:Requests_for_deletions/Archive/2023/06/27#Q119994958 and then subsequently deleted by User:Jianhui67 as it currently does not meet the notability criteria, and it does indeed have some promotional character. Ideally you contact the deleting admin first on Wikidata.

Is there a NSI entry for this data item available?

Deleted data items can only be read by users with admin rights at Wikidata.

**Comment by Cj-Malone** [comment]
Thanks, I'll ping Jianhui67 tomorrow when I'm on my computer.

This PR was about to add the entry to NSI. Presumably the Wikidata entry was young too?

Once it's it's merged (and we do a release, weekly) the Wikidata entry gets a property linking to NSI.

**Comment by HLucasTargomo** [comment]
I added myself the wikidata entry into wikidata project, and one admin removed it some hours later for some obscure reason.

**Comment by Cj-Malone** [comment]
I've commented on Jianhui67s talk page

https://www.wikidata.org/wiki/User_talk:Jianhui67#Request_undelete_of_Q119994958

**Comment by MisterSynergy** [comment]
> I added myself the wikidata entry into wikidata project, and one admin removed it some hours later for some obscure reason.

Assuming you relate to Q119994958 in particular: this data item has been created by an anonymous IP user, thus it receives increased scrutiny. It is usually helpful to create items (and edit in general) using an account, although you can do it with one.

**Comment by Cj-Malone** [comment]
I have a suspicion new accounts get increased scrutiny too. As far as I know I've never had an item deleted, but my account older now.

**Comment by HLucasTargomo** [comment]
The data item has been undeleted: https://www.wikidata.org/wiki/Q119994958

**Pull request merged**
