### PR TITLE
Update redbox to vend video_games and movies

### PR DESCRIPTION
**Pull request by tas50**
They stopped selling just DVDs a long time ago.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by Adamant36** [comment]
What percent of kiosks rent video games though?

**Comment by tas50** [comment]
All the ones I've ever been to have games as well. I'll see if I can figure out a breakdown from their site.

**Comment by tas50** [comment]
I *think* that they don't all have games, but their support folks won't answer that for me. They gave me the physical address of their corporate office and told me to write them a letter asking. So movies it is. I'll update the PR

**Comment by SilentSpike** [comment]
Ah never mind, I see this was discussed 👍

**Pull request merged**
