### PR TITLE
remove unneded name matches in npm run build

### PR DESCRIPTION
**Pull request by matkoniecz**
see https://github.com/osmlab/name-suggestion-index/issues/2732

### CODE REVIEW

**Comment by matkoniecz** [comment]
After implementing and running it as a test I have two doubts

- it is violation of DRY to list `official_name`, `alt_name`, `short_name` in two places.

- I think that it may be confusing for user to see entries disappearing. Maybe it would be better to simply warn user and complain?

**Comment by bhousel** [comment]
You are kidding right?

**Comment by bhousel** [comment]
Oh sorry, read this too quickly.. I thought you were removing the matching code completely..

**Comment by bhousel** [comment]
> Maybe it would be better to simply warn user and complain?

We already do this I think?

**Comment by matkoniecz** [comment]
> We already do this I think?

Technically yes, but in a really cryptic way:

```
  "amenity/bank|ABN AMRO": {
    "countryCodes": ["nl"],
    "matchNames": ["ABN AMRO Bank N.V."],
    "tags": {
      "amenity": "bank",
      "brand": "ABN AMRO",
      "brand:wikidata": "Q287471",
      "brand:wikipedia": "en:ABN AMRO",
      "name": "ABN AMRO",
      "official_name": "ABN AMRO Bank N.V.",
      "operator": "ABN AMRO Group",
      "operator:wikidata": "Q17061287",
      "operator:wikipedia": "en:ABN AMRO Group"
    }
  },
```

generates

```
Warning - Brands match other brands:
--------------------------------------------------------------------------------
If the brands are the different, add a disambiguator after the name, like `~(USA)` vs `~(Canada)`
If the brands are the same, remove extra `matchTags` or `matchNames`.  Remember:
- Name matching ignores letter case, punctuation, spacing, and diacritical marks (é vs e). 
  No need to add `matchNames` for variations in these.
- Tag matching automatically includes other similar tags in the same match group.
  No need to add `matchTags` for similar tags.  see `config/match_groups.json`
--------------------------------------------------------------------------------
  "amenity/bank|ABN AMRO" -> matches? -> "amenity/bank|ABN AMRO ("abnamrobanknv")"
total 1
```

that is not clear at all. Anyway, it would be probably better to improve `Warning - Brands match other brands` for case where it matches itself.

**Comment by bhousel** [comment]
> that is not clear at all. Anyway, it would be probably better to improve `Warning - Brands match other brands` for case where it matches itself.

I agree we should improve the warning..

**Pull request closed without merging**
