### PR TITLE
Fix Cosmo brand, with matchnames

### PR DESCRIPTION
**Pull request by sguinetti**
This pull request "patches" Cosmo brand with matchname to avoid a duplicate with the English version (now deleted). See #3601.

### CODE REVIEW

**Comment by Adamant36** [comment]
I was going to merge this, but it seems seems to have conflicts for some reason that need resolving first.

**Comment by sguinetti** [comment]
I see the the conflict of this branch is "official_name": "コスモ石油". I'm not sure if I can fix that.

**Comment by Adamant36** [comment]
> I see the the conflict of this branch is "official_name": "コスモ石油". I'm not sure if I can fix that.

Hhhhmm, weird.

**Comment by Adamant36** [comment]
I think I fixed it.

**Comment by sguinetti** [comment]
Thanks for you help.

**Comment by bhousel** [comment]
:wave: Hey @sguinetti and @Adamant36 , I'm just catching up on a lot of the activity in this repo.  (I recently switched jobs, and am not at Mapbox anymore).

I think all the additions of the Japanese brands are awesome.  It's great that your work will help the community in Japan map POIs more correctly - keep it up! :+1: 

In a0dafc40 I cleaned up several of the `matchName` properties because they were redundant and causing warnings.  The matchNames are kind of confusing, but they are there to let the scripts (and other applications like iD) know whether a brand with a slightly different name can be considered the same thing. 

We don't need to add a `matchName` for:
- variations in capitalization, punctuation, spacing  (the middots common in Japanese names count as punctuation, so "V・ドラッグ" already matches "vドラッグ")
- names that already appear in the `name`, `alt_name`, `short_name`, `official_name` tag
- variations in diacritic marks (e.g." Freshëns" already matches "Freshens")
- variations in `&` vs. `and`

The code and rules have evolved, and I know that the current description in our contributing guide is out of date - That's my fault for not fixing it, and I'll get that corrected soon!  

Anyway hope this helps clear up some of the `matchName` confusion.  Let me know if you have other questions.

**Pull request merged**
