### PR TITLE
add brand wikidata and wikipedia for Motherhood Maternity

### PR DESCRIPTION
**Pull request by AlbyIanna**
solves #3165

### CODE REVIEW

**Comment by bhousel** [comment]
Realizing now that for this one we should probably push for separate wikidata for
* Motherhood Maternity
* A Pea in the Pod
* Destination Maternity

instead of just using the parent company's wikidata..

**Comment by AlbyIanna** [comment]
ok, but in that case we'd have wikidata and wikipedia for Destination Maternity only

**Comment by tas50** [comment]
@AlbyIanna Creating the wikidata for Motherhood Maternity is probably the best bet here. We can just leave the wikipedia line out since that would just point to the parent company.

**Comment by AlbyIanna** [comment]
> Creating the wikidata for Motherhood Maternity is probably the best bet here.
@tas50 How can I do that?

**Comment by matkoniecz** [comment]
See https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#creating-wikidata-entries

**Comment by Adamant36** [comment]
Motherhood Maternity: Q79051139
A Pea in the Pod: Q79051737
Destination Maternity: Q79051770

@AlbyIanna, you want to update the PR?

**Comment by bhousel** [comment]
> @AlbyIanna, you want to update the PR?

Thanks @Adamant36  - I'll merge as-is and apply the updates 👍

**Pull request merged**
