### PR TITLE
Fix for #4274 : added Tantalizers

### PR DESCRIPTION
**Pull request by 29parthi**

### CODE REVIEW

**Comment by 29parthi** [comment]
#4274 Fixed

**Comment by UKChris-osm** [comment]
Hi @29parthi,

Just a quick note, if "_short_name_" is the same value as "_name_", then you can remove "_short_name_" from your PR. Also, if you don't have an "_id_" value, you can remove that as well and it will be generated automatically later on :)

**Comment by Adamant36** [comment]
> if you don't have an "id" value, you can remove that as well and it will be generated automatically later on

What's the "id" for? I must have been out of the office that day.

**Comment by Adamant36** [comment]
Fixed in be253cf. Thanks for the PR.

**Comment by UKChris-osm** [comment]
> What's the "id" for? I must have been out of the office that day or something.

It's something that's now created automatically via **npm run build** for each entry, replacing the old "_amenity/fast_food|Tantalizers_" ID's that were used previously.

**Pull request merged**
