### PR TITLE
Adding detail

### PR DESCRIPTION
**Pull request by bkissin**
Added wikidata to Royal Farms, Turkey Hill. Added Rutter's

### CODE REVIEW

**Comment by Adamant36** [comment]
Looks like you forgot commas after the Wikidata entries.

**Comment by bkissin** [comment]
Dangit, not again! I'll add the commas now.

**Comment by bhousel** [comment]
Thanks @bkissin 
This one was also missing a `},` after the Rutter's entry, so I added it in 609658c8f.

**Comment by bkissin** [comment]
Thanks @bhousel! Sorry about the beginner mistakes!

**Comment by bhousel** [comment]
no worries @bkissin - everyone is a beginner!

My recommendation if you really want to contribute a lot to this project (or others) is to:
-  set up a local environment with git and node
- `git clone` the project to your computer 
- `npm install` to get the dependencies
- use a programming editor like Sublime, Atom, or VSCode that highlights syntax issues like missing commas
- when you make changes, `npm run build`  - this will cleanup the files and also check for syntax issues

**Pull request merged**
