### PR TITLE
changed brand to Herfy

### PR DESCRIPTION
**Pull request by DavidHunterJS**
I corrected the brand and change it to Herfy.

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks for the correction!  But I already did this in 37bdda1f1

**Comment by DavidHunterJS** [comment]
I see that now, thank you.

**Comment by DavidHunterJS** [comment]
Hey @bhousel, git question: What's next? 
I've done the following locally
`git fetch upstream`
`git rebase upstream/master`
`git push origin master`
Now, should I do `git brach -D add-herfy` and then do a `git push origin --delete add-herfy` ?
Is that any different from clicking the 'Delete branch' button above?
thanks

**Comment by bhousel** [comment]
> Now, should I do `git brach -D add-herfy` and then do a `git push origin --delete add-herfy` ?
> Is that any different from clicking the 'Delete branch' button above?

Sorry I missed this question before!  I _think_ these are the same..

Sometimes I go through GitHub and delete old branches - there are always a bunch hanging around.  
They don't really cause any problem.

**Pull request closed without merging**
