### PR TITLE
Add various Canadian brands

### LINKED ISSUE #1116: Research needed for: shop/car_repair|Speedy
#### :thinking: We need help deciding what to do with "shop/car_repair|Speedy"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/car_repair|Speedy` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/car_repair|Speedy`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/car_repair|Speedy`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

### LINKED ISSUE #1200: Research needed for: shop/clothes|Plato's Closet
#### :thinking: We need help deciding what to do with "shop/clothes|Plato's Closet"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/clothes|Plato's Closet` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/clothes|Plato's Closet`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/clothes|Plato's Closet`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

### PR DESCRIPTION
**Pull request by mparrault**
added: Gabriel Pizza, Freedom Mobile, The Shoe Company, and Speedy Auto Service
wikidata added for: Speedy (a French chain) and Plato's Closet
fixes #1116 and fixes #1200.

### CODE REVIEW

**Comment by Adamant36** [comment]
Everything looks good. Except it seems your using second_hand as a tag and its only been used as a key added onto the shop tag before. I think when you introduce a new tag it should be added to the taginfo.json file (someone can correct me if I'm wrong).

**Comment by bhousel** [comment]
`taginfo.json` will be regenerated whenever someone runs `npm run dist` so it isn’t necessary to edit it.

**Comment by tas50** [comment]
Thanks @mparrault

**Comment by Adamant36** [comment]
Good to know.

**Pull request merged**
