### PR TITLE
update brand "Hofer" in fuel.json

### PR DESCRIPTION
**Pull request by Luzandro**
actual brand is "Diskont", "Hofer" is just the cooperating supermarket

### CODE REVIEW

**Comment by bhousel** [comment]
thanks @Luzandro and welcome 👋 
There are some issues with this, but I'm probably just going to merge and clean up, since I do want to get releases out quickly this week.

- I'm concerned that you just created Q107803455 this morning and it doesn't have a lot of supporting information. This isn't bad necessarily, but an entry like this is at risk for deletion from the Wikidata admins. It would be great if you could add some more references about the "Hofer Diskont" brand (like if it was mentioned in a newspaper or trade publication).
- The `brand` "Diskont" should probably be "Hofer Diskont" to match the `name`, and to match the label on Q107803455
- We don't normally add `operator` tags to brands.  I don't know whether it's universally true that "Avanti" operates all of these fuel stations or whether they operate like franchises with individual operators.
- We don't add `website` tags because people can look up this information from the wikidata. Also it looks misspelled.
- other than all that, it looks fine 👍

**Comment by Luzandro** [comment]
Oh, sorry - I've started a discussion on the austrian osm forum a few months ago and apparently nobody noticed the typo until now. There are also a few more references, all in german: https://forum.openstreetmap.org/viewtopic.php?id=71945

I had hoped the official website would be reference enough to start with. As far as I understand it, NSI needs to link to a wikidata object, but the previously linked wikidata/wikipedia entries represent the supermarket and don't mention the petrol stations at all.

**Comment by Luzandro** [comment]
As for people can look up the website from wikidata - isn't that true for wikipedia as well, which is added most of the time? The first time I came across NSI, was when I was wondering why nearly all of the Eurospar supermarkets in austria referenced a danish wikipedia article
https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&tt=eurospar

Another problem, that I came across in this context was that I couldn't even add the german article to the wikidata object, as https://de.wikipedia.org/wiki/Eurospar is just a redirect to https://de.wikipedia.org/wiki/Spar#Eurospar and Spar is already linked to another wikidata object.

**Comment by bhousel** [comment]
> As for people can look up the website from wikidata - isn't that true for wikipedia as well, which is added most of the time?

Yes people ask about this a lot - the `*:wikipedia` tag doesn't really matter much and it is kind of unnecessary.  We just add it because some people like to see it and it doesn't cause any problems. (https://github.com/openstreetmap/iD/issues/8620 , #4672, #3409)

> Another problem, that I came across in this context was that I couldn't even add the german article to the wikidata object, as https://de.wikipedia.org/wiki/Eurospar is just a redirect to https://de.wikipedia.org/wiki/Spar#Eurospar and Spar is already linked to another wikidata object.

Probably the right way to do this is to replace that redirect with a new German wikipedia article about Eurospar brand.  Then you can have it linked to the Eurospar [Q12309283](https://www.wikidata.org/wiki/Q12309283)

**Pull request merged**
