### PR TITLE
Merge Hampton Inn and Hampton Inn and Suites

### LINKED ISSUE #1848: Research needed for: tourism/hotel|Hampton Inn & Suites
#### :thinking: We need help deciding what to do with "tourism/hotel|Hampton Inn & Suites"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `tourism/hotel|Hampton Inn & Suites` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `tourism/hotel|Hampton Inn & Suites`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `tourism/hotel|Hampton Inn & Suites`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

### PR DESCRIPTION
**Pull request by geospatialem**
Fixes #1848.

### CODE REVIEW

**Comment by ENT8R** [comment]
> In this case it's better to add the `nomatch` property on both objects and then just add the wikidata/wikipedia data from Hampton Inn!

Well, if these are two different brands, they should also each have their own wikidata element. If there is nothing yet, I can create a new one!

**Comment by good-praxis** [comment]
@ENT8R  I'm mostly revering to how we handle Esso (Express):
https://github.com/osmlab/name-suggestion-index/pull/1943#issuecomment-430940428

**Comment by ENT8R** [comment]
From what I see, Hampton Inn & Suites is probably just a longer name for Hampton Inn, so these two entries could maybe be merged. See also https://en.wikipedia.org/wiki/Hampton_by_Hilton and https://skift.com/2016/11/02/every-one-of-hiltons-13-hotel-brands-explained/

**Comment by geospatialem** [comment]
Good discussion, all. Hampton Inn is one of our family's go-to hotels, and we've always considered the names one in the same. I merged in the smaller count, but by no means is that the correct answer. My family and I haven't seen a difference in what is offered, I am ~95% confident they are the same.

If that holds true, and you all agree, maybe it makes sense to include "**Hampton Inn & Suites**" as the main name and ID in this case? Then merge in "**Hampton Inn**".

Either way I can edit as you all seem fit. 👍 💻

**Comment by good-praxis** [comment]
With @ENT8R research and @geospatialem experience I'll approve the changes, sorry for being a bit stingy about it! Knowing psychology it'd probably be best to do the higher count one as the main one.

I'll let someone else make this call though! Please merge this if you're happy with the outcome 😁

**Comment by bhousel** [comment]
Thanks everyone 👍

**Pull request merged**
