### PR TITLE
Add Autobusy miejskie w Toruniu

### LINKED ISSUE #8536: Add transit network "Autobusy miejskie w Toruniu"
Hello,

Could you please add transit network "Autobusy miejskie w Toruniu" into the database?
This is the bus network of Toruń, Poland organized by the City County of Toruń.
Here's the Wikidata link: https://www.wikidata.org/wiki/Q9162522

```
network=Autobusy miejskie w Toruniu
network:wikidata=Q9162522
route=bus
```

It would be great if you could add a bus stop as well:

```
network=Autobusy miejskie w Toruniu
network:wikidata=Q9162522
highway=bus_stop
```

Thank you!

### PR DESCRIPTION
**Pull request by RCRalph**
Resolves #8536

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Thank you for your first Pull Request @RCRalph 

Does this network span the whole of Poland, or a small area? If it's only a small area we can limit the suggestion zone.

Also, are you able to add a Facebook link to [Q9162522](https://www.wikidata.org/wiki/Q9162522) so that the Name Suggestion Index build script can grab a logo.

**Comment by RCRalph** [comment]
Hi, this network is city specific and only spans the Toruń city and some of its suburbs, so I suggest limiting the suggestion zone to kuyavian-pomeranian voivodeship.

I can check if there is a Facebook page that I can link to. If my search is unsuccessful, can the Logo image inside Wikidata be used?

**Comment by UKChris-osm** [comment]
Would [this zone](https://location-conflation.com/?locationSet=%7B%22include%22%3A%5B%5B18.6%2C53.0%5D%5D%7D&referrer=nsi) be suitable?

**Comment by RCRalph** [comment]
I think it should be, if it isn't we can always expand  it later can't we

**Comment by UKChris-osm** [comment]
I'll make the zone bigger now, just in case, but if you change the `locationSet` to what's shown below then I can merge your PR:
` "locationSet": {"include": [[18.6,53.0,110]]},`

**Comment by RCRalph** [comment]
Done, thanks for the quick response

**Review by UKChris-osm — APPROVED** [review]

**Comment by UKChris-osm** [comment]
Thank you for your first successful PR @RCRalph 👍

**Pull request merged**
