### PR TITLE
Added East of Chicago Pizza, updated Gino's Pizza & Spaghetti House

### PR DESCRIPTION
**Pull request by pkoby**
Gino's Pizza & Spaghetti House is consistently worded on all signs and logos that I can find, including the "& Spaghetti House" that was previously omitted from tags.

I added wikidata tags for EOCpizza for Twitter, FB, and website, so logo fetch should work.

### CODE REVIEW

**Comment by Adamant36** [comment]
It seems like "Gino's Pizza" is tagged a lot more then "Gino's Pizza & Spaghetti House." My recommendation is to go with official_name=Gino's Pizza & Spaghetti House instead of using the longer name in the name field if you want it to be included. Since it's always good to stay with preexisting tagging conventions and to use the shorter name when possible.

**Comment by pkoby** [comment]
Fair point. Changed that (and maybe made some noobie Github mistakes...).

**Comment by Adamant36** [comment]
Still needs to be changed for the brand and amenity tags though.

**Comment by Adamant36** [comment]
Thanks. Looks fine now 👍

**Pull request merged**
