### PR TITLE
Update clothes.json

### PR DESCRIPTION
**Pull request by arnowrld**
Please note that the brands I've gotten rid of have become e-commerce & closed their stores. Also, I'm currently moving Burlington to department stores.

### CODE REVIEW

**Comment by arch0345** [comment]
It looks like some of the defunct brands removed are still in OSM, so to prevent these from being added again with the build script I would add this to the exclude named list as "^(brand name)$"

**Comment by bhousel** [comment]
> It looks like some of the defunct brands removed are still in OSM, so to prevent these from being added again with the build script I would add this to the exclude named list as "^(brand name)$" found at the top of the file

I think after #5758 that we should leave defunct brands in the index for a little while, as it can be kind of surprising if you are expecting a preset for one and it doesn't show up in iD.

**Comment by tas50** [comment]
I'd also recommend creating a Maproullete challenge to cleanup any dead brands. Otherwise, they'll stick around for the next decade.

**Comment by UKChris-osm** [comment]
> I think after #5758 that we should leave defunct brands in the index for a little while, as it can be kind of surprising if you are expecting a preset for one and it doesn't show up in iD.

Could we add something on this end that highlights a brand as no longer having physical locations within our core data, so we could also highlight it on the web site - and in turn on the iD side which highlights any matches as "_this brand no longer has outlets / branches_"?

no-longer-trade

**Comment by bhousel** [comment]
I ended up restoring  Avenue, Catherines, Dress Barn, and Justice because `npm run build` put them back, because they still exist frequently in OSM.

**Pull request merged**
