### PR TITLE
Updates on Poland (bank, cinema, lottery)

### PR DESCRIPTION
**Pull request by kubahaha**
Hello
I created few new brands in Poland and completed tags in few other country-specific tags. Hope everything is ok.
This is my first commit to this project.

### CODE REVIEW

**Review by bhousel — CHANGES_REQUESTED** [review]
Sorry I can't review this fully right now, but I will get to it later next week:

At quick glance, our index doesn't currently include tags like 
- `payment:*` (these tags are better suited to in-person survey), 
- non-prefixed `wikidata`/`wikipedia` (these tags are for if the specific branch is notable, not the brand as a whole),
- not sure that `operator` belongs here (meaning of this tag in OSM is for the entity operating the branch, not for the parent company).

**Comment by kubahaha** [comment]
Thank you for yor comment. I just commited with changes you requested.

**Comment by LaoshuBaby** [comment]
Thanks for @kubahaha for maintanced those existing data!  👍

Welcome to this repository!

**Comment by bhousel** [comment]
It also looks like something is wrong with the wikidata for "Lotto" - but this seems to be a mistake on the Wikidata side.
https://www.wikidata.org/wiki/Q2619032

That page seems to be a mix of links for the concept of a lottery game, and also the polish lottery store.
I think it might be better to leave it unlinked in NSI for now until the Wikidata is sorted out..

Can someone with more Wikidata experience help?

**Comment by LaoshuBaby** [comment]
Ahh^!Sorry! This mistake I haven't found! I only look for the json structure and kv tag, not searched the wikidata!
(/(ㄒoㄒ)/~~
I will try to fix to patch for my wrong merge! 
○|￣|_

**Comment by bhousel** [comment]
> Ahh^!Sorry! This mistake I haven't found! I only look for the json structure and kv tag, not searched the wikidata!
> I will try to fix to patch for my wrong merge!

No worries! I just fixed it..
I don't always check all the wikidata, but sometimes it is good to..

I installed this [search extension in Chrome](https://chrome.google.com/webstore/detail/wikidata-search/ingjkjibhnkhomomlmlabndfmiaejkpn?hl=en) so I can just type <kbd>tab</kbd><kbd>w</kbd><kbd>d</kbd> and paste a QID to look it up quickly.

**Comment by kubahaha** [comment]
Thanks, I just copied Wikidata link from Wikipedia page. I opened discussion topic at polish Wikipedia page, so theirs community can spot it (and hopefully I will get notification to update NSI).

**Pull request merged**
