### PR TITLE
Update trade.json Add Tradelink

### PR DESCRIPTION
**Pull request by Guerme**
Adding Tradelink - https://tradelink.com.au/

### CODE REVIEW

**Comment by kjonosm** [comment]
@Guerme Is this really a DIY store and not a `shop=kitchen`, `shop=bathroom_furnishing` or `shop=furniture`? You can check OSM wiki for reference.

**Comment by Guerme** [comment]
@kjonosm - It sells fixtures for bathrooms and kitchens, so I don't think it can fit in one of those categories alone.  It also doesn't sell furniture, only appliances and fixtures, so not sure it fits in furniture.  So due to this, it seemed to me like it was more related to Lowe's/Home Depot, as it sells a mix of appliances/fixtures for both bathroom and kitchen.  Or can I add to both kitchen and bathroom furnishing?

**Comment by kjonosm** [comment]
Current tagging is quite diverse. In my opinion it it best described as [`shop=trade`](https://wiki.openstreetmap.org/wiki/Tag:shop=trade) + `trade=plumbing`. On their website they call themselves 

> Australia’s oldest plumbing merchants

**Comment by Guerme** [comment]
@kjonosm - Thanks for the suggestion.  Moved to trade.json and added trade=plumbing.

**Pull request merged**
