### PR TITLE
Update of location for charging station Eldrive

### PR DESCRIPTION
**Pull request by neau**

### CODE REVIEW

**Comment by Dimitar5555** [comment]
Is Eldrive a Bulgarian company? If it is, does it directly operate the stations in Romania and Lithuania or it has subsidiaries there?

**Comment by kjonosm** [comment]
Anyway, `displayName` should somehow correspond with the actual `operator` or `brand` name.

**Comment by Snowysauce** [comment]
The proposed locationSet appears to be correct per https://eldrive.eu/#charging__station. The company has individual offices in each country according to the contact info at the bottom of the page, but I don't know if they're just offices or subsidiary headquarters. I've refrained from merging this because the brand uses English for branding in some capacity, and so it should have at minimum an `operator:en` tag (along with the relevant local language tag to specify what language the default name is in).

**Comment by Snowysauce** [comment]
This PR seems to have been abandoned, so I removed the questionable operator name change while merging in the locationSet change.

**Pull request merged**
