### PR TITLE
To the post_office module added chilexpress with with wikidata and wi…

### PR DESCRIPTION
**Pull request by Nuthi-Sriram**
To the post_office module added chilexpress with with wikidata and wikipedia and also added correo OCA
Added Animal_boarding with brand:wikipedia

### CODE REVIEW

**Comment by Adamant36** [comment]
Hi there. It seems that the Wikipedia article for Telex-Chile is a diffunct brand that is a different company then the entry. Also with the pet hotels from what I've seen we don't usually use the Wikipedia tag to link to sections of articles. So it would probably be better to just create a new Wikidata entry for it instead. Although, someone else might know differently.

**Comment by Nuthi-Sriram** [comment]
Ohh I get it

**Comment by Nuthi-Sriram** [comment]
> Hi there. It seems that the Wikipedia article for Telex-Chile is a diffunct brand that is a different company then the entry. Also with the pet hotels from what I've seen we don't usually use the Wikipedia tag to link to sections of articles. So it would probably be better to just create a new Wikidata entry for it instead. Although, someone else might know differently.

I have made some changes I have removed the two erroneous code which I had written

**Comment by bhousel** [comment]
Thanks for the quick fix @Nuthi-Sriram and welcome! 👋

**Pull request merged**
