### PR TITLE
Update Taiwan bank information

### PR DESCRIPTION
**Pull request by Supaplextw**
add name:zh, name:nan, name:hak, redirect Sinpac Bank Wikidata link to the bank branch Wikidata item

### CODE REVIEW

**Comment by Identitaet** [comment]
Does the TL stand for transliterated here and the HJ for hanji ?

Looks good as far as I can tell

**Comment by Supaplextw** [comment]
@Identitaet It is the [Tâi-lô system](https://en.wikipedia.org/wiki/T%C3%A2i-u%C3%A2n_L%C3%B4-m%C3%A1-j%C4%AB_Phing-im_Hong-%C3%A0n) to write Taiwanese Banlamgu. Not just transliteration.

**Comment by Supaplextw** [comment]
and yes HJ is for Hanji.

**Comment by Identitaet** [comment]
okay then it looks good
you probably know more about these language tags than me 😆

welcome to the Name suggestion index also

**Comment by Supaplextw** [comment]
I'll add more chain stores of Taiwan to the name-suggestion-index. There are still many chain stores missing in the NSI.

**Pull request merged**
