### PR TITLE
Add Kitchen Origin and Renge Shokudo

### PR DESCRIPTION
**Pull request by sguinetti**
This pull request adds [other brands](https://pkg.navitime.co.jp/toshu/) from Origin Toshu.

### CODE REVIEW

**Comment by ArenaL5** [comment]
Your commit is alright, but these barely have any presence on Wikidata... I'd suggest to add more data to [ensure they're not deleted](https://www.wikidata.org/wiki/Wikidata:Notability). Creating a Wikipedia article is another option, but that takes much more time.

By the way, thank you for your contributions. I merged your other two PRs.

**Comment by sguinetti** [comment]
Yes. But the point is in Japanese Wikipedia, those articles redirect to the company. So, the idea of creating these entries is to separate the logo from the parent product. I have added so many details and social networks.

**Comment by ArenaL5** [comment]
We can actually add redirects now? That's great news. I had problems with that in the past.

If Wikidata is okay with that, I've no problem with this. Merging now.

**Comment by sguinetti** [comment]
Thank for your reply.

**Pull request merged**
