### PR TITLE
added Greenhalgh's & Neon Gift #4290

### PR DESCRIPTION
**Pull request by cr33dx**

### CODE REVIEW

**Review by bhousel — CHANGES_REQUESTED** [review]
Welcome @cr33dx 👋 
Can you move the Greenhalgh's entry from the `amenity/cafe.json` file to the `shop/bakery.json` file?  Thanks!

**Review by bhousel — APPROVED** [review]

**Comment by bhousel** [comment]
Thanks for the quick fix and welcome 👋

**Comment by cr33dx** [comment]
@bhousel can you add hacktoberfest-accepted label to this PR please?

**Comment by UKChris-osm** [comment]
@cr33dx the label shouldn't be needed as this project has the "hacktoberfest" label on the front page :)

**Pull request merged**
