### PR TITLE
Add Bowling and Hobby brands

### PR DESCRIPTION
**Pull request by sguinetti**
This pull request adds other japanese brands about Bowling and Hobby.

### CODE REVIEW

**Comment by Adamant36** [comment]
Its weird the none Japanese Wikipedia articles for Pokemon Center are for the in the game Pokemon centers 🤣

**Comment by SilentSpike** [comment]
Yeah the brand here for Pokemon centre stores should be using a separate Wikidata item than the one for the fictional stores in-game.

**Comment by sguinetti** [comment]
Ok. I fixed Wikidata of Pokémon Center.

**Comment by Adamant36** [comment]
Thanks.

**Pull request merged**
