### PR TITLE
ADD other Estonian supermarket brands

### PR DESCRIPTION
**Pull request by druzanov**

### CODE REVIEW

**Comment by Adamant36** [comment]
Hello and welcome to the project 👋 Everything looks fine. Except, how come you didn't add the Wikipedia article for Coop Eesti?

**Comment by druzanov** [comment]
Hello. There is none in English, only in Estonian. Could add that and then recommit.

**Comment by Adamant36** [comment]
Oh. That's fine. It doesnt have to bw in English. Its actually better if its thw Wikipedia article in whatever language is spoken where the brand is located. So if you want to add the Estonian article and recommit it that would be great.

**Comment by Adamant36** [comment]
Thanks 👍

**Pull request merged**
