### PR TITLE
Entries for Cinnabon and Old Time Pottery

### PR DESCRIPTION
**Pull request by mparrault**
Added entry for Cinnabon according to [#2275]( https://github.com/osmlab/name-suggestion-index/issues/2275) and Old Time Pottery according to [#2219](https://github.com/osmlab/name-suggestion-index/issues/2219).

### CODE REVIEW

**Comment by Adamant36** [comment]
Hi there. It doesn't seem as though cinnamon_roll is an official cuisine tag or even has any uses. So it might be worth changing to something more accepted and in use. 

Also, if you put "closes"  before the issue number it will automatically close the issue the PR is attached to when its merged. Then someone won't have to go through and find it later to close it. 

Thanks

**Comment by mparrault** [comment]
I've changed the cuisine type to cuisine=dessert.  Thanks for the tip on closing.  Closes #2275 and closes #2219.

**Comment by bhousel** [comment]
Thanks @mparrault 👍

**Comment by Adamant36** [comment]
@bhousel, since this was merged is brand:website a tag that can be added to entries now?

**Comment by bhousel** [comment]
I think `brand:website` is not really important, but if people want to add it I don’t care. 

It’s probably better to not add a bunch of extra tags that hold data that can be fetched from the Wikidata record.

**Pull request merged**
