### PR TITLE
Add HERC'S Nutrition to data/brands/shop/nutrition_supplements

### PR DESCRIPTION
**Pull request by alefuedev**
HERC'S Nutrition to data/brands/shop/nutrition_supplements
{
      "displayName": "HERC'S NUTRITION",
      "id": "",
      "locationSet": { "include": ["ca"] },
      "tags": {
        "brand": "HERC'S NUTRITION",
        "name": "HERC'S NUTRITION",
        "shop": "nutrition_supplements"
      }
    },

### CODE REVIEW

**Review by bhousel — CHANGES_REQUESTED** [review]
Thanks @alefuedev - I can see this is a brand and looks like you added it to the right place 👍 
Are you ok with changing the strings to say "HERC'S Nutrition" to match how they talk about themselves in their website copy?  https://hercs.com/origin-of-hercs-our-story/

**Review by bhousel — APPROVED** [review]

**Comment by bhousel** [comment]
Thanks @alefuedev and welcome to the project 👋

**Comment by alefuedev** [comment]
Thank you! I don't have to much experience working with github. I hope I did the pull request correctly. :)

**Comment by bhousel** [comment]
> Thank you! I don't have to much experience working with github. I hope I did the pull request correctly. :)

Yes your pull request was perfect 👍 
This project is great for beginners with GitHub and Open Source.  We mostly just need a lot of volunteers to look up information for us and help edit the config files.  http://nsi.guide contains the complete list of what we've collected so far.

**Pull request merged**
