### PR TITLE
add Alvo supermarket

### PR DESCRIPTION
**Pull request by ferdinand0101**
Note: logo is all lowercase should that be changed ?
I used uppercase because issue and wiki used it aswell.
#3507

### CODE REVIEW

**Comment by thibaultmol** [comment]
Actually, seems like they're also active in Luxembourg, so might want to add that country code as well

**Comment by ferdinand0101** [comment]
okay I added that

**Comment by bhousel** [comment]
Thanks @ferdinand0101  👍

**Comment by bhousel** [comment]
A cool GitHub tip for future PRs - you can include some text like "closes #3507" in your commit message or pull request, and GitHub will close the issue for us automatically 💪
 
https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Pull request merged**
