### PR TITLE
Create substation.json

### PR DESCRIPTION
**Pull request by kjonosm**
Add some location sets
Add wikidata for "TINETZ-Tiroler Netze GmbH", "Thüga AG", "Terna" and "Tensio"
"TINETZ-Stromnetz Tirol AG" has been renamed to "TINETZ-Tiroler Netze GmbH"

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
Wait
In https://github.com/osmlab/name-suggestion-index/commit/eaac4f87205584034152c1acb43e38aa1ccbef5d @bhousel move "Evergy" to first and you moved it to late.

Maybe we faced with problem in #4850 again.

**Comment by LaoshuBaby** [comment]
And id generator have conflict again in your 2 commit
图片
图片

**Comment by kjonosm** [comment]
this happens whenever a file is edited by two people at the same time. I get notified when this occurs so I hold off merging my changes and create a pull request like here instead. what's the best way to merge changes in this pull request without overwriting what has been edited in the meantime?

**Comment by bhousel** [comment]
> this happens whenever a file is edited by two people at the same time. I get notified when this occurs so I hold off merging my changes and create a pull request like here instead. what's the best way to merge changes in this pull request without overwriting what has been edited in the meantime?

I don't worry too much about the sorting or id generation because these things eventually should settle when someone runs `npm run build`.  

I thought that I wrote the code in a way that it should work the same no matter who runs the script, but the issue we saw on https://github.com/osmlab/name-suggestion-index/pull/5261#pullrequestreview-735565530 is similar and makes me think I'm missing something.   

For me:
Linking the [node internationalization docs](https://nodejs.org/api/intl.html#intl_disable_all_internationalization_features_none) here in case I need to look at them later.
May need to do something [like this](https://stackoverflow.com/questions/35126247/how-to-see-what-locales-a-given-node-js-version-supports-and-how-to-enable-missi) to make sure the environment has the locales we expect?

@kjonosm can you let me know:
- when you do changes like this that touch the ids or the sorting, you are running `npm run build` right?
- what version of node you have? 
`node --version` should show a 12, 14, or 16
- make sure to do a `npm install` to get the latest project dependencies.  Do you have a recent `diacritics` depdency?  
`npm ls diacritics` should show `diacritics@1.3.0`

**Comment by LaoshuBaby** [comment]
I also meet with id change problem (in https://github.com/osmlab/name-suggestion-index/commit/8e139178ec593c643c87f3f42cb2648c42af9be6)
@bhousel 
-----
The environment of me:
图片
图片

**Comment by kjonosm** [comment]
> when you do changes like this that touch the ids or the sorting, you are running npm run build right?

🤷 I guess not. I do my edits in the online editor, check my changes in preview mode and hit `Commit changes`...

Bildschirmfoto 2021-08-29 um 10 46 15

**Comment by bhousel** [comment]
@LaoshuBaby :
> I also meet with id change problem (in [8e13917](https://github.com/osmlab/name-suggestion-index/commit/8e139178ec593c643c87f3f42cb2648c42af9be6))

Hmm that's odd.  If 'diacritics' is turning up empty, the id generation will probably not work.  1. are you running this command in the folder that contains the name-suggestion-index project?  It needs to look down into `node_modules/` folder to see what is installed.  2. If you are in the name-suggestion-index project, does running `npm install` fix it?  It's good to do this sometimes..

@kjonosm :
>🤷 I guess not. I do my edits in the online editor, check my changes in preview mode and hit Commit changes...

Ok this is good! I'm more worried if the `npm run build` script does different things in different environments.  If you're not running `npm run build` that's ok.  The sorting and ids will settle on their own eventually (if the script does its job).

**Pull request merged**
