### PR TITLE
hotel

### PR DESCRIPTION
**Pull request by danielatellez**

### CODE REVIEW

**Comment by tas50** [comment]
It looks like this wikidata / wikipedia data is for a single hotel building and not the chain.

**Comment by Adamant36** [comment]
Is it even a chain? They are spread all over Europe and seems like all the Hotel Belvederes in internet searches are separate entities. Belvedere means summerhouse. So maybe it's a generic.

**Comment by bhousel** [comment]
Ah yeah, it doesn't look like a brand.. @danielatellez can you remove this entry from `hotel.json`?

It looks like it should already be filtered by this line:
https://github.com/osmlab/name-suggestion-index/blob/cdc12ad632d805d887b929ccf94ff2e038ac97e8/config/filters.json#L99

So it shouldn't return back into the index if we detect them again.

**Comment by danielatellez** [comment]
@bhousel this had been removed.

**Pull request merged**
