### PR TITLE
Adding BG&E and SMECO to power operators

### PR DESCRIPTION
**Pull request by Eric-Sparks**
Adding Baltimore Gas and Electric and Southern Maryland Electric Cooperative to both minor_line and pole operators.

### CODE REVIEW

**Comment by Eric-Sparks** [comment]
SMECO needs an ID but I'm not sure how to create one (and couldn't find documentation around creating one).

**Comment by arch0345** [comment]
Don't worry about adding ids, we run a script that automatically adds these.

**Comment by arch0345** [comment]
I noticed you added `man_made=utility_pole` and the appropriate `utility=*` tags to the new entries in power/pole. However, the wiki page for this new tag suggests to use only `power=pole` for power poles (https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dutility_pole). It does show that `utility=power` can still be used for `power=pole` so I would just remove `man_made=utility_pole` from these

**Comment by Eric-Sparks** [comment]
> It does show that `utility=power` can still be used for `power=pole` so I would just remove `man_made=utility_pole` from these

Okay, I've removed that tag from the patch.

**Pull request merged**
