### PR TITLE
Added London Borough of Newham and PCM

### PR DESCRIPTION
**Pull request by rskedgell**

### CODE REVIEW

**Comment by rskedgell** [comment]
Removing London Borough of Newham for now, as GB-NWM needs to be added.

**Comment by UKChris-osm** [comment]
Hi @rskedgell - I have added the London Borough of Newham via [f671aea](https://github.com/osmlab/name-suggestion-index/commit/f671aea899b11aa39a4b325e19f0af11286f28ef) so you're welcome to reopen this PR.

You can also use the non-ISO [gb-lon.geojson](https://github.com/osmlab/name-suggestion-index/blob/main/features/gb/gb-lon.geojson) in future to cover London if the specific area you are targeting isn't available.

**Comment by rskedgell** [comment]
On 10/12/2022 22:51, UKChris-osm wrote:
> Hi @rskedgell <https://github.com/rskedgell> - I have added the London 
> Borough of Newham via f671aea 
> <https://github.com/osmlab/name-suggestion-index/commit/f671aea899b11aa39a4b325e19f0af11286f28ef> so you're welcome to reopen this PR.

Thanks!

I was going to add it from the ONS LAD21 boundaries, but hadn't had time 
to work out how much to simplify it in order to get a similar sized 
geojson file to the others in the repository.

Does a boundary from an ONS or OS open data source need any extra 
attribution in the NSI repository? I know they're covered for OSM itself 
and have the appropriate attributions in the OSM Wiki.

**Comment by UKChris-osm** [comment]
Is the ONS LAD21 the government data set that's made available under the [Open Government Licence](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/)?

We don't really have a way of adding attribution directly in the geojson files, but within the [gb folder](https://github.com/osmlab/name-suggestion-index/tree/main/features/gb) I have added a README file that could hold the attribution in there.

**Comment by rskedgell** [comment]
I've had a go at adding the adjacent borough, gb-wft.geojson, with attribution details in the pull request #7527 - if it's accepted, perhaps I should add that to the README file?

**Pull request closed without merging**
