### PR TITLE
Add 4 bank in valencian community

### PR DESCRIPTION
**Pull request by paunofu**
Added Caixa Ontinyent, Caixa Callosa, Caixa Altea and Caixa Popular

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
Community bank? It's a pity that I couldn't understand the introduction in Spanish or Catalan, what I concerned is will they have enough branch banks? Because I feel that community banks serve a small region and may does not have sufficient notability.

**Comment by paunofu** [comment]
This PR comes from a previous PR that I mess it up a little #7557.

Valencian Community is the name of the region, is the same as saying Texas, Ohio,...

Caixa Popular has 74 offices and ATMs
Caixa Altea has offices 11 and ATMs
Caixa Callosa has 3 offices and ATMs
Caixa Ontinyent has 46 offices and ATMs

The number of ATMs could be higher because each office has at least 1 office but could have more.

**Comment by Adamant36** [comment]
I'm a little worried about using match-names to turns of banks called "Caja" into "Caixa" since we already have a bunch of Caja banks in the database and I'm not really sure how it will effect them or really what the difference is. From what I can tell, "Caja" is separate from "Caixa." So they shouldn't be treated as matches, but then again, 🤷‍♂️ @LaoshuBaby or anyone else have an opinion on this or know if it might screw things up somehow down the line?

**Comment by paunofu** [comment]
Oh, okay, now I think why are you worried. Caixa is in Catalan or Galician and Caja is in Spanish. The intention of this PR is add new brands to nsi and correct that people that put the name in Spanish despite of the name is not in Spanish. I thought that matchName corrects the name with the whole entry "Caja Callosa", "Caja Popular",... and not only "Caja".

**Pull request merged**
