### PR TITLE
Remove wrong Dekra declaration

### PR DESCRIPTION
**Pull request by bmillemathias**
... and correct the right one

### CODE REVIEW

**Comment by Adamant36** [comment]
Seems they have both vehicle inspection places and car repair shops. So it might be worth worth keeping both entries somehow. I'm not going to speculate on the best way to do it though.

**Comment by matkoniecz** [comment]
> Seems they have both vehicle inspection places and car repair shops.

Separate ones? Or is it a single object that fulfills both functions?

**Comment by bhousel** [comment]
AFAICT from their wikipedia page, they just do vehicle inspection services, so this seems ok.

**Comment by Adamant36** [comment]
On their website it says they do oil changes and sell basic items like windshield wipers and light bulbs. I don't know if that would count as "car repair" per say. I guess they do more car repair related stuff with their other brands Autocontrol and Norisko.

**Pull request merged**
