### PR TITLE
treat Orlik as not a brand

### PR DESCRIPTION
**Pull request by matkoniecz**
names were result of https://pl.wikipedia.org/wiki/Orlik_2012

### CODE REVIEW

**Review by LaoshuBaby — APPROVED** [review]
Agree. (After consulting en Wikipedia)

If the infrastructure built by the government for public and social welfare purposes, and not a commercial activity, it is okay to remove the brand tag. There are also many facilities like this purpose in China, where I am living in.

However, for the purpose of better identification, it is hoped that editors in your place can pay attention to the standard name when editing. And keep the tag ```"leisure": "sports_centre",```,  which reveal it is stadium

**Comment by LaoshuBaby** [comment]
But I'm not sure whether to merge it because I had made too much mistake before, so just wait for bhousel to finally review this PR, thanks for your contribution for NSI community!

**Comment by matkoniecz** [comment]
> And keep the tag "leisure": "sports_centre",, which reveal it is stadium

Note that stadium should be tagged with https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dstadium

**Comment by LaoshuBaby** [comment]
> 
> 
> Agree. (After consulting en Wikipedia)
> 
> If the infrastructure built by the government for public and social welfare purposes, and not a commercial activity, it is okay to remove the brand tag. There are also many facilities like this purpose in China, where I am living in.
> 
> However, for the purpose of better identification, it is hoped that editors in your place can pay attention to the standard name when editing. And keep the tag `"leisure": "sports_centre",`, which reveal it is stadium



> 
> 
> > And keep the tag "leisure": "sports_centre",, which reveal it is stadium
> 
> Note that stadium should be tagged with https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dstadium

Sorry！ Another mistake！ I means it is a kind of community sport area, statium is a larger landuse.

Yes, this ```orilk``` is more like a sport_centre! wiki.openstreetmap.org/wiki/Tag:leisure%3Dsports_centre



so sorry for my unexact words! This kind of leisure is ```leisure=sports_centre``` 

跪了，这是我的锅

**Comment by UKChris-osm** [comment]
So is "_Orlik_" the name of an initiative to build leisure facilities, rather than a brand / organisation?

**Comment by LaoshuBaby** [comment]
Yes,I think things like this. 👌




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月11日(星期天) 晚上9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [osmlab/name-suggestion-index] treat Orlik as not a brand (#5018)





 
So is "Orlik" the name of an initiative to build leisure facilities, rather than a brand / organisation?
 
&mdash;

**Comment by UKChris-osm** [comment]
Thank you @matkoniecz and @LaoshuBaby 👍

**Comment by matkoniecz** [comment]
> So is "Orlik" the name of an initiative to build leisure facilities, rather than a brand / organisation than runs any?

Yes, exactly.

**Pull request merged**
