### PR TITLE
ADD KK SUPER MART

### PR DESCRIPTION
**Pull request by MASangys**

### CODE REVIEW

**Comment by matkoniecz** [comment]
Note https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md#adding-references-to-wikidata part - without either Wikipedia article link or independent references Wikidata entries will be deleted.

**Comment by MASangys** [comment]
I had created a page for this mart
https://ms.wikipedia.org/wiki/KK_Super_Mart

**Comment by MASangys** [comment]
and then some of the kk super mart was tagged as name Kk or KK mart , can validator detect it?

**Comment by MASangys** [comment]
e.g. 
https://www.openstreetmap.org/search?query=kk%20malaysia#map=19/3.13305/101.71147

**Comment by MASangys** [comment]
https://www.openstreetmap.org/search?query=kk%20mart%20malaysia#map=19/3.12737/101.67019

**Comment by MASangys** [comment]
and this also https://www.openstreetmap.org/search?query=kk%20supermart%20malaysia#map=19/3.13982/101.62823

**Comment by bhousel** [comment]
> and then some of the kk super mart was tagged as name Kk or KK mart , can validator detect it?

You would need to add `matchNames` for the alternate spellings if you want the validator to suggest a tag correction.  

You can also use tags like `alt_name` or `short_name` if these names are somewhat official.  In other words, if everyone locally knows that "KK" means "KK Super Mart" or the business puts "KK" on their signage, it's probably ok to put this in the `short_name` tag.

**Comment by MASangys** [comment]
No proble, you can just do it. I agree

**Comment by bhousel** [comment]
> No proble, you can just do it. I agree

I'm not familiar with this brand, so I'm not really the right person to make that decision.

**Comment by MASangys** [comment]
What you say are logically correct.
First:Match anme for this brand need to be add
Second:Short name for KK tag.

**Comment by Adamant36** [comment]
> without either Wikipedia article link or independent references Wikidata entries will be deleted.

From what I understand we can use the NSI identifier also now that it has been accepted. Although, I don't think it should be a full replacement to good references or a Wikipedia article link if either are also available.

**Comment by bhousel** [comment]
> What you say are logically correct.
> First:Match anme for this brand need to be add
> Second:Short name for KK tag.

I ended up making these changes in 272e5233 and merging.. Thanks for the PR @MASangys 👍

**Pull request merged**
