### PR TITLE
home timber and hardware australia

### PR DESCRIPTION
**Pull request by andrewharvey**
see also https://github.com/openstreetmap/iD/issues/6513 where iD suggested the wrong brand tags

### CODE REVIEW

**Comment by Adamant36** [comment]
You don't need a match for "home hardware" if it's already used as the alt name. The name index accounts for capitalizing and searches alt name for matches now.

**Comment by andrewharvey** [comment]
> You don't need a match for "home hardware" if it's already used as the alt name. The name index accounts for capitalizing and searches alt name for matches now.

Sorry you're right.

> I'm kind of wondering about the usage of "home" to. It seems a little to general to me. Even if the business goes by that somewhere. There's a bunch of places named "home" all over the world.

According to Wikipedia "Home" is a common name, and based on my experience Home is a valid short name.

_Home Timber & Hardware (commonly known as "Home" or "Home Hardware")_

I'm wondering if it matter if there are other places also named Home? Upstream consumers of name-suggestion-index know that this should only match in `au`, and a user should still review any tag suggestions to make sure they are correct to add to the feature.

**Comment by matkoniecz** [comment]
Looking at http://overpass-turbo.eu/s/JPR and its Wikipedia page it seems that `shop=hardware` may also match.

Is `shop=doityourself` better for all its locations?

**Comment by bhousel** [comment]
Looks good thanks @andrewharvey 👍

**Comment by andrewharvey** [comment]
> Looking at http://overpass-turbo.eu/s/JPR and its Wikipedia page it seems that shop=hardware may also match.
> 
> Is shop=doityourself better for all its locations?

I did review the wiki page for shop=hardware and shop=doityourself. The distinction is blury, but from my understanding hardware was for small shops selling screws, nails etc. whereas doityourself was for larger shops selling a wider range of products, for the kitchen, bathroom, etc.

**Comment by Adamant36** [comment]
I agree the difference is blurry. In the description section for shop=hardware it says its for a "shop which sells timber, tools and other building products." That sounds more like a diy store to me. The specific mention of timber is what makes me thing this should be tagged as a hardware store. Either that or the related wiki pages should be updated to be more clear about what exactly the tags apply to.

**Pull request merged**
