### PR TITLE
Aboriginal & Torres Strait Islander flags

### PR DESCRIPTION
**Pull request by codeinabox**
Australian Aboriginal & Torres Strait Islander flags

https://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines#Australian_Flags

### CODE REVIEW

**Comment by tastrax** [comment]
I think this follows the consensus in the talk-au mailing list - many thanks

**Comment by codeinabox** [comment]
> I think this follows the consensus in the talk-au mailing list - many thanks

Thank you for checking, I've marked this as ready for review

**Comment by codeinabox** [comment]
> I think this follows the consensus in the talk-au mailing list - many thanks

@tastrax was the consensus to use `flag:type=national` or `flag:type=indigenous`? I noticed the wiki still says the former

**Comment by tastrax** [comment]
flag:type=indigenous is the preferred as they are not strictly 'National' flags but 'flags of significance'

**Comment by arch0345** [comment]
LGTM, thanks @codeinabox

**Pull request merged**
