### PR TITLE
Oxford Learning

### PR DESCRIPTION
**Pull request by andrewpmk**
Oxford Learning

### CODE REVIEW

**Comment by AntiCompositeNumber** [comment]
https://www.wikidata.org/wiki/Q124034787 was speedily deleted as not meeting [Wikidata notability](https://www.wikidata.org/wiki/Wikidata:Notability). Please see https://github.com/osmlab/name-suggestion-index/pull/8475#issuecomment-1665543134 and https://www.wikidata.org/wiki/Wikidata:Guide_to_requests_for_undeletion for more information.

**Comment by andrewpmk** [comment]
Looks like Wikidata won't accept this entry because Wikipedia thinks it is not notable. https://en.wikipedia.org/wiki/Oxford_Learning

https://www.oxfordlearning.com/locations/ lists over 100 locations I think this is notable.

**Comment by bhousel** [comment]
> https://www.oxfordlearning.com/locations/ lists over 100 locations I think this is notable. 

Thanks, I agree, I've requested an undeletion..

**Comment by AntiCompositeNumber** [comment]
[Undeletion request](https://www.wikidata.org/wiki/Wikidata:Administrators%27_noticeboard/Archive/2024/05#h-Request_for_undeletion_of_Oxford_Learning_Q124034787-20240525170500) was archived after one administrator supported undeletion but did not undelete. Further follow-up is required.

**Pull request merged**
