### PR TITLE
SFR : Added infos

### PR DESCRIPTION
**Pull request by Lulucmy**
Added logo, wikidata, wikipedia and corrected name (different of brand)

### CODE REVIEW

**Comment by Adamant36** [comment]
I don't know if you need to add the logo that way. It does it through running the script anyway. Also, I think the brand and the name has to be the same. Usually if there's a short and long form of the name, the short form in used more. So its used in the name/brand fields and the long form is either added as a match or with the tag official_name. In this case name=SFR has 261 uses, while name=Espace SFR only 55. So SFR is clearly the preferred name and should be in the name/brand tags. Whereas, its fine to use the official_name tag for Espace SFR.

**Comment by Lulucmy** [comment]
It's not the case here : "Espace SFR" is the name of the shop, the brand name is just "SFR", like "Apple"/"Apple Store". I'll remove the picture if needed

**Comment by Adamant36** [comment]
> Espace SFR

Not all of them say Espace SFR. Some just say SFR. The general rule in cases like this is that we split the difference and go with the shorter name because it shows up better on the map and make use official_name if necessary, because while as all Espace SFR's have "SFR in their names, no SFR's have "Espace" As I said, SFR is used exponentially more anyway. Trust me, this comes up a lot and that's how we do it. It just came twice up yesterday a matter of fact. 

images

images (1)

images (2)

sfr-corporate_4079556

For stores that do have "Espace" in their name its not even featured predominantly. For instance, in this one you can hardly even see it on the right. 

download

Pretty much the same with this one

raw

**Comment by Adamant36** [comment]
Apple stores aren't a good comparison because they don't even have a brand name in the front of their shops. Its just a picture of an apple. We always favor what the store front says. As its ground truth verifiable. 

26186-36845-applestore-thepier-l

**Comment by Lulucmy** [comment]
> > Espace SFR
> 
> Not all of them say Espace SFR. Some just say SFR. The general rule in cases like this is that we split the difference and go with the shorter name because it shows up better on the map and make use official_name if necessary, because while as all Espace SFR's have "SFR in their names, no SFR's have "Espace" As I said, SFR is used exponentially more anyway. Trust me, this comes up a lot and that's how we do it. It just came twice up yesterday a matter of fact.
> 
> images
> 
> images (1)
> 
> images (2)
> 
> sfr-corporate_4079556
> 
> For stores that do have "Espace" in their name its not even featured predominantly. For instance, in this one you can hardly even see it on the right.
> 
> download
> 
> Pretty much the same with this one
> 
> raw

Didn't know all these rules, thanks 😉

**Comment by Adamant36** [comment]
> Didn't know all these rules, thanks

Yep.

**Comment by bhousel** [comment]
I added "match": ["shop/mobile_phone|Espace SFR"],  to the existing SFR entry, and merged

**Pull request merged**
