### PR TITLE
add Ecoshop

### PR DESCRIPTION
**Pull request by MASangys**

### CODE REVIEW

**Comment by matkoniecz** [comment]
Have you considered `shop=variety_store`? https://wiki.openstreetmap.org/wiki/Tag:shop%3Dvariety_store

Based on their website it seems to me that it would be a better match ( http://welcome.eco-shop.com.my/ ).

**Comment by MASangys** [comment]
Ohh, if like that you just put it at variety store. Didnt know that

**Comment by UKChris-osm** [comment]
I would agree with the **shop=variety_store** suggestion by @matkoniecz.

**Comment by Adamant36** [comment]
> Have you considered shop=variety_store?

Thanks @MASangys. I added it to the shop=variety_store file in 1ae6a8e.

**Pull request closed without merging**
