### PR TITLE
Update ZG Raiffeisen

### PR DESCRIPTION
**Pull request by Karthoo**
There are different kinds of ZG Raiffeisen stores, this one is the type "Markt"

### CODE REVIEW

**Comment by bhousel** [comment]
Just want to understand better -
- are there other types of "ZG Raiffeisen" that we should have in the index also?
- should all `shop=garden_centre` named "ZG Raiffeisen" be upgraded to name "ZG Raiffeisen Markt"?

**Comment by Karthoo** [comment]
Yes, the ZG Raiffeisen garden_centers are called "Markt". There are also agrarian shops, fuel stations... (see their [location list](https://www.zg-raiffeisen.de/standorte/standort-liste))

**Comment by Karthoo** [comment]
I added the other types of ZG Raiffeisen stores now, most of them are agricutlture-related.

**Comment by bhousel** [comment]
> I added the other types of ZG Raiffeisen stores now, most of them are agricutlture-related.

Awesome @Karthoo this looks great 👍

**Pull request merged**
