### PR TITLE
Add Sleepmasters

### PR DESCRIPTION
**Pull request by arrival-spring**

### CODE REVIEW

**Comment by arrival-spring** [comment]
@UKChris-osm 
I'm intrigued as to how you know the brand is present in Egpyt?
I can't see it on the website or mapped in OSM at all

**Comment by UKChris-osm** [comment]
When I went to the web site linked in the Wikidata and selected stores, it showed up there.

**Comment by arrival-spring** [comment]
Ah, that map had been blocked for me. That's an error in the data though as well

**Comment by UKChris-osm** [comment]
> Ah, that map had been blocked for me. That's an error in the data though as well

So there really isn't a store in Egypt?

**Comment by arrival-spring** [comment]
No store in Egypt. That one says it is in Pretoria and all of the categories on the left are the provinces in South Africa.

**Pull request merged**
