### PR TITLE
Add sub-brands in DE, AT and CH for nextbike

### PR DESCRIPTION
**Pull request by sb12**
See #3378

### CODE REVIEW

**Comment by bhousel** [comment]
We do need `name` tags for all the things in this index, even for situations where convention is for the user to modify the name tag.

**Comment by sb12** [comment]
Do we really need a `name` tag? According to [the wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental) `name=*` should be used for the name of the station (e.g. 'Main Station`) and `network=*` for the name of the station network (`nextbike` in this case). The station name is usually printed in small letters at the station and refers to the locality. 
Adding the name tag violates the approved description in the wiki and might lead to the deletion of correct tags, when the suggestion is used careless by mappers.

**Comment by bhousel** [comment]
This particular index currently needs one

**Comment by bhousel** [comment]
At some point we will probably support other tags like `network`, but we're not currently there yet, sorry..

**Comment by Adamant36** [comment]
@sb12, It's not like people can't just edit the name field if need be. It's currently that way with other things in the index that have local names along with the more general name, like post offices or hotels. Given that would you be willing to just add the name tags so this can be merge? Because it's better to have the presets then not. Especially with the Nextbike preset being removed in #3378. Which, IMO and how you made it sound there, was semi-contingent on this PR happening.

**Comment by sb12** [comment]
> It's not like people can't just edit the name field if need be.

In theory yes, in praxis `name` will be overwritten in iD-Editor and using the JOSM preset, also name will be locked in the iD-Editor after adding the brand. So mappers, which do not read the wiki, will think, `name` is used for the brand name and not for the station name, but this is a problem of all `bicycle_rental` brands and can be solved as soon as it is possible to add brands without names.

I might add the `name` tag in order to add the brands again, but I am not very happy about it.

@bhousel: Travis also complains about `operator`, do I need to remove this tag?

**Comment by bhousel** [comment]
> I might add the `name` tag in order to add the brands again, but I am not very happy about it.
> @bhousel: Travis also complains about `operator`, do I need to remove this tag?

I think if you're not happy about it, we should just leave it out of the index for now.

For now the index is really designed around brands with consistently named features.  It is after all called the "**name** suggestion index", and we are seeding it with the data that we find in the `name` tag.  

We know that we do have a handful of things in the index with name variability (for example, hotels and car dealerships) but in those cases it's not the worst thing if a mapper adds a dealership with the name "Honda", and then forgets to rename it to "Planet Honda Route 22". 

* We don't currently support features that are keyed off `operator`/`operator:wikidata` or `network`/`network:wikidata` but there are some tickets where we've said that this would be good to do.  
* We also don't have a great solution for the name variability, but we've discussed maybe adding a property to some kinds of things to say whether the name should be strictly applied or not.

Until people are happy with how iD and NSI are working together, we don't have to try to stick everything into the NSI that doesn't really fit.


Here are some related tickets
https://github.com/openstreetmap/iD/issues/6890
https://github.com/openstreetmap/iD/issues/6561  (and dup https://github.com/openstreetmap/iD/issues/6951)

**Comment by Adamant36** [comment]
> I think if you're not happy about it, we should just leave it out of the index for now.

Well, I'm disappointed. @sb12 could you at least discuss this on the German tagging mailing list before we completely leave it like out (like you should have done before requesting NextBike's removal)?

**Comment by Adamant36** [comment]
@ENT8R, your from Germany right? Do you have any opinions on this?

**Comment by ENT8R** [comment]
Actually I fully agree with @bhousel. Currently this type of data does not really fit to the goals of the index, maybe in the future there will be another chance to add this. Maybe we need an **network-suggestion-index** beside this index... :smile:
So I would propose to add just one entry for nextbike and rather keep it more simple for the moment.

**Comment by Adamant36** [comment]
> So I would propose to add just one entry for nextbike and rather keep it more simple for the moment.

That's how it originally was, but unfortunately it got removed because of #3378. I guess it can be re-added though. That's what should happen IMO.

**Comment by Adamant36** [comment]
I think I'm going to close this since the consensus seems to be that it doesn't fit with the index. Maybe someone can add the Nextbike entry back at some point if that's what the community wants so there's at least something related to in iD. If not though, that's fine also.

**Pull request closed without merging**
