### PR TITLE
Add Spanish subdivisions flags

### PR DESCRIPTION
**Pull request by Robot8A**
Added the Andalusian flag so far, if everything is correct, I'll add the remaining Autonomous Communities and Autonomous Cities flags.

### CODE REVIEW

**Comment by bhousel** [comment]
This looks ok to me, but I do think the `flag:name:xx` and `subject:name:xx` is unnecessary?  

It's probably fine to just put `flag:name` as whatever local people would call the flag, and add `matchNames` if there are other less-preferred words people might use instead.

cc @1ec5 too

**Comment by michaelblyons** [comment]
Ignorant question here.

The two hyphenated flag names have spacing around the hyphen that is differing: `Castilla-La Mancha` vs `Navarra - Nafarroa` (which looks like the Spanish vs Basque spellings of the same name...?). Is that intentional?

**Review by bhousel — APPROVED** [review]
merge it if you like it  👍

**Comment by Robot8A** [comment]
> Ignorant question here.
> 
> The two hyphenated flag names have spacing around the hyphen that is differing: `Castilla-La Mancha` vs `Navarra - Nafarroa` (which looks like the Spanish vs Basque spellings of the same name...?). Is that intentional?

https://www.openstreetmap.org/relation/349052
https://www.openstreetmap.org/relation/349027

Castilla-La Mancha is a compound name, and the official name includes the hyphenation without spaces around it. For Navarre, yes, it is the Spanish and Basque names. I chose to go as it was written in OSM, as there is usually no defined way to separate multilingual names in Spain. For the Basque Country and Catalonia I chose the Basque and Catalonian forms respectively as they are more widely used locally, even if the Spanish form for BC and the Spanish and Occitan (Aranese) forms for Cat are also stated in their respective Statutes of Autonomy. For Navarre I went with both as Spanish and Basque are both widely spoken. For other multilingual communities, the official name in their Statute of Autonomy clearly states one form over other.
As always, this is a messy topic, but I tried to be as neutral as possible.

**Comment by Robot8A** [comment]
Also, here are the respective government websites of each autonomy as an example of how their names are usually written:
https://www.juntadeandalucia.es/
https://www.aragon.es/
https://www.asturias.es/
http://www.caib.es/
https://www.gobiernodecanarias.org/
https://www.cantabria.es/
https://www.castillalamancha.es/
http://www.jcyl.es/
https://web.gencat.cat/
https://www.gva.es/
http://www.juntaex.es/
https://www.xunta.gal/
https://web.larioja.org/
https://www.comunidad.madrid/
http://www.carm.es/
https://www.navarra.es/ and https://www.nafarroa.eus/
https://www.euskadi.eus/
https://www.ceuta.es/
https://www.melilla.es/

**Pull request merged**
