### PR TITLE
Last Minute Tour

### PR DESCRIPTION
**Pull request by fansanelli**

### CODE REVIEW

**Comment by Adamant36** [comment]
I'm surprised there isn't already other travel agent entries.

**Comment by fansanelli** [comment]
@Adamant36 me too TBH. Idk if it's a big enough brand, but you can check with overpass and let me know :)
Cheers
Francesco

**Comment by ENT8R** [comment]
The more common tag is probably `shop=travel_agency` (https://github.com/osmlab/name-suggestion-index/blob/master/brands/shop/travel_agency.json)

**Comment by fansanelli** [comment]
@ENT8R I've never used it... But IMHO taginfo could reply this question.
Francesco

**Comment by bhousel** [comment]
Oh yeah, @fansanelli - I agree with @ENT8R ... Can you please move this entry into `shop/travel_agent.json` and remove the `office/travel_agent.json` file?  Thanks!

**Comment by fansanelli** [comment]
Will do. But tomorrow.. can you please mark help me to deprecate the office=travel_agent then?

https://wiki.openstreetmap.org/wiki/Proposed_features/office%3Dtravel_agent

**Comment by bhousel** [comment]
> Will do. But tomorrow.. can you please help me to deprecate the `office=travel_agent` then?

Sorry, that's not a thing I can help you with.

**Comment by fansanelli** [comment]
please see #2937

**Pull request closed without merging**
