### PR TITLE
Evroopt supermarket chain

### PR DESCRIPTION
**Pull request by tohaklim**
and wikidata link

### CODE REVIEW

**Comment by Adamant36** [comment]
Hi there. We generally leave out website links from the database. Since its available on the Wikidata page already, isn't reliable, and varies by store location etc. anyway.

**Comment by tohaklim** [comment]
Thanks for the comments. alt_name is how they style it in marketing/signage, but not that important. Will remove the website. Not sure why the Belorussian name should be dropped?

**Comment by Adamant36** [comment]
In that case its not really an alt name. Its the actual name. Otherwise what's the difference between that and Евроопт? What's on the signs goes in the brand and name values. 

As far as dropping the Belorussian, its because of the same reason I said in the other PR. We only go with two languages in the name index. The name on the signs and English if its not in English. I don't care if you drop Belorussian or Russian, but one of them needs to be dropped. If the signs are in Belorussian, id drop Russian. Otherwise, drop the Belorussian. It doesn't really matter which one. As long its one of them English at the end of it.

**Comment by bhousel** [comment]
I removed the redundant tags in 7104c83 and merged..

**Pull request merged**
