### PR TITLE
German transit districts

### PR DESCRIPTION
**Pull request by Karthoo**
added network:wikipedia + network:wikidata links, removed operator tags, duplicates and historical networks and added a few missing networks

### CODE REVIEW

**Comment by Karthoo** [comment]
I don't get why checking fails. I have removed the duplicate where it says it fails.

**Comment by Adamant36** [comment]
> I don't get why checking fails. I have removed the duplicate where it says it fails.

Are all the edits from you or is some of it from running build or something?

**Comment by Adamant36** [comment]
So, this was a lot of edits and seems to have problems and changes that were not really needed, like removing the operator tags (and I think a few others). So, I'm going to close this. Maybe due each "thing" in a separate PR so they are easier to review and trouble shot.

**Comment by bhousel** [comment]
I honestly dont see anything wrong with it, and probably would have hit the green button.
@Adamant36 , @Karthoo Want to merge anyway?
It's ok to remove the `operator` tags if the situation in Germany is complicated.  Standardizing `network`/`network:wikidata` and removing duplicates is what we're really after.

**Comment by Adamant36** [comment]
> @Adamant36 , @Karthoo Want to merge anyway?

Yeah sure. I didnt see anything wrong with it myself, but then I didn't want to screw something up down the line either. I guess I could have waited for a second opinion though.

**Comment by bhousel** [comment]
> Yeah sure. I didnt see anything wrong with it myself, but then I didn't want to screw something up down the line either. I guess I could have waited for a second opinion though.

Sorry, now that I'm looking at it more closely, and seeing #4289 - it is kind of a mess.  Going to revert it..

**Comment by Adamant36** [comment]
> Sorry, now that I'm looking at it more closely, and seeing #4289 - it is kind of a mess. Going to revert it..

Not problem.

**Pull request merged**
