### PR TITLE
Update Kwik Fill

### PR DESCRIPTION
**Pull request by cicku**
- Wikidata
- Wikipedia

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Thanks @cicku 

However, it might be preferable to create a specific "_Kwik Fill_" branded Wikidata item, rather than using the parent company / operator wikidata in this case.

For example, having a Wikidata item that's specific to "_Kwik Fill_" it's web site, social media links, inception, headquater location, and the fact it's a subsidiary of the "_United Refining Company_".

**Comment by bhousel** [comment]
Agree with @UKChris-osm - it would be better to have wikipedia/wikidata pages for the Kwik Fill brand.

**Comment by cicku** [comment]
Sorry I was busy recently.

Yes your ideas area great. So what should I do now? Simply creating a new page at wikipedia with a redirection to parent company?

**Comment by UKChris-osm** [comment]
I would recommend creating a Wikidata entry for "_Kwik Fill_" (I don't think there is enough information to create a Wikipedia entry) and add a reference to its parent company "_United Refining Company_", as well as any other useful information, such as social media links, the date the company was created, web address, headquarter locations, etc.

The "_Kwik Fill_" Wikipedia reference you have included in your PR is only a redirect to "_United Refining Company_" and so isn't suitable unfortunately.

**Comment by cicku** [comment]
I'm going to close this one and work on this in the future.

**Pull request closed without merging**
