### PR TITLE
Add wikidata reference for Tchip hairdresser

### PR DESCRIPTION
**Pull request by bmillemathias**
Partially fill issue #1505

### CODE REVIEW

**Comment by Adamant36** [comment]
What does "partially fills" mean? Seems like it closes it to me.

**Comment by bmillemathias** [comment]
> What does "partially fills" mean? Seems like it closes it to me.

Because there is no wikipedia page. I tried to create one for another shop but some zealot deleted it instantly...

**Comment by matkoniecz** [comment]
In case of no Wikipedia article it is perfectly fine to add just wikidata. Changing Wikipedia notability guidelines is not required to be done as part of fixing issues :)

**Comment by Adamant36** [comment]
That sucks. Yeah, in general good luck doing much of anything on Wikipedia like that these days. Luckily Wikidata is a little loser on nobility, but there's still probably there to sometimes. Just having a Wikidata entry without a Wikipedia article attached to it is perfectly fine for our purposes though.

**Pull request merged**
