### PR TITLE
Add supermarket in Malaysia

### PR DESCRIPTION
**Pull request by MASangys**

### CODE REVIEW

**Comment by Adamant36** [comment]
Hi. Did you mean to add 99 Speedmart again here?

**Comment by MASangys** [comment]
No but in variety store

**Comment by Adamant36** [comment]
You want to delete it then since its already in another PR and the index?

**Comment by MASangys** [comment]
99 speedmart is in convenience store category, this one is another

**Comment by Adamant36** [comment]
Yeah but your already adding it in the other PR. So its not needed in this one also. That one should take care of it.

**Comment by MASangys** [comment]
This one is for another shop which is The Store and TF Value Mart tho

**Comment by Adamant36** [comment]
I get that. It doesn't have anything to do with The Store and TF Value Mart. My point is that you have code in this PR to add 99 Speedmart to the variety store file. Which your already doing in PR #4004. So, do you want to add it in #4004 or this PR? because it can't be added in both and you told me to re-open #4004. So, I'm assuming that's how you want to do it. Which would make the code for it here redundant.

**Comment by MASangys** [comment]
Both are the same right, I think there is an issue occur when I do PR

**Comment by MASangys** [comment]
So just merge 1 of them and another need to be clesed

**Comment by bhousel** [comment]
Thanks @MASangys , looks good to me ..

**Pull request merged**
