### PR TITLE
Removed Carino's Italian

### PR DESCRIPTION
**Pull request by Shweta200126**
#4451 was supposed to be added to restaurant's amenity and has been added there.

### CODE REVIEW

**Review by bhousel — CHANGES_REQUESTED** [review]
Please include the updates to amenity/restaurant.json in this pull request also, thanks 👍

**Comment by Shweta200126** [comment]
Sorry but I dont know how to do that , If u could guide me that would be nice.

**Comment by UKChris-osm** [comment]
I've re-opened #4451 with a question about Carino's!

**Comment by bhousel** [comment]
Oh nice - Looks like it should be removed from fast food (which this PR does).. Thanks @Shweta200126 👍

**Review by bhousel — APPROVED** [review]

**Pull request merged**
