### PR TITLE
Change Cici's to Cicis

### PR DESCRIPTION
**Pull request by gabrielhicks**
#4268

### CODE REVIEW

**Comment by Adamant36** [comment]
Thanks. One thing though. Cici's Pizza should probably a match name instead of being discarded so they can be "upgraded."

**Comment by gabrielhicks** [comment]
Thanks! I will commit to change this again :)

**Comment by UKChris-osm** [comment]
Have they retained "_Pizza_" in the name? Or is it just known as "_Cicis_" now?

**Comment by Adamant36** [comment]
According to Wikipedia and their new logo it's "Cicis"

**Comment by gabrielhicks** [comment]
Maybe we could change brand to Cicis then

**Comment by gabrielhicks** [comment]
I changed brand and name to Cicis to reflect their wikidata, and added match names for variations of this brand. The data from their own twitter, youtube, and facebook pages points to Cicis being the name, occasionally with pizza following.

**Comment by UKChris-osm** [comment]
Thanks @gabrielhicks 👍 

For future reference, you don't need to edit the "_names_all_" or "_names_keep_" files, as these are taken care of automatically :)

**Comment by gabrielhicks** [comment]
@UKChris-osm Thank you! Sorry I am spazzy, this is my first time contributing to open source. Thank you so much for gently guiding me!

**Comment by UKChris-osm** [comment]
@gabrielhicks nothing spazzy about your PR :) We look forwards to any more contributions you wish to submit :)

**Pull request merged**
