### PR TITLE
Split out DQ Grill and Chill

### PR DESCRIPTION
**Pull request by tas50**
I made this cuisine burger based on reading their menu. Dairy Queen
itself is listed as cuisine ice cream, which seems a bit exaggerated since
their stores are just burger joints at this point.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
I had assumed we were sorting that hash since we sort the arrays. That should probably just get sorted by the build so they're consistent throughout.

**Comment by Adamant36** [comment]
> That should probably just get sorted by the build so they're consistent throughout.

That would probably be a better way to do it.

**Comment by Adamant36** [comment]
@tas50, btw do you happen to know why your PR's are creating branches on the main repository instead of in yours? Did you not fork it or something?

**Comment by bhousel** [comment]
> do you happen to know why your PR's are creating branches on the main repository instead of in yours? Did you not fork it or something?

I made @tas50 a collaborator so they can work directly against master if they want to.

**Comment by Adamant36** [comment]
My original question to @tas50 probably could have been said better. Since it was more about him not deleting his old branches more then anything. 

IHis branches weren't being deleted after his PRs were merged. So when I went to update my branch they all got added to it in the fetching proccessing. Which is why I was asking. It makes sense collaborators could make branches without forking though. I just hadn't thought about it before. 

I guess we'll have to do a better job making sure the branches from PRs are deleted after merging them so they don't build up. I thought the person doing the PR deletes them, but it probably doesn't matter that much who does it. Although, I don't want to accidently delete a branch someone is still using after a PR is merged either. So maybe it should be on the person doing the PR. Do you have a policy for that?

**Comment by tas50** [comment]
Yeah sorry about the lack of cleanup. We have a CI job that auto deletes PR branches at Chef so I'm used to a bot cleaning up my messes. I'll be sure to open them up as tas50/BRANCH as well so there won't be any name collision issues. If you see anything that's been merged and not deleted by me feel free to nuke it.

**Comment by Adamant36** [comment]
> Yeah sorry about the lack of cleanup

No worries. Its cool you guys have a bot that does it for you. 

> I'll be sure to open them up as tas50/BRANCH

Thanks. That will help a lot. 

> If you see anything that's been merged and not deleted by me feel free to nuke it.

OK. I'll do that.

**Pull request merged**
