### PR TITLE
Preserve `name=*` tags of CBA & Reál convenience stores

### PR DESCRIPTION
**Pull request by gy-mate**
The `name=*` tags of _CBA_ & _Reál_ convenience stores should be preserved, as these shops usually have a unique name by which they are commonly known.

### CODE REVIEW

**Comment by UKChris-osm** [comment]
When you say "_smaller_" shops, are you still talking about supermarkets, or the "_convenience stores_"?

I've also noticed the supermarket in Bulgaria is a separate entry from the rest, but this isn't the case for "_convenience stores_", do you think this should be changed as well?

**Comment by gy-mate** [comment]
> When you say "_smaller_" shops, are you still talking about supermarkets, or the "_convenience stores_"?

@UKChris-osm My bad, I meant _convenience stores_. Fixed the title, description and the content of the PR. (Thank you for the question!)

**Comment by gy-mate** [comment]
> I've also noticed the supermarket in Bulgaria is a separate entry from the rest, but this isn't the case for "_convenience stores_", do you think this should be changed as well?

Unfortunately I'm not familiar with Bulgarian _CBA_ stores.

**Comment by Dimitar5555** [comment]
> I've also noticed the supermarket in Bulgaria is a separate entry from the rest, but this isn't the case for "_convenience stores_", do you think this should be changed as well?

Yes it should be a separate entry without `preserveTags`. They are named "CBA". Any other local names ([example](https://www.openstreetmap.org/node/3130696829)) are related to the branch.

**Comment by gy-mate** [comment]
@Dimitar5555 Thank you for the info!

Lke this?

**Comment by Dimitar5555** [comment]
Yes, exactly like that. Thanks!

**Comment by gy-mate** [comment]
@UKChris-osm @Snowysauce I think this is ready for a final review.

**Pull request merged**
