### PR TITLE
Add Tambunting (shop=pawnbroker)

### PR DESCRIPTION
**Pull request by govvin**
Add an entry for the Tambunting chain of pawnshops in the Philippines, update entries with correct Wikidata and Wikipedia items.

### CODE REVIEW

**Comment by ArenaL5** [comment]
Great! Could you add a Wikipedia link, too? Either
```json
      "brand:wikipedia": "en:Tambunting",
```
or
```json
      "brand:wikipedia": "tl:Tambunting Pawnshop",
```

And please squash your commits after that.

**Comment by govvin** [comment]
How do I squash commits?

**Comment by ArenaL5** [comment]
The easiest way is to:
- go three commits back, but keep all the changes in stage, without discarding them
- create a new commit
- do a force-push to replace these three commits with your new, squashed commit

```bash
git reset --soft HEAD~3
git commit -m "Add Tambunting (shop=pawnbroker)

Add an entry for the Tambunting chain of pawnshops in the Philippines."
git push --force
```

If you have any trouble, I can squash them for you.

**Comment by govvin** [comment]
I hope you wouldn't find it too inconvenient to doing the squashing for me.  I'm not doing this PR from the CLI, 

Thanks!

> The easiest way is to:
> 
>     * go three commits back, but keep all the changes in stage, without discarding them
> 
>     * create a new commit
> 
>     * do a force-push to replace these three commits with your new, squashed commit
> 
> 
> ```shell
> git reset --soft HEAD~3
> git commit -m "Add Tambunting (shop=pawnbroker)
> 
> Add an entry for the Tambunting chain of pawnshops in the Philippines."
> git push --force
> ```
> 
> If you have any trouble, I can squash them for you.

**Comment by ArenaL5** [comment]
Unbearably inconvenient.

Squash

I tell people to do it for themselves only because I try to avoid editing or cloning commits from other people. (Or insert myself in other commits, but this one is only attributed to you.) :slightly_smiling_face:

It's also how I started learning Git (the command tool) in the first place. It has a lot of useful methods if you're willing to study the manuals -- I only know a couple of them.

**Pull request merged**
