### PR TITLE
Update logos and the docs

### PR DESCRIPTION
**Pull request by tas50**
I backfilled a few on wikidata, and reran the script

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by bhousel** [comment]
oh whoops!  I just did the same thing

**Comment by bhousel** [comment]
though this makes me realize that I should fix the generated html to be more diff-able

**Comment by matkoniecz** [comment]
> oh whoops! I just did the same thing

So I guess that it can be closed as this PR is just a script rerun and data was added externally to Wikidata?

**Comment by bhousel** [comment]
> So I guess that it can be closed as this PR is just a script rerun and data was added externally to Wikidata?

Yeah I think so.. I just spot checked a few of the conflicts, and it seems like master is just slightly ahead , probably from me running the script after you.. Sorry!

**Comment by tas50** [comment]
I was going to ask for a PP html so the diffs will make sense. That would be super useful

**Pull request closed without merging**
