### PR TITLE
Add 1 cafe , 1 post_office

### PR DESCRIPTION
**Pull request by LaoshuBaby**
# Add:
  + 蜜雪冰城
  + 菜鸟驿站

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
First

I Should thanks to @bhousel for fix the locale sensetive sort func in [this commit (58bfd67)](https://github.com/osmlab/name-suggestion-index/commit/58bfd675d1f5fbfad8caa80ad36da585ffa7d058)

This time the odd-order problem doesn't come again!

**Comment by LaoshuBaby** [comment]
Second

This PR is still the maintance of [this list](https://github.com/osmlab/name-suggestion-index/pull/4871#issuecomment-765151272)

Thanks for my friends in QQ Group ```Mapping Life```

It is them that help me collect this daily brand list

**Comment by LaoshuBaby** [comment]
This list still remain:
+ **菜鸟驿站**(Add this time)
+ ~~新华书店~~
+ 易捷
+ ~~吉野家~~
+ 和合谷
+ 田老师
+ 稻香村
+ **蜜雪冰城**(Add this time)
+ ~~喜茶~~(Already in NSI **but can't auto suggest in iD**)
+ COCO
+ 一点点
+ ~~好利来~~(Already in NSI **but can't auto suggest in iD**)
+ 沪上阿姨
+ 东方宫
+ 西部马华
+ 中百便利

**Comment by LaoshuBaby** [comment]
And I still found some brand can't auto suggest in iD editor

even they have already exist in NSI

**Comment by UKChris-osm** [comment]
> And I still found some brand can't auto suggest in iD editor
> even they have already exist in NSI

Hi @LaoshuBaby, the updated NSI list will soon appear in iD hopefully. as @bhousel has [submitted version 5](https://github.com/openstreetmap/iD/pull/8305) code to the iD Editor repository, it just needs to be accepted by iD and pushed out to users, so shouldn't be to much longer if all goes well.

**Comment by bhousel** [comment]
Looks great @LaoshuBaby thanks 👍 
The iD integration will be ready soon - I have been doing a lot of work on https://github.com/openstreetmap/iD/pull/8305 and it is really hard, but we definitely don't want to rush something into production that makes bad suggestions.. 😅

**Pull request merged**
