### PR TITLE
Add Freshens

### LINKED ISSUE #3172: Add Freshens fast food
Fast food chain that claims 500+ locations. Main item is smoothies: https://freshens.com/

### PR DESCRIPTION
**Pull request by ferdinand0101**
I'm unsure about the cuisine tag which is needed for that green healthy food stuff

fixes #3172

### CODE REVIEW

**Comment by mds08011** [comment]
Can you be more specific regarding what you mean by "green healthy food stuff"?  I just looked at the menu and am unsure.  Are you referring to vegetable-based smoothies (kale, wheatgrass, etc)?  I would recommend just not including it.

**Comment by ferdinand0101** [comment]
No I'm reffering to the Salads and all the other stuff which uses fresh produuce and those "superfoods" which seems to be their main selling point

**Comment by bmillemathias** [comment]
Hello

I'm not really happy with the cuisine tag either, please have a look to https://taginfo.openstreetmap.org/keys/cusine#values and set a more correct value.

Also for sake of commit history are you able to put everything in one commit.

Best.

**Comment by ferdinand0101** [comment]
Yeah I was hoping you guys would have an idea for the cusine tag cause I found no good one

**Comment by mds08011** [comment]
I'm not too concerned with having all-encompassing cuisine tags.  For example, the NSI Jamba Juice entry just uses `juice` despite having a variety of things other things on the menu.

**Comment by ferdinand0101** [comment]
also I can't seem to squish the commits

**Comment by Adamant36** [comment]
> also I can't seem to squish the commits

Its fine. I did it when merging.

**Pull request merged**
