### PR TITLE
Update consulting.json added Iron Mountain

### PR DESCRIPTION
**Pull request by jhutton1**

### CODE REVIEW

**Comment by kjonosm** [comment]
@jhutton1 Could you check whether Iron Mountain really is a consulting company? According to wikipedia it's rather a data storage provider.

**Comment by jhutton1** [comment]
@kjonosm  - I agree.  Which category would it be for data storage provider?  it?

**Comment by jhutton1** [comment]
> @jhutton1 Could you check whether Iron Mountain really is a consulting company? According to wikipedia it's rather a data storage provider.

which category should it be then?

**Comment by kjonosm** [comment]
Not entirely sure whether there is an agreed upon tag. For tagging the actual server facilities, see [`telecom=data_center`](https://wiki.openstreetmap.org/wiki/Tag:telecom%3Ddata_center).

**Comment by AntiCompositeNumber** [comment]
I'm going back and forth between `office=consulting` and `office=it`, but leaning more toward `consulting`. If they just did data storage I'd probably say `it`, but some of their other services fall more into `consulting` for me.

`telecom=data_center` obviously covers the data centers, as previously noted. Their other facilities mostly fall under `man_made=warehouse`/`landuse=industrial` `industrial=warehousing`.

**Comment by jhutton1** [comment]
So leave it as office=consulting?

**Comment by jhutton1** [comment]
@AntiCompositeNumber , should we leave it as office=consulting?

**Comment by AntiCompositeNumber** [comment]
Looks like [existing offices](https://overpass-turbo.eu/s/1DcE) are pretty much all just tagged `office=company`. There's a couple of `office=it`, which would also be fine. There's also an `office=ngo` which is wrong.

I'm still kinda unsure about which tag is best, which I guess is probably a good sign to just use `office=company`.

**Comment by Cj-Malone** [comment]
I have no idea what Iron Mountain is. But my opinion is to follow OSM, unless we have a strong opinion/know better. I'd vote for `office=company`, with `"matchTags": ["office/it", "office/consulting"]`. We can change it in the future if some knows better.

**Comment by jhutton1** [comment]
Thanks all for the feedback.  Updates have been made.

**Review by Cj-Malone — APPROVED** [review]

**Review by AntiCompositeNumber — APPROVED** [review]

**Pull request merged**
