### PR TITLE
Add LifeLabs and Hamilton Bike Share; add operator and matchNames to Hamilton Street Railway

### PR DESCRIPTION
**Pull request by kyy0602**

### CODE REVIEW

**Comment by arch0345** [comment]
Thanks @kyy0602 and welcome! Note that Hamilton Bike Share won't get generated as an iD preset since it doesn't have a wikidata page linked to it.

**Comment by kyy0602** [comment]
> 
> 
> Thanks @kyy0602 and welcome! Note that Hamilton Bike Share won't get generated as an iD preset since it doesn't have a wikidata page linked to it.

Thanks @arch0345 ! I would probably add a wikidata page and link to it in a future PR since there isn't one yet.

**Comment by arch0345** [comment]
>I would probably add a wikidata page and link to it in a future PR since there isn't one yet.
Great! Just make sure you add some statements (instance of, country, official website, etc) so it doesn't get deleted. Since we collect logos from Facebook/Twitter profiles on their wikidata page, I also recommend adding at least one of these if they have one.

**Comment by kyy0602** [comment]
> 
> 
> > I would probably add a wikidata page and link to it in a future PR since there isn't one yet.
> 
> Great! Just make sure you add some statements (instance of, country, official website, etc) so it doesn't get deleted. Since we collect logos from Facebook/Twitter profiles on their wikidata page, I also recommend adding at least one of these if they have one.

Thanks for the tips!

**Pull request merged**
