### PR TITLE
fix "hu" (shop/convenience|Abc) - general hungarian word - remove (need extra check in Poland!)

### PR DESCRIPTION
**Pull request by ImreSamu**

### CODE REVIEW

**Comment by matthijsmelissen** [comment]
Why you think 'ABC' is a generic hungarian word?

At least in Poland, ABC (or Abc or abc, not sure) is a major chain of small convenience shops.

**Comment by ImreSamu** [comment]
>Why you think 'ABC' is a generic hungarian word?

in Hungary, it is a synonym for a ( food ) shop (  ~ type of shop )  - so a general name.
* https://hu.wikipedia.org/wiki/ABC-%C3%A1ruh%C3%A1z

maybe you can re-add  with  proper country code + wikidata code

**Comment by ImreSamu** [comment]
[Google Translate link:ABC Áruház](https://translate.google.com/translate?sl=hu&tl=en&js=y&prev=_t&hl=hu&ie=UTF-8&u=https%3A%2F%2Fhu.wikipedia.org%2Fwiki%2FABC-%25C3%25A1ruh%25C3%25A1z&edit-text=)

**Comment by ImreSamu** [comment]
Overpass Turbo : http://overpass-turbo.eu/s/CYa

**Comment by ImreSamu** [comment]
wordwide Overpass Turbo :   it  is a frequent name.
image

**Comment by bhousel** [comment]
Ah yeah this is another tricky one kind of like Price Chopper #1868 
There's one in Hawaii too:  https://en.wikipedia.org/wiki/ABC_Stores_(Hawaii)

Let's leave this open but hold off on merging for now..

**Comment by matkoniecz** [comment]
> There's one in Hawaii too: https://en.wikipedia.org/wiki/ABC_Stores_(Hawaii)

Article for Polish brand is at https://pl.wikipedia.org/wiki/Abc_(sie%C4%87_handlowa) ( https://www.wikidata.org/wiki/Q11683985 )

**Pull request closed without merging**
