### PR TITLE
Merge shop/interior_decoration|Casa into shop/furniture|Casa

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by Adamant36** [comment]
Seems like they are a furniture store. When I did a search for them they are actually called "Casa Furniture" and that's what it is called on their [website](https://casafurniture.com/). So this should probably be reversed.

**Comment by bhousel** [comment]
Yeah let's keep it as `shop=furniture`.  This is a situation where the previous mappers are more often wrong than right!  😆

**Comment by waldyrious** [comment]
Thanks so much for double-checking. I was looking for a way to quickly contributing manpower but it turns out the issue is not the scale of the task list, but the nuance required to solve each one. This particular example seemed to be more straightforward than the others, but turns out it wasn't either. Sorry! 😳 Will fix.

**Comment by waldyrious** [comment]
Btw, should the counts be summed when merging entries, or do I keep them untouched?

**Comment by ENT8R** [comment]
> Btw, should the counts be summed when merging entries, or do I keep them untouched?

Just keep them untouched.

**Comment by bhousel** [comment]
Thanks @waldyrious 👍

**Pull request merged**
