### PR TITLE
added brand albaik

### PR DESCRIPTION
**Pull request by pushkar1393**
- Added entry under fast_food.json for `Albaik`.
- Related issue - #4353 

Please let me know if anything needs to be modified.

### CODE REVIEW

**Comment by Adamant36** [comment]
Thank you. It looks fine. BTW, if put "closes" and the issue number in your PR comment then it will automatically close the issue the PR is related to when it's merged.

**Comment by Adamant36** [comment]
> Thank you. It looks fine.

Actually, I guess it has a conflict. So, I'll wait for someone else to come around and look at it before I merge it.

**Comment by pushkar1393** [comment]
Thanks, for the quick reply @Adamant36. I checked the conflict was due to malformation in the `fast_food.json` file, due to a mismatch with the upstream since the request was raised earlier. I have resolved the conflict.

**Comment by pushkar1393** [comment]
Out of curiosity how does one decide what tag value should be provided for "brand:Wikipedia" if there is a wiki page in English and in Arabic (or any other language.)

**Comment by Identitaet** [comment]
We usually try to use the "local language"
And if that isn't possible usually English

**Pull request merged**
