### PR TITLE
Changes to amenity/fuel

### PR DESCRIPTION
**Pull request by luisluigi639**
Adding Wikidata for Classic Oil and changing Copec to correct Wikidata.

### CODE REVIEW

**Comment by matkoniecz** [comment]
Is Empresas Copec completely wrong or just imprecise?

**Comment by luisluigi639** [comment]
@matkoniecz Empresas Copec just imprecise, the parent company is called Empresas Copec and the gas sation chain is called just Copec.

**Comment by luisluigi639** [comment]
I think I need some help with this last commit.

**Comment by bhousel** [comment]
No problem @luisluigi639  I sorted out the conflict and merged.

I left the name "Amic" as it was (instead of renaming it to "Amic Energy") because it's already tagged this way [76 times](https://github.com/osmlab/name-suggestion-index/blob/master/dist/names_keep.json#L1048) and the stations show the "energy" part very small: http://amicenergy.com/

**Pull request merged**
