### PR TITLE
Add Kokoriko

### PR DESCRIPTION
**Pull request by desiderantes**

### CODE REVIEW

**Comment by Adamant36** [comment]
I don't think we add the delivery tag with anything because we would have to be 100% sure every place does delivery and that it wont change any time soon. Otherwise, it risks introducing bad data. So, are you certain every location does delivery?

**Comment by desiderantes** [comment]
> I don't think we add the delivery tag with anything because we would have to be 100% sure every place does delivery and that it wont change any time soon. Otherwise, it risks introducing bad data. So, are you certain every location does delivery? 

Yup. They offer both their own delivery, and have agreements with iFood, so you can order from Kokoriko itself and the delivery can be fulfilled by Kokoriko itself or by iFood

**Review by bhousel — CHANGES_REQUESTED** [review]
Please remove the `delivery` tag - we don't include it for other brands in this index.  Thanks!

**Comment by Adamant36** [comment]
I removed it in f8d7610.

**Pull request merged**
