### PR TITLE
Origin/itsmeanubhab

### PR DESCRIPTION
**Pull request by itsmeAnubhab**
added omaha steaks #5451

### CODE REVIEW

**Comment by arch0345** [comment]
Are you sure Omaha Steaks is a restaurant? A majority of these are tagged as shop/butcher based on an [overpass query](https://overpass-turbo.eu/?w=%22name%22%3D%22Omaha+Steaks%22+global&R).

**Comment by tas50** [comment]
@bhousel Honey Baked Ham! I was trying to remember where we discussed this all while I was writing up the issue. That was the one.

**Comment by itsmeAnubhab** [comment]
> Are you sure Omaha Steaks is a restaurant? A majority of these are tagged as shop/butcher based on an [overpass query](https://overpass-turbo.eu/?w=%22name%22%3D%22Omaha+Steaks%22+global&R).

yes there are omaha butcher shops as well but i have the restaurant

**Comment by itsmeAnubhab** [comment]
> Are you sure Omaha Steaks is a restaurant? A majority of these are tagged as shop/butcher based on an [overpass query](https://overpass-turbo.eu/?w=%22name%22%3D%22Omaha+Steaks%22+global&R).

ok, i will edit it

**Pull request closed without merging**
