### PR TITLE
Cooper's Hawk

### PR DESCRIPTION
**Pull request by m-hue**
american restaurant & wine store chain, locations in the midwest, florida, arizona, and some on the east coast.

### CODE REVIEW

**Comment by m-hue** [comment]
good catch. Copy/Paste fail. Sorry about that. fixed.

**Comment by kjonosm** [comment]
Sorry for nitpicking but do they really serve American cuisine? Their menu online looks quite international to me...

**Review by LaoshuBaby — COMMENTED** [review]
https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/shop/wine.json

For this brand, treat is as a restaurant or just a wine shop?

**Comment by bhousel** [comment]
> For this brand, treat is as a restaurant or just a wine shop?

It is weird, but it looks like it is actually both..

thanks @m-hue , I'll merge 👍

**Pull request merged**
