### PR TITLE
Added brand entries for Waikiki Poke and Blackjack Pizza

### PR DESCRIPTION
**Pull request by smfuller**

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @smfuller and welcome! 👋 
This looks good!  "Waikiki Poke" will need a `brand:wikidata` entry at some point, but we can merge as-is..

**Comment by Adamant36** [comment]
@smfuller, you know how many stores Waikiki Poke has and where they are mainly located? It seems from an internet search that they only have one location in Colorado.

**Comment by smfuller** [comment]
@Adamant36 Although I thought this was a franchise, after looking at this further it appears that this is indeed the only location right now.

Should I submit another pull request from my fork without this location info?

**Comment by bhousel** [comment]
no problem @smfuller  - I removed it in ecda8ff2d

**Pull request merged**
