### PR TITLE
Add Macif insurance

### PR DESCRIPTION
**Pull request by bmillemathias**
https://overpass-turbo.eu/s/Jx0

### CODE REVIEW

**Comment by Adamant36** [comment]
The brand:wikipedia name is ridiculously long to the point of being useless in my opinion. I'm surprised Wikipedia even allows for it as an article title. Is there some way you could create an article for Macif that mentions the long name as "known as" and then have the current article forward to it? That's how it is for banks with long names. The articles titles are the shortened forms of the name. Personally, I'm a little against introducing something that long into OSM.

**Comment by bmillemathias** [comment]
> 
> 
> The brand:wikipedia name is ridiculously long to the point of being useless in my opinion. I'm surprised Wikipedia even allows for it as an article title. Is there some way you could create an article for Macif that mentions the long name as "known as" and then have the current article forward to it? That's how it is for banks with long names. The articles titles are the shortened forms of the name. Personally, I'm a little against introducing something that long into OSM.

Yes I saw that and had the same impression; when you see that Maaf or Maif have the shortened name, I thought about renaming but I did not want to rename on WK and started to have comments from other people. I'll try to create a short name redirecting to the canonical one.

**Comment by matkoniecz** [comment]
`fr:Mutuelle assurance des commerçants et industriels de France et des cadres et des salariés de l'industrie et du commerce` is ridiculous, but at 122 characters still fits within tag size limit.

**Comment by bhousel** [comment]
Yes, this one is weird but `brand:wikipedia` _really doesn't matter at all_.  The values aren't stable and someone could go and change it on Wikipedia tomorrow. 

This is the main reason we are prioritizing `brand:wikidata` as the main brand identifier, and not the wikipedia links or the names.

I'm fine with merging as-is but also fine with waiting if you want.

**Comment by bmillemathias** [comment]
> 
> 
> `fr:Mutuelle assurance des commerçants et industriels de France et des cadres et des salariés de l'industrie et du commerce` is ridiculous, but at 122 characters still fits within tag size limit.

actually `fr:Macif` already exist and redirect to the main article

**Comment by bhousel** [comment]
thanks @bmillemathias  👍

**Pull request merged**
