### PR TITLE
Velcom rebranding

### PR DESCRIPTION
**Pull request by tohaklim**
Now A1 nationwide, signage being replaced. 
Added name:en to differentiate from other A1 in the EU

### CODE REVIEW

**Comment by bhousel** [comment]
I don't understand this rebranding.. 
If the new A1 Belarus is a subsidiary of the "other A1 in Europe", can we just use that one instead?

https://en.wikipedia.org/wiki/A1_Telekom_Austria_Group 
https://www.wikidata.org/wiki/Q688755

Meaning - can I just make a A1 entry that has those things, and operates in a bunch of countries (including `by`) and matches the older "velcom" names?

**Comment by tohaklim** [comment]
I am not sure if that would work universally considering the only thing they have in common is branding. This is a separate legal entity, but same brand they seem to be using in a couple of countries. 
I don’t think I’ve seen the other A1 entries in the index though?

**Comment by bhousel** [comment]
> am not sure if that would work universally considering the only thing they have in common is branding. This is a separate legal entity, but same brand they seem to be using in a couple of countries.

It seems ok - this project is really more an index of brands not legal entities.

**Comment by tohaklim** [comment]
Thanks for implementing that!
I am wondering if the local sub Wikipedia page should be inserted somewhere, or just the wiki data entries linked

**Pull request merged**
