### PR TITLE
Update bank.json

### PR DESCRIPTION
**Pull request by waso99**
Adding some Saudi banks

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @waso99 , looks great!  👍

**Comment by waso99** [comment]
Thanks @bhousel .

**Comment by waso99** [comment]
how it's work with ID editor? As Automated POI with logo

**Comment by bhousel** [comment]
> how it's work with ID editor? As Automated POI with logo

Eventually it will be available in iD as a preset with a logo.

**Comment by waso99** [comment]
> 
> 
> > how it's work with ID editor? As Automated POI with logo
> 
> Eventually it will be available in iD as a preset with a logo.

So far it doesn't.

**Pull request merged**
