### PR TITLE
Add 2 lottery and Modify 1 lottery and Delete 1 lottery

### PR DESCRIPTION
**Pull request by LaoshuBaby**
## Add:
   + 中国福利彩票
   + 中国体育彩票

## Modify:
   + 台灣彩券

## Delete:
   + 公益彩券

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
## 2 Infomation about this PR

1. The reason of **Delete** the brand ```公益彩券```：

  According to my search on the internet， ```公益彩券``` is a alt_name of ```台灣彩券``` in old time.

  More infomation can be found on [wikipedia](https://zh.wikipedia.org/wiki/%E5%8F%B0%E7%81%A3%E5%BD%A9%E5%88%B8)

2. Why don't add ```brand:wikidata``` for new added 2 brand:

  Because I have to use VPN to edit wikipedia, and **I only have immunity on zhwiki**

  So I could't create new wikidata for those only Chinese version wikipedia.

**Comment by bhousel** [comment]
Thanks @LaoshuBaby  - one point about wikidata:

> Why don't add brand:wikidata for new added 2 brand:
>Because I have to use VPN to edit wikipedia, and I only have immunity on zhwiki
>So I could't create new wikidata for those only Chinese version wikipedia.

Every wikipedia page should already have a wikidata qid created for it automatically:
Can you follow this link like in the screenshot ?

Screen Shot 2021-03-04 at 11 13 34 AM

For me it takes me to the https://www.wikidata.org/wiki/Q10915473  Taiwan Lottery (Q10915473)

**Comment by LaoshuBaby** [comment]
> 
> 
> Thanks @LaoshuBaby - one point about wikidata:
> 
> > Why don't add brand:wikidata for new added 2 brand:
> > Because I have to use VPN to edit wikipedia, and I only have immunity on zhwiki
> > So I could't create new wikidata for those only Chinese version wikipedia.
> 
> Every wikipedia page should already have a wikidata qid created for it automatically:
> Can you follow this link like in the screenshot ?
> 
> Screen Shot 2021-03-04 at 11 13 34 AM
> 
> For me it takes me to the https://www.wikidata.org/wiki/Q10915473 Taiwan Lottery (Q10915473)

------

Ahh......This is because the page you see have already link to a wikidata so it will show you this button

For Example

#### A page that only in zhwiki (without wikidata)

In the tools bar at left , the list have 9 objects

图片

#### A page that have multi language version (with wikidata)

In the tools bar at left , the list have 10 objects

图片

------


**I'm sorry for my incomplete commit! **

And thanks to @Identitaet for added wikidata! It helps we a lot! 

------

I guess this PR is ready for merge?

**Comment by bhousel** [comment]
Thanks @LaoshuBaby & @Identitaet  👍

**Pull request merged**
