### PR TITLE
Added XL Parts to shop car parts

### PR DESCRIPTION
**Pull request by ckpiper**

### CODE REVIEW

**Comment by arch0345** [comment]
Thanks @ckpiper for all your contributions recently! To speed things up, I've invited you to be a maintainer on this project. Feel free to triage issues, merge PRs, and commit directly to the main branch anything that you feel good about.

**Comment by ckpiper** [comment]
Thank you @arch0345 !! Quick Question. When you say commit directly to the main branch. Can I merge my own PRs if I make a branch on my fork and then make a PR upstream like here?

**Comment by arch0345** [comment]
Yes, you can either do that or edit directly on the main repository (https://github.com/osmlab/name-suggestion-index/tree/main)

**Comment by ckpiper** [comment]
Sweet. I will continue making branches on my personal and making PRs as I think it is more proper.

**Pull request merged**
