### PR TITLE
WIP: Israeli brands

### PR DESCRIPTION
**Pull request by yotamN**
I'm working on adding a lot of missing Israeli brands. I haven't done yet but it would be helpful to get some feedback before I add all of the brands.

### CODE REVIEW

**Comment by Adamant36** [comment]
Just a general comment, its always better to do things in a bunch of smaller PR's if you can versus one big one. As its easier to review etc. Especially when adding new brands. My personal opinion is that you should probably stop adding entries at this point and do the rest in a new PR. It really doesn't matter since iD doesn't support them immediately anyway.  

Also, its good to run "npm run build" before commiting the PR if you can because it will organize things and point out any errors.

**Comment by Adamant36** [comment]
Btw, are the brand:he and name:he values for Cofix correct?

**Comment by bhousel** [comment]
Thanks @yotamN , looks good 👍

**Comment by bhousel** [comment]
oh wait no, these look a bit wrong.. The `name` tag should probably be in Hebrew if that's how it is signed in real life.  Either way, it should match the name suggestion index key.

```js
  "amenity/cafe|קופיז": {       /// <-- the name here in the key
    "countryCodes": ["il"],
    "tags": {
      "amenity": "cafe",
      "brand": "Cofizz",
      "brand:en": "Cofizz",
      "brand:he": "Cofizz",
      "brand:wikidata": "Q64606270",
      "cuisine": "coffee_shop",
      "name": "Cofizz",               /// <-- should match the name here in the tag
      "name:en": "Cofizz",
      "name:he": "Cofizz",
      "takeaway": "yes"
    }
  },
```

**Comment by yotamN** [comment]
Oops, I accidentally used the English name, I will fix it on Friday.

**Comment by yotamN** [comment]
I've fixed the pull request and will add the rest of the brands in different pull requests.

**Comment by yotamN** [comment]
I've fixed the name fields and run `npm run build` again but I got two warnings about "Brands match other brands" which I don't understand.

**Comment by bhousel** [comment]
Thanks @yotamN 👍

**Pull request merged**
