### PR TITLE
Rename Pearle to Pearle Vision

### PR DESCRIPTION
**Pull request by tas50**
It's on the wikipedia page, their website, and their past and present
logos.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by matkoniecz** [comment]
Note OSM data - http://overpass-turbo.eu/s/JmJ http://overpass-turbo.eu/s/JmL

Austria, Belgium, Netherlands have large number of `name=Pearle shop=optican`

Is it case of two separate brands or brand using two versions? Maybe country codes limitation is necessary?

**Comment by Adamant36** [comment]
@matkoniecz, it seems to be two different brands. Here's the Wikipedia article for Pearle https://nl.wikipedia.org/wiki/Pearle

**Comment by tas50** [comment]
Looks like we have 2 distinct brands. Let's hold off on this PR until I figure out if it should be split.

**Comment by bhousel** [comment]
This seems fine..

**Comment by tas50** [comment]
I still plan to figure out the European vs. US branding of this so we can autocorrect both correctly.

**Comment by bhousel** [comment]
That’s fine.. I just drove by a few of these this week and they all say “pearle vision”

**Comment by tas50** [comment]
In the US they're all Pearle Vision. Apparently not so much in Europe.

**Pull request merged**
