### PR TITLE
add c-town supermarkets

### LINKED ISSUE #2455: C-Town Supermarkets
The stores are labeled: "C-Town" in physical locations.

https://www.wikidata.org/wiki/Q5005929

### PR DESCRIPTION
**Pull request by yoasif**
closes  #2455

### CODE REVIEW

**Comment by Adamant36** [comment]
How come you removed the Acme entries in it?

**Comment by yoasif** [comment]
I didn't remove anything, I think that Git is detecting a change between the master and my commit.

**Comment by Adamant36** [comment]
Hhmmm, weird. Alright.

**Comment by matkoniecz** [comment]
I wonder whatever https://www.openstreetmap.org/way/422820424#map=18/31.95994/35.85947 https://www.openstreetmap.org/node/3583903213 are mistaggings or accidental name matches or shops from this brand outside USA.

**Comment by matkoniecz** [comment]
But given Wikipedia and dominating use in USA I think it is OK to ignore it for now. If usage outside USA grows we can review it again.

**Comment by matkoniecz** [comment]
Argh, I should also squash it. Too late now.

**Pull request merged**
