### PR TITLE
Auchan localization in Rusia (Ашан)

### PR DESCRIPTION
**Pull request by afanasovich**
I have created a separate entry for a subsidiary of Auchan in Russia -- Q110053013. It has a different legal form, a localized logo, and other social media accounts.

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Hi @afanasovich - this edit seems to remove "_ua_" (Ukraine) from the entry, was this intentional?

**Comment by afanasovich** [comment]
> Hi @afanasovich - this edit seems to remove "_ua_" (Ukraine) from the entry, was this intentional?

Auchan use international logo In Ukraine https://auchan.ua/

In Russia Auchan use Cyrillic logo 
https://ru.wikipedia.org/wiki/Файл:Auchan-logo.svg
https://www.auchan.ru/

**Comment by UKChris-osm** [comment]
Would adding "_ua_" to one of the other entries be suitable, or creating one for "_ua_" as well? It's just your edit seems to remove Ukraine from the index entirely for Auchan.

**Comment by afanasovich** [comment]
> I think that *ua* should be added to the international brand [auchan-0ffad6](https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&tt=auchan#auchan-0ffad6).

**Comment by bhousel** [comment]
It turns out that Ukraine is already included in the other "Auchan" locationSet, because it includes `151` for "Eastern Europe".  I did just now exclude Russia from it, so I think this is probably [a decent locationSet for "Auchan"](https://location-conflation.com/?locationSet=%7B%0A%22include%22%3A%20%5B%22039%22%2C%20%22151%22%2C%20%22155%22%2C%20%22cn%22%5D%2C%0A%22exclude%22%3A%20%5B%22ru%22%5D%0A%7D)

**Pull request merged**
