### PR TITLE
Resolve issue #4273 Add mr biggs

### PR DESCRIPTION
**Pull request by TheDynamicPunk**

### CODE REVIEW

**Comment by Adamant36** [comment]
Thanks 👍

**Comment by TheDynamicPunk** [comment]
@Adamant36 Welcome! Can you please add this label - '**_hacktoberfest-accepted_**' to my closed pr's as they're not being accepted in hacktoberfest. Thanks you guys are awesome!

**Comment by bhousel** [comment]
> Welcome! Can you please add this label - '**_hacktoberfest-accepted_**' to my closed pr's as they're not being accepted in hacktoberfest. Thanks you guys are awesome!

I'm pretty sure they will be accepted eventually.. I'll review the guidelines, but I know we never needed to label each PR in the past.

**Comment by TheDynamicPunk** [comment]
@bhousel Ohh okay. I was asking as this is what it tell me to do in my profile section in the hacktoberfest website. It's my first time so pardon if my questions or any comment sound too silly sometimes😅

**Comment by Adamant36** [comment]
The rules section of the website says "PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest." So, you shouldn't have anything to worry about 👍

**Comment by TheDynamicPunk** [comment]
@Adamant36 Okay. Thanks for clarifying 😄

**Comment by UKChris-osm** [comment]
It seems this year projects only count when they have been opted in by a project maintainer, and so I have added the "_hacktoberfest_" tag to the topic tags of the Name Suggestion Index, which should be enough to have all PR's count from this point on :)

**Comment by TheDynamicPunk** [comment]
@UKChris-osm Thanks! I saw it [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update) that as of 3rd October it is updated.

**Pull request merged**
