### PR TITLE
Created "audiologist.json" under "/brands/healthcare/"

### PR DESCRIPTION
**Pull request by UKChris-osm**
Created "_audiologist.json_" under "**/brands/healthcare/**", and added "_Imperial Hearing_", a UK hearing specialist, with roughly 36 branches / locations.

Created a pull request to enable it to be reviewed by others, rather than just adding it myself, as it involved creating a new file.

### CODE REVIEW

**Comment by UKChris-osm** [comment]
I'm slightly confused buy this, as I only created the one file, but this pull request seem to have 4 old edits included?

**Comment by SilentSpike** [comment]
If those edits were merged in other PRs it's possible they were done as squash commits which will change the commit IDs of the changes. This means your branch now differs from the upstream.

In general it's good practise to branch off of `master` for PRs and then you can just delete the branches once those PRs are done and then merge the upstream changes back into your master branch.

Unsure how familiar you are with git so some of this may not make sense to you, I can walk you through how to fix this PR if you'd like. As it looks like you now have collaborator access here you can even create future PRs using branches in this repository which will avoid any such issues.

**Comment by UKChris-osm** [comment]
> In general it's good practise to branch off of `master` for PRs and then you can just delete the branches once those PRs are done and then merge the upstream changes back into your master branch.

The thing that has confused me is that is what I usually do, and that I had only just forked the NSI master only a minute or so prior to creating the new audiologist file, so was under the impression it was a brand new, up to date fresh fork.

I'll close and remove this pull request, and try again, thanks @SilentSpike :)

**Comment by UKChris-osm** [comment]
Trying again with #3577

**Pull request closed without merging**
