### PR TITLE
Adding details for Associated Bank

### LINKED ISSUE #186: Research needed for: amenity/bank|Associated Bank
#### :thinking: We need help deciding what to do with "amenity/bank|Associated Bank"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `amenity/bank|Associated Bank` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `amenity/bank|Associated Bank`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `amenity/bank|Associated Bank`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

### PR DESCRIPTION
**Pull request by iandees**
Fixes #186

### CODE REVIEW

**Comment by matkoniecz** [comment]
> [wip]

Is there something incomplete? It looks OK for me.

**Comment by iandees** [comment]
I hadn't run `npm run build` yet.

**Comment by matkoniecz** [comment]
And it is now ready, right?

**Comment by iandees** [comment]
Yep, all set.

**Pull request merged**
