### PR TITLE
update BBVA names

### LINKED ISSUE #4650: BBVA Francés is the former name of BBVA Argentina
According wikipedia, [BBVA Francés](https://nsi.guide/index.html?t=brands&k=amenity&v=bank&tt=BBVA%20Francés) is the former name of [BBVA Argentina](https://www.bbva.com.ar).

See [brands/amenity/bank.json#L2184-L2199](https://github.com/osmlab/name-suggestion-index/blob/c9e02f02b60016c84001899c63b8375c0f04f619/data/brands/amenity/bank.json#L2184-L2199).

I suggest to remove theses tags too :
```json
"brand:en": "BBVA France"
"brand:fr": "BBVA France"
"brand:wikipedia": "en:BBVA Francés"
"name:en": "BBVA France"
"name:fr": "BBVA Francés"
```

I don't know if it's possible to keep the former name as a "synonym" with `displayName` ?
 ```json
    {
      "displayName": "BBVA Argentina (formely BBVA Francés)",
      "id": "bbvafrances-841353",
      "locationSet": {"include": ["ar"]},
      "tags": {
        "amenity": "bank",
        "brand": "BBVA Argentina",
        "brand:wikidata": "Q2876788",
        "name": "BBVA Argentina",
      }
    },
```

### PR DESCRIPTION
**Pull request by gedankenstuecke**
This updates the names of the different BBVA branches in the different countries, as suggested in #4650, to avoid stale suggestions. 

closes #4650

### CODE REVIEW

**Comment by kjonosm** [comment]
@gedankenstuecke You might want to keep the old names as `matchNames` to trigger suggestions in iD.

**Comment by gedankenstuecke** [comment]
Oh thanks, I knew I had forgotten something after reading the docs! :see_no_evil: 

I've added those in, would matchTags for the old brand names also be useful or would that be duplicating the name matching?

**Comment by kjonosm** [comment]
Thanks for the update @gedankenstuecke!
For `BBVA Argentina` you can add both previous name variants `BBVA Francés` and `BBVA France` as `matchNames`.
Also, for `BBVA Argentina` you can omit both local name variants as they are indifferent.

**Comment by gedankenstuecke** [comment]
Thanks for walking me through this @kjonosm, that's so helpful to get more familiar with the structure! :pray: 

I've made those edits too :-)

**Comment by kjonosm** [comment]
Looks good now. Thanks!

**Comment by gedankenstuecke** [comment]
Thanks so much for the help again! :heart:

**Comment by Cj-Malone** [comment]
Should the `Bancomer` entry also be removed?

> BBVA México, formerly Bancomer

https://en.wikipedia.org/wiki/BBVA_M%C3%A9xico

**Pull request merged**
