### PR TITLE
Update frozen_food.json

### PR DESCRIPTION
**Pull request by MortalEngineXXII**
Simplifying names

### CODE REVIEW

**Review by serhii-muchychka — CHANGES_REQUESTED** [review]
In my opinion the changes in this PR have nothing to do with reality and are just your personal vision of how it should be. The best we can do is discuss with the local OSM community how best to do this.
For more details see
https://github.com/osmlab/name-suggestion-index/issues/9386#issuecomment-2070774428
https://github.com/osmlab/name-suggestion-index/issues/9386#issuecomment-2070783739

**Comment by MortalEngineXXII** [comment]
All this is already described in the rules. [See this](https://wiki.openstreetmap.org/wiki/Uk:%D0%9D%D0%B0%D0%B7%D0%B2%D0%B8#Name_%E2%80%94_%D1%82%D1%96%D0%BB%D1%8C%D0%BA%D0%B8_%D0%B4%D0%BB%D1%8F_%D0%BD%D0%B0%D0%B7%D0%B2). The slogan (like "Елікатні радощі життя!") can be specified in a [separate tag](https://wiki.openstreetmap.org/wiki/Key:strapline)

**Comment by serhii-muchychka** [comment]
I can't say unequivocally whether this is a slogan, because both options are meaningless phrases. I insist that this should be discussed with the community

**Comment by MortalEngineXXII** [comment]
I've started a discussion in the local community, you can join in if you want https://t.me/osmUA

**Comment by bhousel** [comment]
Following up, did you decide what to do with these names?

**Comment by MortalEngineXXII** [comment]
Hello. I have started a [discussion](https://community.openstreetmap.org/t/topic/113416) on this issue, but there is no consensus yet.

**Pull request closed without merging**
