### PR TITLE
Add China Telecom into telecommunication.json

### PR DESCRIPTION
**Pull request by LaoshuBaby**

### CODE REVIEW

**Comment by UKChris-osm** [comment]
Thank you @LaoshuBaby 

Do you know if China Telecom have any social media links that can be added to the Wikidata article, such as Facebook or Twitter? We can use those logo's to add to the index if they are available 👍

**Comment by LaoshuBaby** [comment]
> 
> 
> Thank you @LaoshuBaby
> 
> Do you know if China Telecom have any social media links that can be added to the Wikidata article, such as Facebook or Twitter? We can use those logo's to add to the index if they are available 👍

If I can I will really willing to add more information into this brand.

But the fact is that usually Chinese company won't set up Facebook or Twitter account. And I found that there are a lot of fake account of some famous Chinese company.

So if CT is OK, I will add more chain-brand which very-famous into NSI list.

Thank you for your review!

**Comment by LaoshuBaby** [comment]
> 
> 
> > Thank you @LaoshuBaby
> > Do you know if China Telecom have any social media links that can be added to the Wikidata article, such as Facebook or Twitter? We can use those logo's to add to the index if they are available 👍
> 
> If I can I will really willing to add more information into this brand.
> 
> But the fact is that usually Chinese company won't set up Facebook or Twitter account. And I found that there are a lot of fake account of some famous Chinese company.
> 
> So if CT is OK, I will add more chain-brand which very-famous into NSI list.
> 
> Thank you for your review!

I will choose the brand that have Wikidata and have nation-wide chain-store.

**Comment by UKChris-osm** [comment]
Thanks for the feedback about Facebook and Twitter in China @LaoshuBaby 👍

**Pull request merged**
