### PR TITLE
Added wiki tags for Wellcome

### LINKED ISSUE #1800: Research needed for: shop/supermarket|惠康 Wellcome
#### :thinking: We need help deciding what to do with "shop/supermarket|惠康 Wellcome"

:point_right: Read the [CONTRIBUTING.md](https://github.com/osmlab/name-suggestion-index/blob/master/CONTRIBUTING.md) guide for more info, and feel free to ask questions on this issue!

### What's needed

First, do some research on `shop/supermarket|惠康 Wellcome` by searching Google and Wikipedia.

#### If it is an actual brand:

* Edit `config/canonical.json`:
  * Find the entry for `shop/supermarket|惠康 Wellcome`
  * Add tags for `brand:wikidata` and `brand:wikipedia`
  * Optionally add `"countryCodes"` or other tags
* `npm run build`
* Commit your changes and submit a pull request

#### If it is not an actual brand:

* Edit `config/filters.json` to add an expression that discards it
* Edit `config/canonical.json` to remove the entry for `shop/supermarket|惠康 Wellcome`
* `npm run build`
* Commit your changes and submit a pull request

#### If the situation is complicated:

* Leave a comment on this issue with what you find

:sparkles: Thanks!

_This is an autogenerated ticket_

### PR DESCRIPTION
**Pull request by xeluna**
Closes #1800

### CODE REVIEW

**Comment by ENT8R** [comment]
There are some unrelated changes of `dist/discardNames.json` and `dist/keepNames.json` that look unintended... Could you maybe look at them?

**Comment by xeluna** [comment]
Those came out of a run of `npm run build`... I'll remove them.

**Comment by ENT8R** [comment]
Oops, sorry, my fault... Somebody didn't ran the build script, so you were the first person that includes those changes in a PR... Could you maybe run `npm run build` again and push that commit or simply revert the commit? Sorry for the noise...

**Comment by xeluna** [comment]
Sure thing, no problem.

**Comment by ENT8R** [comment]
Thank you very much 👍

**Pull request merged**
