### PR TITLE
Fix 美而美 series brand

### PR DESCRIPTION
**Pull request by LaoshuBaby**
According to #4956 , just fixed a headache brand series problem.

Below are note about this.

 (written in Chinese, to feedback to that DWG menber supaplex, sure that he can understand)

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
大家好，这个问题还算挺复杂的。

在这之前我应说明，注意到有一些品牌被错误的放在了resturant而非fast_food中。私以为这种快餐式的，能带走的汉堡也好，早点也好，并非注重在室内享受食物本身，而是尽快迅速的能填饱肚子。而人们心目中，这和正餐进餐的餐馆也是有区别的。尤其是在我所生活的大陆地区更是如此。汉堡店就应该和KFC或麦当劳一起，都被视作fast_food。

首先是品牌拆分后的wikidata和wikipedia问题。

本人并不生活在台湾地区，故对该地区品牌的了解仅可通过互联网搜索得知。由wikipedia来看，早安美芝城这个品牌相较于其他三个拆分后的品牌，或许是更为出名的。因此目前仅能搜索到它有独立的wikidata和wikipedia词条。故其余的三个品牌，巨林、瑞麟、弘爷，鄙人只好统一使用原有的美而美的词条对应的wikidata。

其次是关于品牌的海外经营问题。

美而美品牌在大陆是有经营加盟店的，但就所了解到的情况来看，其加盟仅限于台湾地区四个分支品牌中的一个，即瑞麟美而美这个品牌。但在大陆地区并没有前缀，就搜索到的情况，是直接叫做美而美的。之后对这两部分进行了排除，对其他可能存在的国家地区中的该品牌以英文表示了。

最后，因为考虑到不同公司分别经营四个品牌，出于避免混淆的目的，加入了operator字段。

若有不当之处，还请批评指正。

**Comment by bhousel** [comment]
Thanks for your research @LaoshuBaby 👍 

For the restaurant/fast_food question, I believe the convention is that 
- `amenity=restaurant` for a place where a host seats you and a waiter takes your order (aka "table service"), and 
- `amenity=fast_food` for a place where you order food from a counter (includes ["fast casual"](https://en.wikipedia.org/wiki/Fast_casual_restaurant) style)

**Comment by bhousel** [comment]
A cool GitHub tip for future PRs - you can include some text like "closes #4956" in your commit message or pull request, and GitHub will close the issue for us automatically when it merges. 💪

**Comment by LaoshuBaby** [comment]
Ah, yes, what you said is very vivid and concise, that's right. And for the close issue way it is the first time i just heard, thanks for your warm-heart.



Besides, the reason I haven't close issue and pr is because this problem is risen by that DWG worker. And I think this time the changes is bigger than I made former, so just waiting for the community to judge it.


Thanks twice for your quickly response

---原始邮件---
发件人: "Bryan ***@***.***&gt;
发送时间: 2021年3月22日(周一) 凌晨2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [osmlab/name-suggestion-index] Fix 美而美 series brand (#4987)




 
Thanks for your research @LaoshuBaby 👍
 
For the restaurant/fast_food question, I believe the convention is that
  
amenity=restaurant for a place where a host seats you and a waiter takes your order (aka "table service"), and 

amenity=fast_food for a place where you order food from a counter (includes "fast casual" style)

**Pull request merged**
