### PR TITLE
Add Sagawa Express and Yamato Transport

### PR DESCRIPTION
**Pull request by sguinetti**
This pull requests adds courier brands, Sagawa Express and Yamato Transport.

### CODE REVIEW

**Comment by Adamant36** [comment]
What are these being tagged on exactly? Is it like a mail/shipping store or something?

**Comment by sguinetti** [comment]
As far as I know, these are brands for transporting of private and commercial goods. For example, [Yamato](http://www.global-yamato.com/en/hands-free-travel/facilities/) shows delivery icons of goods. Japan Post is for sending mail (and I imagine it's the only one) for [the world](https://www.post.japanpost.jp/int/index_en.html).

**Comment by sguinetti** [comment]
Accourding to [Wikipedia](https://en.wikipedia.org/wiki/Courier):

> Couriers are distinguished from ordinary mail services by features such as speed, security, tracking, signature, specialization and individualization of express services, and swift delivery times, which are optional for most everyday mail services. As a premium service, couriers are usually more expensive than standard mail services, and their use is normally limited to packages where one or more of these features are considered important enough to warrant the cost.

In short, the right thing to tag is "courier office" than "mail office".

Note: Logist is for big corporations. While they admit, the services are very expensive. I put courier because it is a permissive term for individuals and companies, regardless of their economic situation.

**Comment by Adamant36** [comment]
Hmmm looking over it, this sounds like it would be similar to a mail/package carrier like UPS. Which is currently tagged as amenity=post_office. The Wiki says that tag applies to "A place where letters and parcels may be sent or collected." Cost and who they ship with or to doesn't really matter that much. Like both these places just look like UPS stores. 
unnamed

**Comment by sguinetti** [comment]
Interesting comparison of an American courier company. However, that makes me a little doubtful because UPS is labeled as amenity=post_office. However, the issue of mail delivery and collection is unique to Japan Post. In fact, it says so [on Wikipedia](https://ja.wikipedia.org/wiki/%E9%9B%86%E9%85%8D%E9%83%B5%E4%BE%BF%E5%B1%80).

In my opinion a courier is a particular and distinctive service to the national or state mail. For example, I have seen with Olva Courier that it offers distinctions in Peru. Although reviewing, they made a proposal to use the label amenity=courier, but [they rejected it](https://wiki.openstreetmap.org/wiki/Proposed_features/courier).

**Comment by sguinetti** [comment]
For now and not to be confusing, I change this proposal to amenity=post_office. I hope that in the future they will discuss the proposal of amenity=courier.

**Comment by Adamant36** [comment]
> Interesting comparison of an American courier company. However, that makes me a little doubtful because UPS is labeled as amenity=post_office.

Honestly, I'm not a big fan of UPS being tagged as a post office either. I'd much prefer something like amenity=carrier myself, but the OSM community can be a harsh task master if you go against established tagging conventions. So, that's how it is. 

I'm aware that there regional differences sometimes, but generally tags in OSM are suppose to be globally applicable and based on British English standards. I'm trying to follow conventions a little more after letting amenity=karaoke_box slide, when it is still a proposal and not used much outside of Japan. While I think that was the right choice in the moment, going with a rejected proposal in this case, to respect regional differences, wouldn't be. 

You have to watch out for not creating tagging fragmentation anyway. It's a global map and we should expect tags to be extremely similar no matter where we use, no matter how locals tag things.  Like in America where I live practically every town you go has a different way of using the leisure=park tag and we can't agree on a standard for it. So, there's no way to accurately find parks in OSM here. With brands you have to be more narrow and specific about your tags IMO.

**Comment by bhousel** [comment]
These entries stayed in the `office/post_office.json` file, so in 792a8df I moved them back to the `amenity/post_office.json` file and fixed the keys so they will stay there.

**Pull request merged**
