### PR TITLE
Add wikipedia entry for Only store

### PR DESCRIPTION
**Pull request by tas50**
It's a European Denim brand. I created the wikidata page which is basically empty since there wasn't one.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
Resolves https://github.com/osmlab/name-suggestion-index/issues/1193

**Comment by Adamant36** [comment]
Thanks for creating the wikidata pages.

**Comment by Adamant36** [comment]
Maybe you could relate it to the operator on the wikidata page somehow. I'm not sure how that works, but at least it would have something on it then.

**Comment by tas50** [comment]
That one is already linked between the brand and the parent org. I've tried to do that to all of them.

**Comment by Adamant36** [comment]
Ok cool.

**Pull request merged**
