### PR TITLE
Update police.json

### PR DESCRIPTION
**Pull request by Mannivu**
Fix capitalization: "locale" and "municipale" are simple adjectives, not proper nouns, so they should start with a lowercase letter

### CODE REVIEW

**Comment by Adamant36** [comment]
It looks like they can be either way. For instance Wikipedia has it as capital letters. Same goes for their [official website](https://www.poliziamunicipale.it/).

**Comment by Mannivu** [comment]
> Same goes for their [official website](https://www.poliziamunicipale.it/)

If we follow the official website, we should write "PoliziaMunicipale" without spaces. Anyway, "municipale" and "locale" are simple adjectives, and those police forces are not centralised (so, the official website is not really an official website), and they are not linked with each other. They all respond to the city mayor, and are not part of any Ministery (which is the case for Arma dei Carabinieri, Polizia di Stato, Guardia di Finanza, and Guardia Costiera; these are also capitalised since those are proper noun, not simple adjectives).

**Comment by kjonosm** [comment]
By current numbers, the Italian community clearly favours `Polizia Municipale` [overpass link](https://overpass-turbo.eu/s/1oxv) over `Polizia municipale` [overpass link](https://overpass-turbo.eu/s/1oxu). It also clearly favours `Polizia Locale` [overpass link](https://overpass-turbo.eu/s/1oxA) over `Polizia locale` [overpass link](https://overpass-turbo.eu/s/1oxB).

I don't see a reason for NSI to change accepted tagging in that regard.

**Comment by bhousel** [comment]
Just want to confirm that "Local Police" and "Municipal Police" really commonly tagged things, like a recognizable brand?  

Normally we would exclude names like this from NSI.. but maybe in Italy this is what you want?

**Comment by Mannivu** [comment]
> By current numbers, the Italian community clearly favours Polizia Municipale [overpass link](https://overpass-turbo.eu/s/1oxv) over Polizia municipale [overpass link](https://overpass-turbo.eu/s/1oxu). It also clearly favours Polizia Locale [overpass link](https://overpass-turbo.eu/s/1oxA) over Polizia locale [overpass link](https://overpass-turbo.eu/s/1oxB).

@kjonosm  this might be affected from the NSI itself, since I'm not adding something new, but updating something that has been present on the NSI for awhile (so, stating that the local communty prefers the Capital letter version it's not correct; there should be a more deep research).

@bhousel this is pretty hard to articulate, but I'll do my best. In Italy, almost every Comune (which is the smallest administrative entity in Italy) has a Polizia municipale, which are not linked between them, but all have the same duties (which are regulated by a specific law). So, even if they are not entirely linked, they act as a linked network. The Polizia locale is an hyperonym, since it comprehends Polizia municipale, Polizia provinciale and Polizia regionale. But, explaining it to you, I wonder if you are right and maybe a network tag is more appropriate. I'll ask with the Italian community.

**Comment by kjonosm** [comment]
@Mannivu looking at the different colours in linked overpass turbo query results one can assume that only green coloured  points are probably updated via NSI suggestion. The remaining yellow points still outnumber your suggested spelling by far.

**Comment by kjonosm** [comment]
However, @bhousel's question remains, whether to keep these general entries for those types of police forces at all or just exclude them because they really should be differentiated as e.g. listed here: https://www.poliziamunicipale.it/comuni

**Comment by Adamant36** [comment]
>The official website is not really an official website

By official I really meant "main" since what we usually go with when it comes to how to spell a default is what people are most likely going to see IRL (or in this case when looking at "official" documents). Personally, I could really care if it's "official" or not, but the fact remains that people are usually going to see Polizia Municipale in capital letters when viewing the website. As well as well as other places, for instance their police uniforms. I'm sure you'll have a reason that how it's spelled on the uniforms should be disregarded to though.
italian-polizia

What about how it's spelled on the sides of their cars? 

360_F_468306719_UKA4Vp3HwN6ek9tN6Kaa304NgpzerF69

No? What about the signs in front of their buildings? 

italian-police-station-with-polizia-municipale-car-parked-outside-E62MYK

I'm sure you get my point.

**Comment by Mannivu** [comment]
UPDATE
Based on the ML inquiry, the Italian community has suggested that "Polizia locale" and "Polizia municipale" should not be part of the NSI, since there's no central governance and are therefore all separate entities.

**Comment by bhousel** [comment]
> Based on the ML inquiry, the Italian community has suggested that "Polizia locale" and "Polizia municipale" should not be part of the NSI, since there's no central governance and are therefore all separate entities.

Thanks for checking!
I'm also going to add these as named exclude so they dont return when we process the osm planet.

**Comment by Mannivu** [comment]
> I'm also going to add these as named exclude so they dont return when we process the osm planet.

Thank you!

**Pull request merged**
